import {scryptSync,timingSafeEqual,randomBytes,createHash} from 'node:crypto';
import validation from '../../public/shared/validation.js';
export const accountSchema=[
 `CREATE TABLE IF NOT EXISTS site_customers(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,phone TEXT UNIQUE NOT NULL,name TEXT NOT NULL,email TEXT,password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,session_version INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,last_login TEXT)`,
 `CREATE TABLE IF NOT EXISTS site_sessions(token_hash TEXT PRIMARY KEY,customer_id TEXT NOT NULL,revision INTEGER NOT NULL,expires_at INTEGER NOT NULL,last_used_at INTEGER NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS site_addresses(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,details TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS site_favourites(customer_id TEXT NOT NULL,product_id INTEGER NOT NULL,PRIMARY KEY(customer_id,product_id))`,
 `CREATE TABLE IF NOT EXISTS site_recovery(token_hash TEXT PRIMARY KEY,customer_id TEXT NOT NULL,expires_at INTEGER NOT NULL,used_at INTEGER)`,
 `CREATE TABLE IF NOT EXISTS site_customer_orders(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,payload TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TABLE IF NOT EXISTS site_loyalty(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,order_id TEXT,type TEXT NOT NULL,delta INTEGER NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,reason TEXT NOT NULL,actor TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TRIGGER IF NOT EXISTS site_loyalty_no_update BEFORE UPDATE ON site_loyalty BEGIN SELECT RAISE(ABORT,'Loyalty ledger is immutable');END`,
 `CREATE TRIGGER IF NOT EXISTS site_loyalty_no_delete BEFORE DELETE ON site_loyalty BEGIN SELECT RAISE(ABORT,'Loyalty ledger is immutable');END`,
 `CREATE TRIGGER IF NOT EXISTS site_loyalty_no_overspend BEFORE INSERT ON site_loyalty WHEN NEW.type='redeem' AND NOT EXISTS(SELECT 1 FROM site_loyalty WHERE idempotency_key=NEW.idempotency_key) AND COALESCE((SELECT SUM(delta) FROM site_loyalty WHERE customer_id=NEW.customer_id),0)+NEW.delta<0 BEGIN SELECT RAISE(ABORT,'Insufficient points');END`
];
const sha=value=>createHash('sha256').update(value).digest('hex');
export function passwordHash(password){if(typeof password!=='string'||password.length<12||password.length>128)throw Error('Use a password of 12–128 characters');const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64,{N:16384,r:8,p:1}).toString('hex')}
export function passwordVerify(password,stored){const [salt,expected]=String(stored).split(':');if(!salt||!/^[a-f0-9]{128}$/.test(expected)||String(password).length>128)return false;return timingSafeEqual(scryptSync(String(password),salt,64),Buffer.from(expected,'hex'))}
const token=request=>(request.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-tb_customer='))?.split('=')[1];
export async function customerSession(db,request){const value=token(request);if(!value)return null;const row=await db.one('SELECT c.* FROM site_sessions s JOIN site_customers c ON c.id=s.customer_id WHERE s.token_hash=? AND s.expires_at>? AND c.active=1 AND c.session_version=s.revision',sha(value),Date.now());if(row)await db.run('UPDATE site_sessions SET last_used_at=? WHERE token_hash=?',Date.now(),sha(value));return row}
const cookie=(value,age=2592000)=>`__Host-tb_customer=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
export function customerView(row){return {id:row.id,customer_id:row.id,member_code:'TB-'+String(row.seq).padStart(6,'0'),name:row.name,phone:row.phone,email:row.email,active:!!row.active,created_at:row.created_at,last_login:row.last_login}}
async function createSession(db,row,json){const value=randomBytes(32).toString('hex');await db.batch([['INSERT INTO site_sessions(token_hash,customer_id,revision,expires_at,last_used_at) VALUES(?,?,?,?,?)',sha(value),row.id,row.session_version,Date.now()+30*86400000,Date.now()],['UPDATE site_customers SET last_login=CURRENT_TIMESTAMP WHERE id=?',row.id]]);const response=json({customer:customerView(row)});response.headers.set('set-cookie',cookie(value));return response}
async function limit(db,request,kind){const window=Math.floor(Date.now()/60000),bucket=sha(kind+':'+(request.headers.get('cf-connecting-ip')||'unknown')+':'+window);const row=await db.one('INSERT INTO site_rate_limits(bucket,count,expires_at) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count',bucket,(window+2)*60000);return row.count<=8}
export async function accountApi(ctx){const {db,request,url,body,json,fail,state}=ctx,path=url.pathname,verb=request.method;if(!path.startsWith('/api/account/'))return null;
 if(verb!=='GET'&&request.headers.get('origin')!==url.origin)fail(403,'Same-origin request required');
 if(['/api/account/signup','/api/account/login','/api/account/recover','/api/account/reset'].includes(path)&&verb==='POST'){
  if(!await limit(db,request,path))fail(429,'Please wait before trying again');const b=await body(request);
  if(path.endsWith('/recover'))return json({ok:true,message:'Contact the restaurant for identity-verified recovery. SMS/email delivery is not configured.'});
  if(path.endsWith('/reset')){let hashed;try{hashed=passwordHash(b.password)}catch(e){fail(400,e.message)}const key=sha(String(b.token||'')),recovery=await db.one('SELECT * FROM site_recovery WHERE token_hash=? AND used_at IS NULL AND expires_at>?',key,Date.now());if(!recovery)fail(400,'Invalid or expired recovery token');await db.batch([['UPDATE site_customers SET password_hash=?,session_version=session_version+1 WHERE id=? AND EXISTS(SELECT 1 FROM site_recovery WHERE token_hash=? AND used_at IS NULL AND expires_at>?)',hashed,recovery.customer_id,key,Date.now()],['UPDATE site_recovery SET used_at=? WHERE token_hash=? AND used_at IS NULL',Date.now(),key]]);return json({ok:true})}
  let phone;try{phone=validation.phone(b.phone)}catch(e){fail(400,e.message)}
  if(path.endsWith('/signup')){let hashed;try{hashed=passwordHash(b.password)}catch(e){fail(400,e.message)}const name=String(b.name||'').trim();if(!name||name.length>100)fail(400,'Name required');const email=String(b.email||'').trim();if(email&&(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254))fail(400,'Invalid email');const id=crypto.randomUUID();try{await db.run('INSERT INTO site_customers(id,phone,name,email,password_hash) VALUES(?,?,?,?,?)',id,phone,name,email||null,hashed)}catch{fail(409,'Account could not be created. Sign in or contact the restaurant.')}
   return createSession(db,await db.one('SELECT * FROM site_customers WHERE id=?',id),json);
  }
  const row=await db.one('SELECT * FROM site_customers WHERE phone=? AND active=1',phone);if(!row||!passwordVerify(b.password,row.password_hash))fail(401,'Invalid phone or password');return createSession(db,row,json);
 }
 const customer=await customerSession(db,request);if(!customer){if(path==='/api/account/me'&&verb==='GET')return json({customer:null});fail(401,'Sign in required')}
 if(path==='/api/account/logout'&&verb==='POST'){await db.run('DELETE FROM site_sessions WHERE token_hash=?',sha(token(request)));const response=json({ok:true});response.headers.set('set-cookie',cookie('',0));return response}
 if(path==='/api/account/me'&&verb==='GET')return json({customer:customerView(customer),addresses:(await db.all('SELECT id,details FROM site_addresses WHERE customer_id=?',customer.id)).map(a=>({id:a.id,...JSON.parse(a.details)})),favourites:(await db.all('SELECT product_id FROM site_favourites WHERE customer_id=?',customer.id)).map(r=>r.product_id),points:(await db.one('SELECT COALESCE(SUM(delta),0) balance FROM site_loyalty WHERE customer_id=?',customer.id)).balance});
 if(path==='/api/account/profile'&&verb==='POST'){const b=await body(request),name=String(b.name||'').trim();if(!name||name.length>100)fail(400,'Name required');await db.run('UPDATE site_customers SET name=? WHERE id=?',name,customer.id);return json({ok:true})}
 if(path==='/api/account/password'&&verb==='POST'){const b=await body(request);if(!passwordVerify(b.currentPassword,customer.password_hash))fail(403,'Current password required');let hashed;try{hashed=passwordHash(b.password)}catch(e){fail(400,e.message)}await db.run('UPDATE site_customers SET password_hash=?,session_version=session_version+1 WHERE id=?',hashed,customer.id);return json({ok:true})}
 if(path==='/api/account/addresses'&&verb==='POST'){const b=await body(request);if(!b.fullAddress||String(b.fullAddress).length>500)fail(400,'Address required');const details=Object.fromEntries(['label','area','street','fullAddress','building','floor','apartment','landmark','alternativePhone','deliveryNotes'].map(k=>[k,String(b[k]||'').slice(0,500)])),id=crypto.randomUUID();await db.run('INSERT INTO site_addresses(id,customer_id,details) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM site_addresses WHERE customer_id=?)<20',id,customer.id,JSON.stringify(details),customer.id);return json({ok:true,id})}
 if(path.match(/^\/api\/account\/addresses\/[^/]+$/)&&verb==='DELETE'){await db.run('DELETE FROM site_addresses WHERE id=? AND customer_id=?',path.split('/').pop(),customer.id);return json({ok:true})}
 if(path==='/api/account/favourites'&&verb==='POST'){const b=await body(request);if(!Number.isInteger(b.productId)||b.productId<1)fail(400,'Invalid product');if(b.saved)await db.run('INSERT OR IGNORE INTO site_favourites VALUES(?,?)',customer.id,b.productId);else await db.run('DELETE FROM site_favourites WHERE customer_id=? AND product_id=?',customer.id,b.productId);return json({ok:true})}
 if(path==='/api/account/orders'&&verb==='GET'){const online=await db.all("SELECT * FROM site_orders WHERE json_extract(payload,'$.customerId')=? ORDER BY seq DESC LIMIT 100",customer.id),local=await db.all('SELECT payload FROM site_customer_orders WHERE customer_id=? ORDER BY updated_at DESC LIMIT 100',customer.id);const rows=online.map(o=>({id:o.id,sequential_no:o.seq+5000,date:o.created_at,total:o.total,status:o.status,payment_status:o.payment_status,trackingToken:o.tracking_token,items:JSON.parse(o.payload).items}));const ids=new Set(online.map(o=>o.local_order_id));return json({orders:[...rows,...local.map(r=>JSON.parse(r.payload)).filter(o=>!ids.has(o.id))]})}
 if(path==='/api/account/loyalty'&&verb==='GET'){const entries=await db.all('SELECT id,order_id,type,delta,reason,created_at FROM site_loyalty WHERE customer_id=? ORDER BY created_at DESC LIMIT 200',customer.id),balance=(await db.one('SELECT COALESCE(SUM(delta),0) balance FROM site_loyalty WHERE customer_id=?',customer.id)).balance;return json({balance,entries,rewards:JSON.parse(await state(db,'loyalty_rewards')||'[]').filter(r=>r.active),settings:JSON.parse(await state(db,'loyalty_settings')||'{"enabled":false}')})}
 fail(404,'Not found');
}
