import validation from '../../public/shared/validation.js';
import rules from '../../public/shared/loyalty.js';
export const redemptionSchema=[`CREATE TABLE IF NOT EXISTS site_redemptions(id TEXT PRIMARY KEY,request_key TEXT UNIQUE NOT NULL,request_hash TEXT NOT NULL,customer_id TEXT NOT NULL,reward TEXT NOT NULL,discount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'reserved',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`];
export async function redemptionApi({db,request,url,body,json,fail,state,digest}){if(!url.pathname.startsWith('/api/sync/loyalty/'))return null;const b=await body(request);if(request.method!=='POST')fail(405,'POST required');
 if(url.pathname==='/api/sync/loyalty/balance'){if(!await db.one('SELECT id FROM site_customers WHERE id=?',b.customerId))fail(404,'Customer not found');return json({points:(await db.one('SELECT COALESCE(SUM(delta),0) points FROM site_loyalty WHERE customer_id=?',b.customerId)).points,entries:await db.all('SELECT * FROM site_loyalty WHERE customer_id=? ORDER BY created_at DESC LIMIT 100',b.customerId)})}
 if(url.pathname==='/api/sync/loyalty/reserve'){let items,key;try{items=validation.items(b.items);key=validation.requestId(b.requestId,true)}catch(e){fail(400,e.message)}if(!await db.one('SELECT id FROM site_customers WHERE id=? AND active=1',b.customerId))fail(400,'Active customer account required');const hash=await digest(validation.canonical({items,customerId:b.customerId,rewardId:b.rewardId})),previous=await db.one('SELECT * FROM site_redemptions WHERE request_key=?',key);if(previous){if(previous.request_hash!==hash||previous.status==='released')fail(409,'Reservation request no longer usable');return json({reservation:{...previous,reward:JSON.parse(previous.reward)}})}
 const catalog=JSON.parse(await state(db,'catalog')||'{}');if(catalog.loyaltySettings?.enabled===false)fail(400,'Loyalty is disabled');for(const item of items){const p=catalog.products.find(p=>p.id===item.productId);if(!p)fail(400,'Product unavailable');item.price=Number(p.price);for(const id of item.modifiers){const mod=catalog.modifiers.find(m=>m.id===id&&m.product_id===item.productId);if(!mod)fail(400,'Modifier unavailable');item.price+=Number(mod.price)}}const reward=catalog.loyaltyRewards.find(r=>r.id===b.rewardId);let discount;try{discount=rules.discount(reward,items,items.reduce((n,i)=>n+i.price*i.qty,0))}catch(e){fail(400,e.message)}const id=crypto.randomUUID(),snapshot={...reward,redemption_key:'pos-redeem:'+key};
 try{await db.batch([['INSERT INTO site_redemptions(id,request_key,request_hash,customer_id,reward,discount) VALUES(?,?,?,?,?,?) ON CONFLICT(request_key) DO NOTHING',id,key,hash,b.customerId,JSON.stringify(snapshot),discount],['INSERT OR IGNORE INTO site_loyalty(id,customer_id,type,delta,idempotency_key,reason,actor) SELECT ?,customer_id,\'redeem\',?,?,?,? FROM site_redemptions WHERE request_key=? AND request_hash=?',crypto.randomUUID(),-reward.points_cost,snapshot.redemption_key,'POS reward reservation','pos',key,hash]])}catch(e){if(String(e).includes('Insufficient points'))fail(409,'Insufficient points');throw e}const saved=await db.one('SELECT * FROM site_redemptions WHERE request_key=?',key);if(saved.request_hash!==hash)fail(409,'Request ID already used');return json({reservation:{...saved,reward:JSON.parse(saved.reward)}});
 }
 if(url.pathname==='/api/sync/loyalty/release'){const row=await db.one('SELECT * FROM site_redemptions WHERE request_key=?',b.requestId);if(!row)fail(404,'Reservation not found');const reward=JSON.parse(row.reward);await db.batch([['INSERT OR IGNORE INTO site_loyalty(id,customer_id,type,delta,idempotency_key,reason,actor) SELECT ?,customer_id,\'redemption_reversal\',?,?,?,? FROM site_redemptions WHERE id=? AND status=\'reserved\'',crypto.randomUUID(),reward.points_cost,'release:'+row.id,'POS order was not committed','pos',row.id],['UPDATE site_redemptions SET status=\'released\' WHERE id=? AND status=\'reserved\'',row.id]]);return json({ok:true})}
 fail(404,'Not found');
}
