import {createHash,randomBytes} from 'node:crypto';
import {passwordVerify} from './accounts.mjs';
export const remoteSchema=[
 `CREATE TABLE IF NOT EXISTS site_staff(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,role TEXT NOT NULL,password_hash TEXT NOT NULL,active INTEGER NOT NULL,revision INTEGER NOT NULL,permissions TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS site_staff_sessions(token_hash TEXT PRIMARY KEY,staff_id TEXT NOT NULL,revision INTEGER NOT NULL,expires_at INTEGER NOT NULL,last_used_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TABLE IF NOT EXISTS site_commands(id TEXT PRIMARY KEY,installation_id TEXT NOT NULL,version INTEGER NOT NULL,operation TEXT NOT NULL,payload TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT NOT NULL DEFAULT 'Pending',result TEXT,expected_revision TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS site_admin_audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,entity_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`
];
const hash=v=>createHash('sha256').update(v).digest('hex');
const cookie=(v,age=43200)=>`__Host-tb_staff=${v}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;
const getToken=req=>(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(x=>x.startsWith('__Host-tb_staff='))?.split('=')[1];
export const operations=['menu.save','menu.price','category.save','modifier.save','public_settings.save','loyalty.settings','loyalty.reward'];
export async function remoteApi(ctx){const {db,request,url,body,json,fail,state,env}=ctx,p=url.pathname,m=request.method;
 if(p==='/api/sync/staff'&&m==='POST'){const b=await body(request,2e6);if(env.INSTALLATION_ID&&b.installationId!==env.INSTALLATION_ID)fail(403,'Incorrect installation');if(!Array.isArray(b.staff)||b.staff.length>100)fail(400,'Invalid staff');const writes=[['UPDATE site_staff SET active=0']];for(const u of b.staff){if(!['owner','manager'].includes(u.role)||!u.id||!u.password_hash)fail(400,'Invalid remote staff');writes.push(['INSERT INTO site_staff(id,username,role,password_hash,active,revision,permissions) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,role=excluded.role,password_hash=excluded.password_hash,active=excluded.active,revision=excluded.revision,permissions=excluded.permissions',u.id,u.username,u.role,u.password_hash,u.active?1:0,u.revision,JSON.stringify(u.permissions||[])])}writes.push(['INSERT INTO site_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','staff_revision',b.revision||'']);if(b.resources)writes.push(['INSERT INTO site_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','admin_resources',JSON.stringify(b.resources)]);await db.batch(writes);return json({ok:true})}
 if(p==='/api/sync/commands'&&m==='GET')return json({commands:await db.all("SELECT * FROM site_commands WHERE status IN ('Pending','Delivered') ORDER BY created_at,id LIMIT 30")});
 const ack=p.match(/^\/api\/sync\/commands\/([^/]+)\/ack$/);if(ack&&m==='POST'){const b=await body(request);if(!['Applied','Failed','Delivered'].includes(b.status))fail(400,'Invalid result');await db.run("UPDATE site_commands SET status=?,result=? WHERE id=? AND status IN ('Pending','Delivered')",b.status,JSON.stringify(b.result||{}),ack[1]);return json({ok:true})}
 if(p==='/api/sync/customers'&&m==='GET')return json({customers:await db.all("SELECT id,name,phone,'TB-' || printf('%06d',seq) member_code,active FROM site_customers ORDER BY seq")});
 if(!p.startsWith('/api/remote/'))return null;
 if(m!=='GET'&&request.headers.get('origin')!==url.origin)fail(403,'Same-origin request required');
 if(p==='/api/remote/login'&&m==='POST'){const b=await body(request),window=Math.floor(Date.now()/60000),bucket=hash('staff:'+request.headers.get('cf-connecting-ip')+':'+window),rate=await db.one('INSERT INTO site_rate_limits(bucket,count,expires_at) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count',bucket,(window+2)*60000);if(rate.count>8)fail(429,'Try again later');const user=await db.one('SELECT * FROM site_staff WHERE username=? AND active=1',String(b.username||''));if(!user||!passwordVerify(b.password,user.password_hash))fail(401,'Invalid credentials or remote access disabled');const token=randomBytes(32).toString('hex');await db.run('INSERT INTO site_staff_sessions(token_hash,staff_id,revision,expires_at) VALUES(?,?,?,?)',hash(token),user.id,user.revision,Date.now()+12*3600000);const response=json({user:{id:user.id,role:user.role,username:user.username}});response.headers.set('set-cookie',cookie(token));return response}
 const token=getToken(request),user=token?await db.one('SELECT u.id,u.role,u.username,u.permissions FROM site_staff_sessions s JOIN site_staff u ON u.id=s.staff_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1 AND u.revision=s.revision',hash(token),Date.now()):null;
 if(!user)fail(401,'Remote sign in required');
 await db.run('UPDATE site_staff_sessions SET last_used_at=CURRENT_TIMESTAMP WHERE token_hash=?',hash(token));
 if(p==='/api/remote/logout'&&m==='POST'){await db.run('DELETE FROM site_staff_sessions WHERE token_hash=?',hash(token));const r=json({ok:true});r.headers.set('set-cookie',cookie('',0));return r}
 if(p==='/api/remote/bootstrap'&&m==='GET')return json({user,resources:JSON.parse(await state(db,'admin_resources')||'{}'),catalog:JSON.parse(await state(db,'catalog')||'{}'),operations,commands:await db.all('SELECT id,operation,status,result,created_at FROM site_commands ORDER BY created_at DESC LIMIT 100')});
 if(p==='/api/remote/commands'&&m==='POST'){const b=await body(request);if(b.version!==1||!operations.includes(b.operation)||!b.payload||typeof b.payload!=='object'||!b.expectedRevision)fail(400,'Invalid versioned command');const cap=({'menu.save':'menu.write','menu.price':'menu.write','category.save':'menu.write','modifier.save':'menu.write','public_settings.save':'settings.manage','loyalty.settings':'loyalty.adjust','loyalty.reward':'loyalty.adjust'})[b.operation];if(!JSON.parse(user.permissions).includes(cap))fail(403,'Permission required: '+cap);const id=crypto.randomUUID();await db.batch([['INSERT INTO site_commands(id,installation_id,version,operation,payload,created_by,expected_revision) VALUES(?,?,?,?,?,?,?)',id,env.INSTALLATION_ID||'',1,b.operation,JSON.stringify(b.payload),user.id,b.expectedRevision],['INSERT INTO site_admin_audit(id,actor,action,entity_id) VALUES(?,?,?,?)',crypto.randomUUID(),user.id,'command.create',id]]);return json({id,status:'Pending'},201)}
 if(p==='/api/remote/customers'&&m==='GET'){if(!JSON.parse(user.permissions).includes('customers.pii'))fail(403,'Customer permission required');return json({customers:await db.all("SELECT id,name,phone,active,'TB-' || printf('%06d',seq) member_code FROM site_customers ORDER BY seq DESC LIMIT 200")});}
 if(p==='/api/remote/customers'&&m==='POST'){const b=await body(request);if(user.role!=='owner')fail(403,'Owner required');const c=await db.one('SELECT id FROM site_customers WHERE id=?',b.id);if(!c)fail(404,'Customer not found');if(b.action==='recovery'){const value=randomBytes(32).toString('hex');await db.batch([['INSERT INTO site_recovery VALUES(?,?,?,NULL)',hash(value),c.id,Date.now()+900000],['INSERT INTO site_admin_audit VALUES(?,?,?,?,CURRENT_TIMESTAMP)',crypto.randomUUID(),user.id,'customer.recovery',c.id]]);return json({recoveryToken:value,expiresIn:900,instructions:'Deliver privately only after verifying the customer identity.'})}if(b.action!=='activation'||typeof b.active!=='boolean')fail(400,'Invalid customer action');await db.batch([['UPDATE site_customers SET active=?,session_version=session_version+1 WHERE id=?',b.active?1:0,c.id],['INSERT INTO site_admin_audit VALUES(?,?,?,?,CURRENT_TIMESTAMP)',crypto.randomUUID(),user.id,'customer.activation',c.id]]);return json({ok:true})}
 fail(404,'Not found');
}
