const {one,all,run,transaction}=require('./db');
const p=require('./permissions'),costing=require('./costing'),customers=require('./customers');
const {number,required}=require('./validation');
const admin=require('./admin');
function handle(req,res,url,user,b,json){const method=req.method,path=url.pathname,done=data=>{json(res,200,data);return true};
 const userEdit=path.match(/^\/api\/admin\/users\/(\d+)$/);if(userEdit&&method==='PATCH'){transaction(()=>{const id=Number(userEdit[1]),old=one('SELECT id,username,role,active FROM users WHERE id=?',id);if(!old)throw new Error('User not found');if(old.role==='owner'&&b.active===false&&one("SELECT COUNT(*) count FROM users WHERE role='owner' AND active=1").count<=1)throw new Error('Keep at least one active owner');if(b.password){require('./auth').validateCredentials(old.username,String(b.password));require('./auth').revoke(id);run('UPDATE users SET password_hash=?,password_changed_at=CURRENT_TIMESTAMP WHERE id=?',require('./auth').hashPassword(String(b.password)),id)}if(b.remoteAccessEnabled!==undefined){if(!['owner','manager'].includes(old.role))throw Error('Remote access is limited to owner and manager');if(b.remoteAccessEnabled&&(!b.password||String(b.password).length<12))throw Error('Set a password of at least 12 characters to enable remote access');run('UPDATE users SET remote_access_enabled=? WHERE id=?',b.remoteAccessEnabled?1:0,id);require('./auth').revoke(id)}if(b.active!==undefined)run('UPDATE users SET active=? WHERE id=?',b.active?1:0,id);p.audit(user,'user.update','users',id,old,{active:b.active,passwordChanged:!!b.password})});return done({ok:true})}
 if(path==='/api/admin/stations'&&method==='POST'){transaction(()=>{const code=required(b.code);if(!/^[a-z][a-z0-9_]{1,30}$/.test(code))throw new Error('Invalid station code');run('INSERT INTO preparation_stations(code,name_ar,name_en) VALUES(?,?,?)',code,required(b.nameAr),b.nameEn||null);run('INSERT INTO printer_settings(code,name,station_code) VALUES(?,?,?)',code,b.nameEn||b.nameAr,code);p.audit(user,'station.create','preparation_stations',code,null,b)});return done({ok:true})}
 if(path==='/api/menu/costing')return done({modifierTemplates:all('SELECT * FROM modifier_templates'),rows:costing.products(),ingredients:costing.ingredients(),method:costing.method(),targetFoodCost:Number(one("SELECT value FROM settings WHERE key='target_food_cost_percent'").value)});
 if(path==='/api/menu/item'&&method==='DELETE'){const id=Number(url.searchParams.get('id'));const reason=required(url.searchParams.get('reason'),'Delete reason');transaction(()=>{const before=one('SELECT * FROM products WHERE id=?',id);if(!before)throw new Error('Menu item not found');run('UPDATE products SET active=0,in_stock=0,available_online=0 WHERE id=?',id);p.audit(user,'menu.delete','products',id,before,{active:0,inStock:0,availableOnline:0},reason)});return done({ok:true,id})}
 if(path==='/api/menu/item'&&method==='POST'){let id;transaction(()=>{let before=null;if(b.id){id=Number(b.id);before=one('SELECT * FROM products WHERE id=?',id);if(!before)throw new Error('Menu item not found');required(b.reason,'Change reason');run('UPDATE products SET category_id=?,station_id=?,name_ar=?,name_en=?,price=?,active=?,in_stock=?,available_online=?,image_url=?,description_ar=?,description_en=? WHERE id=?',Number(b.categoryId),Number(b.stationId)||null,required(b.nameAr),b.nameEn||null,b.price===''||b.price==null?0:number(b.price,'Price',{zero:true}),b.active?1:0,b.inStock?1:0,b.availableOnline?1:0,b.imageUrl||null,b.descriptionAr||null,b.descriptionEn||null,id)}else{id=admin.addProduct(b);run('UPDATE products SET active=?,in_stock=?,available_online=?,image_url=?,description_ar=?,description_en=? WHERE id=?',b.active?1:0,b.inStock?1:0,b.availableOnline?1:0,b.imageUrl||null,b.descriptionAr||null,b.descriptionEn||null,id)}run('UPDATE products SET price_known=? WHERE id=?',b.price!==''&&b.price!=null&&Number(b.price)>0?1:0,id);if(Array.isArray(b.lines)&&!b.lines.length){run('DELETE FROM recipe_lines WHERE recipe_id IN (SELECT id FROM recipes WHERE product_id=?)',id)}else if(b.lines)admin.setRecipe({productId:id,lines:b.lines.map(l=>{const ing=one('SELECT * FROM ingredients WHERE id=?',Number(l.ingredientId));if(!ing)throw new Error('Ingredient not found');let factor=1;if(l.unit==='kg'&&ing.base_unit==='g'||l.unit==='L'&&ing.base_unit==='ml')factor=1000;else if(l.unit&&l.unit!==ing.base_unit&&!(l.unit==='slice'&&ing.base_unit==='pcs'))throw new Error('Incompatible recipe unit');return {...l,ingredientId:ing.id,quantityBase:number(l.quantity)*factor}})});p.audit(user,'menu.save','products',id,before,b,b.reason||null)});return done({id})}
 if(path==='/api/menu/history')return done({rows:all("SELECT a.*,u.username FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE a.entity_type IN ('product','products') AND a.entity_id=? ORDER BY a.id DESC LIMIT 100",url.searchParams.get('id'))});
 if(path==='/api/customers')return done({rows:customers.list(url.searchParams.get('q')||'').map(c=>require('./response-views').customer(user,c))});
 if(path==='/api/customers/lookup'){const row=one('SELECT id FROM customers WHERE phone=?',customers.phone(url.searchParams.get('phone')));return done({customer:row?require('./response-views').customer(user,customers.profile(row.id)):null})}
 if(path.startsWith('/api/customers/'))return done({customer:require('./response-views').customer(user,customers.profile(path.split('/').pop()))});
 if(path==='/api/inventory/receive-simple'&&method==='POST'){let quantityBase;transaction(()=>{const ingredient=one('SELECT * FROM ingredients WHERE id=? AND active=1',Number(b.ingredientId));if(!ingredient)throw new Error('Ingredient not found');let conversion=1;if(b.unit==='kg'&&ingredient.base_unit==='g'||b.unit==='L'&&ingredient.base_unit==='ml')conversion=1000;else if(b.unit==='carton'&&ingredient.base_unit==='pcs'){conversion=number(b.conversionToBase,'Pieces per carton');if(!Number.isInteger(conversion))throw Error('Pieces per carton must be an integer')}else if(b.unit!==ingredient.base_unit)throw new Error('Unit does not match ingredient');const brand=String(b.brand||'').trim();let variant=one('SELECT * FROM ingredient_variants WHERE ingredient_id=? AND COALESCE(brand,\'\')=? AND purchase_unit=? AND conversion_to_base=? AND active=1',ingredient.id,brand,b.unit,conversion);if(!variant){const id=admin.addVariant({ingredientId:ingredient.id,nameAr:brand||ingredient.name_ar,nameEn:brand||ingredient.name_en,brand:brand||null,purchaseUnit:b.unit,conversionToBase:conversion});variant={id}}const item={variantId:variant.id,locationId:Number(b.locationId),quantityPurchase:number(b.quantityPurchase),unitPricePurchase:number(b.unitPricePurchase,'Price',{zero:true}),batchNumber:b.batchNumber,expiresOn:b.expiresOn};if(b.supplierId)admin.createPurchase({supplierId:Number(b.supplierId),invoiceNo:b.invoiceNo,items:[item],userId:user.id});else require('./inventory').receiveStock({...item,userId:user.id});quantityBase=item.quantityPurchase*conversion;p.audit(user,'stock.receive','ingredients',ingredient.id,null,{...b,quantityBase})});return done({quantityBase})}
 if(path==='/api/settings/order-types'){if(method==='GET')return done({rows:all('SELECT * FROM order_types')});required(b.code,'Code');if(!/^[a-z][a-z0-9_]{1,30}$/.test(b.code))throw new Error('Use a short lowercase code');run('INSERT INTO order_types(code,name_ar,name_en,requires_delivery,active,online) VALUES(?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET name_ar=excluded.name_ar,name_en=excluded.name_en,requires_delivery=excluded.requires_delivery,active=excluded.active,online=excluded.online',b.code,required(b.nameAr),b.nameEn||null,b.requiresDelivery?1:0,b.active===false?0:1,b.online?1:0);p.audit(user,'order_type.save','order_types',b.code,null,b);return done({ok:true})}
 return false;
}
module.exports={handle};
