const {one,all}=require('./db');
const {money}=require('./validation');
function method(){return one("SELECT value FROM settings WHERE key='costing_method'")?.value||'average'}
function ingredientCost(id,specificVariantId=null){const where=`v.ingredient_id=? ${specificVariantId?'AND v.id=?':''} AND m.quantity_base>0 AND m.unit_cost_base IS NOT NULL AND m.movement_type IN ('purchase','production_output','opening')`;const params=specificVariantId?[id,specificVariantId]:[id];const result=method()==='latest'?one(`SELECT m.unit_cost_base cost FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id WHERE ${where} ORDER BY m.created_at DESC,m.id DESC LIMIT 1`,...params):one(`SELECT SUM(m.quantity_base*m.unit_cost_base)/SUM(m.quantity_base) cost FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id WHERE ${where}`,...params);return result?.cost??null}
function ingredients(){return all('SELECT * FROM ingredients WHERE active=1').map(i=>({...i,unit_cost:ingredientCost(i.id)}))}
function productCost(product){const target=Number(one("SELECT value FROM settings WHERE key='target_food_cost_percent'")?.value||30),recipe=one('SELECT * FROM recipes WHERE product_id=?',product.id);
 const lines=recipe&&product.recipe_verified?all('SELECT r.*,i.name_ar,i.name_en,i.base_unit,i.cost_group FROM recipe_lines r JOIN ingredients i ON i.id=r.ingredient_id WHERE recipe_id=?',recipe.id):[];let known=lines.length>0&&recipe.yield_qty>0,total=0,packaging=0,ingredients=0;
 for(const l of lines){l.unit_cost=ingredientCost(l.ingredient_id,l.specific_variant_id);l.cost=l.unit_cost==null?null:l.unit_cost*l.quantity_base/recipe.yield_qty;if(l.cost==null)known=false;total+=l.cost||0;if(l.cost_group==='packaging')packaging+=l.cost||0;else ingredients+=l.cost||0}
 const priceKnown=!!product.price_known&&product.price>0,cost=known?money(total):null,margin=known&&priceKnown?money(product.price-total):null;
 return {...product,price:priceKnown?product.price:null,lines,recipe_complete:lines.length>0,cost,margin,known_cost:money(total),ingredient_cost:known?money(ingredients):null,packaging_cost:known?money(packaging):null,missing_costs:lines.filter(l=>l.cost==null).map(l=>({id:l.ingredient_id,name_ar:l.name_ar,name_en:l.name_en})),cost_status:!lines.length?'recipe_missing':!known?'cost_incomplete':!priceKnown?'price_missing':'complete',suggested_price:known?money(total/(target/100)):null,food_cost_percent:known&&priceKnown?money(total/product.price*100):null,margin_percent:known&&priceKnown?money((product.price-total)/product.price*100):null,costing_method:method()};
}
function products(){return all('SELECT p.*,c.name_ar category_ar,c.name_en category_en,s.name_ar station_ar,s.name_en station_en FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN preparation_stations s ON s.id=p.station_id WHERE p.active=1 ORDER BY p.id').map(productCost)}

function period(from,to){const sales=all("SELECT * FROM orders WHERE date(created_at,'localtime') BETWEEN ? AND ? AND status='completed'",from,to);let foodCost=0,known=true;for(const o of sales){const movements=all("SELECT quantity_base,unit_cost_base,variant_id FROM stock_movements WHERE reference_type='order' AND reference_id=? AND movement_type='sale'",o.id);if(!movements.length)known=false;for(const m of movements){const ingredient=one('SELECT ingredient_id FROM ingredient_variants WHERE id=?',m.variant_id);const c=ingredientCost(ingredient.ingredient_id,m.variant_id);if(c==null)known=false;foodCost+=-m.quantity_base*(c||0)}}const revenue=money(sales.reduce((s,o)=>s+o.total,0)),expenses=one("SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE COALESCE(expense_date,date(created_at,'localtime')) BETWEEN ? AND ?",from,to).total;return {revenue,estimatedFoodCost:known?money(foodCost):null,estimatedGrossProfit:known?money(revenue-foodCost):null,operatingExpenses:expenses,estimatedOperatingProfit:known?money(revenue-foodCost-expenses):null,costingMethod:method(),estimated:true}}
module.exports={productCost,method,ingredientCost,ingredients,products,period};
