const crypto=require('crypto');
const {one,all,run}=require('./db');
function phone(value){return value?require('../public/shared/validation').phone(value):''}
function save({customerName,customerPhone,deliveryDetails={}}){const mobile=phone(customerPhone);if(!mobile)return null;if(!/^\+?\d{7,16}$/.test(mobile))throw new Error('Enter a valid phone number');let row=one('SELECT * FROM customers WHERE phone=?',mobile);if(row?.account_linked)return null;if(!row){const id=crypto.randomUUID();run('INSERT INTO customers(id,name,phone,alternative_phone) VALUES(?,?,?,?)',id,customerName||null,mobile,deliveryDetails.alternativePhone||null);row={id}}else run('UPDATE customers SET name=COALESCE(?,name),alternative_phone=COALESCE(?,alternative_phone) WHERE id=?',customerName||null,deliveryDetails.alternativePhone||null,row.id);if(Object.values(deliveryDetails).some(Boolean)){const details=JSON.stringify(deliveryDetails),existing=one('SELECT id FROM customer_addresses WHERE customer_id=? AND details=?',row.id,details);if(!existing)run('INSERT INTO customer_addresses(id,customer_id,details) VALUES(?,?,?)',crypto.randomUUID(),row.id,details)}return row.id}
function list(q=''){return all(`SELECT c.*,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) order_count,(SELECT COALESCE(SUM(total),0) FROM orders o WHERE o.customer_id=c.id AND o.status='completed') total_spending,(SELECT MAX(created_at) FROM orders o WHERE o.customer_id=c.id) last_order FROM customers c WHERE c.name LIKE ? OR c.phone LIKE ? OR c.member_code LIKE ? OR c.id=? ORDER BY last_order DESC LIMIT 200`,'%'+q+'%','%'+String(q).replace(/[ ()-]/g,'')+'%','%'+q+'%',q)}
function profile(id){const row=one('SELECT * FROM customers WHERE id=?',id);if(!row)return null;return {...row,addresses:all('SELECT * FROM customer_addresses WHERE customer_id=? ORDER BY updated_at DESC',id).map(a=>({...a,details:JSON.parse(a.details)})),orders:all('SELECT id,sequential_no,total,status,created_at FROM orders WHERE customer_id=? ORDER BY created_at DESC',id)}}
function attach(id,{customerName,customerPhone,memberCode,fromCloud=false}){
 let row=one('SELECT * FROM customers WHERE id=?',id)||one('SELECT c.* FROM customers c JOIN customer_links l ON l.customer_id=c.id WHERE l.account_id=?',id);
 if(!fromCloud){if(!row)throw Error('Customer not found');return row.id}
 if(!require('../public/shared/validation').uuid(id)||!/^TB-\d{6,}$/.test(memberCode||''))throw Error('Invalid customer identity');
 const mobile=phone(customerPhone);
 if(!row){const matches=all('SELECT * FROM customers').filter(c=>phone(c.phone)===mobile);if(matches.length)throw Error('Customer identity needs review: link the existing phone record before import');run('INSERT INTO customers(id,name,phone,member_code,account_linked) VALUES(?,?,?,?,1)',id,customerName,mobile,memberCode);row={id}}
 const linked=one('SELECT * FROM customer_links WHERE customer_id=?',row.id);if(linked&&linked.account_id!==id)throw Error('Customer is linked to another account');
 run('INSERT OR IGNORE INTO customer_links(account_id,customer_id,member_code) VALUES(?,?,?)',id,row.id,memberCode);
 run('UPDATE customers SET name=?,phone=?,member_code=?,account_linked=1 WHERE id=?',customerName,mobile,memberCode,row.id);return row.id;
}
function link(localId,account){const row=one('SELECT * FROM customers WHERE id=?',localId);if(!row||row.account_linked)throw Error('Choose an unlinked customer');if(phone(row.phone)!==phone(account.phone))throw Error('Phone numbers do not match');run('INSERT INTO customer_links(account_id,customer_id,member_code) VALUES(?,?,?)',account.id,localId,account.member_code);run('UPDATE customers SET account_linked=1,member_code=? WHERE id=?',account.member_code,localId);for(const o of all('SELECT id FROM orders WHERE customer_id=?',localId))queueOrder(require('./orders').getOrder(o.id));}
function queueOrder(o){if(!o.customer_id)return;const linked=one('SELECT account_id FROM customer_links WHERE customer_id=?',o.customer_id);if(!linked)return;const payload={id:o.id,customer_id:linked.account_id,sequential_no:o.sequential_no,total:o.total,status:o.status==='refunded'?'cancelled':o.fulfillment_status,payment_status:o.payment_status,date:o.created_at,items:o.items.map(i=>({productId:i.product_id,qty:i.quantity,notes:i.notes,modifiers:i.modifiers.map(m=>m.id),snapshot:{name_ar:i.product_name_ar,name_en:i.product_name_en}}))};run("INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('customer_order',?,'upsert',?,?)",o.id,JSON.stringify(payload),crypto.randomUUID())}
module.exports={save,list,profile,phone,attach,link,queueOrder};
