const crypto=require('crypto');
const {one,all,run}=require('./db');
function phone(value){return value?require('../public/shared/validation').phone(value):''}
function save({customerName,customerPhone,deliveryDetails={}}){const mobile=phone(customerPhone);if(!mobile)return null;if(!/^\+?\d{7,16}$/.test(mobile))throw new Error('Enter a valid phone number');const found=require('./customer-management').matches(mobile);if(found.length>1)throw Error('Duplicate customers need review before continuing');let row=found[0];if(row?.account_linked)return null;if(!row){const id=crypto.randomUUID();run('INSERT INTO customers(id,name,phone,alternative_phone) VALUES(?,?,?,?)',id,customerName||null,mobile,deliveryDetails.alternativePhone||null);row={id}}else run('UPDATE customers SET alternative_phone=COALESCE(?,alternative_phone) WHERE id=?',deliveryDetails.alternativePhone||null,row.id);if(Object.values(deliveryDetails).some(Boolean)){const details=JSON.stringify(deliveryDetails),existing=one('SELECT id FROM customer_addresses WHERE customer_id=? AND details=?',row.id,details);if(!existing)run('INSERT INTO customer_addresses(id,customer_id,details) VALUES(?,?,?)',crypto.randomUUID(),row.id,details)}return row.id}
function list(q=''){const match=require('./customer-management'),query=String(q).trim().toLowerCase(),normalized=match.canonical(q);return all('SELECT * FROM customers WHERE merged_into IS NULL').filter(c=>!q||[c.name,c.phone,c.member_code,c.id].some(x=>String(x||'').toLowerCase().includes(query))||(normalized&&match.canonical(c.phone)===normalized)).map(c=>{const values=match.ids(c.id),marks=values.map(()=>'?').join(',');return {...c,...one(`SELECT COUNT(*) order_count,COALESCE(SUM(CASE WHEN status='completed' THEN total ELSE 0 END),0) total_spending,MAX(created_at) last_order FROM orders WHERE customer_id IN (${marks})`,...values),duplicate_phone:match.duplicates(c).length,duplicate_name:all('SELECT id,name FROM customers WHERE merged_into IS NULL AND id!=?',c.id).filter(x=>x.name?.trim().toLowerCase()===c.name?.trim().toLowerCase()).length}}).sort((a,b)=>String(b.last_order||'').localeCompare(String(a.last_order||''))).slice(0,200)}
function profile(id){const match=require('./customer-management'),row=match.primary(id);if(!row)return null;const values=match.ids(row.id),marks=values.map(()=>'?').join(',');return {...row,duplicates:match.duplicates(row),mergedCount:values.length-1,addresses:all(`SELECT * FROM customer_addresses WHERE customer_id IN (${marks}) ORDER BY updated_at DESC`,...values).map(a=>({...a,details:JSON.parse(a.details)})),orders:all(`SELECT id,sequential_no,total,status,created_at FROM orders WHERE customer_id IN (${marks}) ORDER BY created_at DESC`,...values)}}
function attach(id,{customerName,customerPhone,memberCode,fromCloud=false}){
 let row=one('SELECT * FROM customers WHERE id=?',id)||one('SELECT c.* FROM customers c JOIN customer_links l ON l.customer_id=c.id WHERE l.account_id=?',id);
 if(!fromCloud){if(!row)throw Error('Customer not found');return row.id}
 if(!require('../public/shared/validation').uuid(id)||!/^TB-\d{6,}$/.test(memberCode||''))throw Error('Invalid customer identity');
 const mobile=phone(customerPhone);
 if(!row){const matches=require('./customer-management').matches(mobile);if(matches.length)throw Error('Customer identity needs review: link the existing phone record before import');run('INSERT INTO customers(id,name,phone,member_code,account_linked) VALUES(?,?,?,?,1)',id,customerName,mobile,memberCode);row={id}}
 const linked=one('SELECT * FROM customer_links WHERE customer_id=?',row.id);if(linked&&linked.account_id!==id)throw Error('Customer is linked to another account');
 run('INSERT OR IGNORE INTO customer_links(account_id,customer_id,member_code) VALUES(?,?,?)',id,row.id,memberCode);
 run('UPDATE customers SET name=?,phone=?,member_code=?,account_linked=1 WHERE id=?',customerName,mobile,memberCode,row.id);return row.id;
}
function link(localId,account){const row=one('SELECT * FROM customers WHERE id=?',localId);if(!row||row.account_linked)throw Error('Choose an unlinked customer');if(phone(row.phone)!==phone(account.phone))throw Error('Phone numbers do not match');run('INSERT INTO customer_links(account_id,customer_id,member_code) VALUES(?,?,?)',account.id,localId,account.member_code);run('UPDATE customers SET account_linked=1,member_code=? WHERE id=?',account.member_code,localId);for(const id of require('./customer-management').ids(localId))run("UPDATE sync_queue SET next_retry_at=0 WHERE entity_type='loyalty' AND entity_id=? AND status IN ('pending','retrying')",id);for(const o of profile(localId).orders)queueOrder(require('./orders').getOrder(o.id));}
function queueOrder(o){if(!o.customer_id)return;const linked=one('SELECT account_id FROM customer_links WHERE customer_id=?',require('./customer-management').primary(o.customer_id)?.id);if(!linked)return;const payload={id:o.id,customer_id:linked.account_id,sequential_no:o.sequential_no,total:o.total,status:o.status==='refunded'?'cancelled':o.fulfillment_status,payment_status:o.payment_status,date:o.created_at,items:o.items.map(i=>({productId:i.product_id,qty:i.quantity,notes:i.notes,modifiers:i.modifiers.map(m=>m.id),snapshot:{name_ar:i.product_name_ar,name_en:i.product_name_en}}))};run("INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('customer_order',?,'upsert',?,?)",o.id,JSON.stringify(payload),crypto.randomUUID())}
module.exports={save,list,profile,phone,attach,link,queueOrder};
