const {one,all,run,transaction}=require('./db'),orders=require('./orders'),permissions=require('./permissions');
const waiting=['awaiting_restaurant_confirmation','needs_review'];
function failure(message){if(/stock|variant|ingredient/i.test(message))return 'stock';if(/price|total|pricing/i.test(message))return 'price';if(/recipe/i.test(message))return 'recipe';if(/modifier/i.test(message))return 'modifier';if(/product|sellable/i.test(message))return 'product';if(/customer|identity|phone|account|member/i.test(message))return 'customer';if(/reward|redemption|points|loyalty/i.test(message))return 'loyalty';if(/delivery|address|order type/i.test(message))return 'delivery';if(/fetch|network|offline|timeout|connection/i.test(message))return 'connection';return 'database'}
function get(id){const row=one('SELECT * FROM online_order_inbox WHERE cloud_id=?',id);if(!row){const e=Error('Online order not found');e.status=404;throw e}return row}
function review(id,error){run("UPDATE online_order_inbox SET status='needs_review',reason_code=?,validation_details=?,technical_error=?,decision_pending=1,next_retry_at=0,updated_at=CURRENT_TIMESTAMP WHERE cloud_id=? AND status IN ('awaiting_restaurant_confirmation','needs_review')",failure(error.message),error.details?JSON.stringify(error.details):null,String(error.message).slice(0,1000),id)}
function ingest(rows){for(const row of rows)transaction(()=>{
 const link=one('SELECT local_order_id FROM cloud_imports WHERE cloud_order_id=?',row.id);
 const inserted=run('INSERT OR IGNORE INTO online_order_inbox(cloud_id,cloud_no,payload,received_at,status,local_order_id,decision_pending) VALUES(?,?,?,?,?,?,?)',row.id,row.sequential_no,JSON.stringify(row.payload),row.created_at||new Date().toISOString(),link?'confirmed':'awaiting_restaurant_confirmation',link?.local_order_id||null,link?1:0);
 if(inserted.changes&&row.status==='needs_review'&&!link)review(row.id,Error(row.error||'Review required'));
});}
function create(row,user){const p=JSON.parse(row.payload),normalized=orders.normalize(p.items);
 for(let i=0;i<normalized.length;i++)if(Math.abs(normalized[i].price-Number(p.items[i].price))>0.001)throw Error('Menu price changed since customer checkout');
 const created=orders.createOrder({source:'web',requestId:row.cloud_id,userId:user?.id||null,customerId:p.customerId,memberCode:p.memberCode,discount:p.discount||0,reward:p.reward||null,customerName:p.customerName||null,customerPhone:p.customerPhone||null,orderType:p.orderType||'pickup',items:p.items,notes:p.notes||null,deferredPayment:true,deliveryAddress:p.deliveryAddress||null,deliveryDetails:p.deliveryDetails||{},deliveryFee:p.deliveryFee||0});
 if(Math.abs(created.total-Number(p.total))>0.001)throw Error('Menu price changed since customer checkout');
 return created;
}
function validate(id){const row=get(id);if(!waiting.includes(row.status))return row;const rollback={};try{transaction(()=>{create(row,null);throw rollback})}catch(e){if(e!==rollback){review(id,e);return get(id)}}run("UPDATE online_order_inbox SET status='awaiting_restaurant_confirmation',reason_code=NULL,validation_details=NULL,technical_error=NULL,decision_pending=1,next_retry_at=0,updated_at=CURRENT_TIMESTAMP WHERE cloud_id=?",id);return get(id)}
function snapshot(user,row){const p=JSON.parse(row.payload),kitchen=user.role==='kitchen',pii=permissions.can(user,'customers.pii');const out={id:row.cloud_id,sequential_no:row.cloud_no,source:'web',status:row.status,created_at:row.received_at,local_order_id:row.local_order_id,reason:row.reason_code,shortage:row.validation_details?JSON.parse(row.validation_details):null,decision_pending:!!row.decision_pending,order_type:p.orderType,notes:p.notes,items:(p.items||[]).map(i=>{const product=one('SELECT name_ar,name_en FROM products WHERE id=?',i.productId);return {quantity:i.qty,product_name_ar:i.product_name_ar||product?.name_ar||'صنف غير متاح',product_name_en:i.product_name_en||product?.name_en||'Unavailable item',notes:i.notes,modifiers:(i.modifiers||[]).map(id=>one('SELECT id,name_ar,name_en FROM modifiers WHERE id=?',id)).filter(Boolean),...(!kitchen?{unit_price:i.price}: {})}})};
 if(!kitchen)Object.assign(out,{total:p.total,subtotal:p.pricing?.subtotal,delivery_fee:p.deliveryFee,discount:p.discount,reward:p.reward?{name_ar:p.reward.name_ar,name_en:p.reward.name_en}:null,rejection_reason:row.rejection_reason});
 if(pii)Object.assign(out,{customer_name:p.customerName,customer_phone:p.customerPhone,delivery_address:p.deliveryAddress,customer_id:p.customerId,member_code:p.memberCode});
 if(permissions.can(user,'sync.manage'))Object.assign(out,{technical_error:row.technical_error,delivery_error:row.last_delivery_error});return out;
}
function list(user){return all("SELECT * FROM online_order_inbox WHERE status IN ('awaiting_restaurant_confirmation','needs_review') OR decision_pending=1 ORDER BY received_at,cloud_no").map(row=>snapshot(user,row))}
function counts(){return {incoming:one("SELECT COUNT(*) n FROM online_order_inbox WHERE status='awaiting_restaurant_confirmation'").n,review:one("SELECT COUNT(*) n FROM online_order_inbox WHERE status='needs_review'").n,decisionsPending:one('SELECT COUNT(*) n FROM online_order_inbox WHERE decision_pending=1').n}}
async function deliver(cloud){for(const row of all('SELECT * FROM online_order_inbox WHERE decision_pending=1 AND next_retry_at<=? ORDER BY received_at LIMIT 100',Date.now())){try{
 const endpoint=row.status==='confirmed'?'ack':row.status==='rejected'?'reject':'review';const order=row.local_order_id?orders.getOrder(row.local_order_id):null;
 await cloud('/api/sync/orders/'+row.cloud_id+'/'+endpoint,{method:'POST',body:JSON.stringify({localOrderId:row.local_order_id,paymentStatus:order?.payment_status||'due',reason:row.rejection_reason,code:row.reason_code,status:row.status,actor:row.actor_id})});
 run('UPDATE online_order_inbox SET decision_pending=0,last_delivery_error=NULL,delivery_attempts=0 WHERE cloud_id=? AND status=? AND updated_at=?',row.cloud_id,row.status,row.updated_at);
 }catch(e){run('UPDATE online_order_inbox SET delivery_attempts=delivery_attempts+1,last_delivery_error=?,next_retry_at=? WHERE cloud_id=?',String(e.message).slice(0,500),Date.now()+require('./sync-policy').backoff(row.delivery_attempts+1),row.cloud_id)}}}
async function accept(id,user){let row=get(id);if(row.status==='confirmed')return {alreadyAccepted:true,order:orders.getOrder(row.local_order_id)};if(!waiting.includes(row.status)){const e=Error('Order is no longer awaiting confirmation');e.status=409;throw e}
 const cloud=require('./sync-service').cloud;
 try{const remote=await cloud('/api/sync/orders/'+id);row=get(id);if(row.status==='confirmed')return {alreadyAccepted:true,order:orders.getOrder(row.local_order_id),ackPending:!!row.decision_pending};if(!['pending',...waiting].includes(remote.order.status))throw Error('Cloud order is no longer awaiting confirmation');if(remote.order.rewardValid===false)throw Error('Loyalty reward reservation requires review');
 const result=transaction(()=>{row=get(id);if(row.status==='confirmed')return {alreadyAccepted:true,order:orders.getOrder(row.local_order_id)};if(!waiting.includes(row.status))throw Error('Order is no longer awaiting confirmation');
 const existing=one('SELECT local_order_id FROM cloud_imports WHERE cloud_order_id=?',id);const order=existing?orders.getOrder(existing.local_order_id):create(row,user);if(!existing)run('INSERT INTO cloud_imports(cloud_order_id,local_order_id) VALUES(?,?)',id,order.id);
 run("UPDATE online_order_inbox SET status='confirmed',local_order_id=?,actor_id=?,decided_at=CURRENT_TIMESTAMP,reason_code=NULL,validation_details=NULL,technical_error=NULL,decision_pending=1,next_retry_at=0,updated_at=CURRENT_TIMESTAMP WHERE cloud_id=?",order.id,user.id,id);permissions.audit(user,'online.accept','online_order',id,{status:row.status},{status:'confirmed',localOrderId:order.id});return {order};});
 await deliver(cloud);return {...result,ackPending:!!get(id).decision_pending};
 }catch(e){review(id,e);e.status=e.status||409;e.message='Order needs review: '+failure(e.message);throw e}
}
async function reject(id,reason,user){reason=String(reason||'').trim();if(!reason||reason.length>500)throw Error('A rejection reason (1–500 characters) is required');transaction(()=>{const row=get(id);if(row.status==='rejected')return;if(!waiting.includes(row.status)){const e=Error('Accepted orders must use the audited refund/cancellation workflow');e.status=409;throw e}run("UPDATE online_order_inbox SET status='rejected',rejection_reason=?,actor_id=?,decided_at=CURRENT_TIMESTAMP,decision_pending=1,next_retry_at=0,updated_at=CURRENT_TIMESTAMP WHERE cloud_id=?",reason,user.id,id);permissions.audit(user,'online.reject','online_order',id,{status:row.status},{status:'rejected'},reason)});await deliver(require('./sync-service').cloud);return {incoming:snapshot(user,get(id))}}
module.exports={ingest,validate,list,counts,accept,reject,deliver,snapshot,get};
