const crypto=require('crypto');const validation=require('../public/shared/validation');
const {one,all,run,transaction}=require('./db');
const stock=require('./stock-ledger');
const {number,money,required}=require('./validation');
const permissions=require('./permissions');
const pricing=require('../public/shared/pricing');
const customers=require('./customers');
function normalize(items){return validation.items(items).map(item=>{const p=one('SELECT * FROM products WHERE id=? AND active=1 AND in_stock=1',Number(item.productId));if(!p)throw new Error('Product unavailable');if(!p.recipe_verified||!p.price_known||p.price<=0||p.setup_required&&require('./costing').productCost(p).cost==null)throw new Error('Product setup incomplete: recipe, cost and selling price required');const qty=number(item.qty??1),recipe=one('SELECT * FROM recipes WHERE product_id=?',p.id);if(!recipe)throw new Error(`Recipe required: ${p.name_en||p.name_ar}`);const requirements=all('SELECT * FROM recipe_lines WHERE recipe_id=?',recipe.id).map(l=>({...l,quantity_base:l.quantity_base/recipe.yield_qty}));if(!requirements.length)throw new Error('Recipe cannot be empty');const ids=[...new Set((item.modifiers||[]).map(Number))];const mods=ids.map(id=>{const m=one('SELECT * FROM modifiers WHERE id=? AND product_id=? AND active=1',id,p.id);if(!m)throw new Error('Modifier unavailable');for(const l of all('SELECT * FROM modifier_lines WHERE modifier_id=?',id)){let r=requirements.find(r=>r.ingredient_id===l.ingredient_id);if(!r){r={ingredient_id:l.ingredient_id,quantity_base:0};requirements.push(r)}r.quantity_base+=l.quantity_base}return {id:m.id,name_ar:m.name_ar,name_en:m.name_en,price:m.price}});for(const r of requirements){if(r.quantity_base<0)throw new Error('Modifier removes more than recipe contains');if(item.variants?.[r.ingredient_id]){const v=stock.variant(item.variants[r.ingredient_id]);if(v.ingredient_id!==r.ingredient_id||(r.specific_variant_id&&r.specific_variant_id!==v.id))throw new Error('Variant is not approved for this recipe');r.specific_variant_id=v.id}}
 const price=money(p.price+mods.reduce((s,m)=>s+m.price,0));if(price<0)throw new Error('Invalid modified price');return {p,qty,price,line:money(price*qty),mods,requirements,notes:item.notes||null}})}
function createOrder(input){const {source='pos',userId=null,shiftId=null,customerName=null,customerPhone=null,orderType='pickup',items=[],payments=[],notes=null,requestId=null,discount=0,deferredPayment=false,deliveryAddress=null,deliveryDetails={},deliveryFee=0}=input;return transaction(()=>{
 validation.requestId(requestId);const hash=crypto.createHash('sha256').update(validation.canonical({source,userId,customerId:input.customerId||null,items:validation.items(items),payments,discount,customerName,customerPhone,orderType,notes,deferredPayment,deliveryAddress,deliveryDetails,deliveryFee})).digest('hex');
 if(requestId){const existing=one('SELECT * FROM orders WHERE request_id=?',String(requestId));if(existing){if(existing.request_hash!==hash)throw new Error('Request ID already used for another order');return getOrder(existing.id)}}
 const type=one('SELECT * FROM order_types WHERE code=? AND active=1',orderType);if(!type)throw new Error('Invalid order type');if(type.requires_delivery){required(customerName,'Customer name');required(customerPhone,'Mobile');required(deliveryAddress||deliveryDetails.fullAddress||deliveryDetails.street,'Delivery address')}
 const settings=Object.fromEntries(all('SELECT key,value FROM settings').map(r=>[r.key,r.value]));
 const normalized=normalize(items),subtotal=money(normalized.reduce((s,r)=>s+r.line,0)),reduction=money(number(discount,'Discount',{zero:true}));if(reduction>subtotal)throw new Error('Discount exceeds subtotal');const priced=pricing.calculate({subtotal,discount:reduction,deliveryFee:type.requires_delivery?deliveryFee:0,settings});const total=priced.total;
 let pays=[];if(!deferredPayment){pays=payments.map(p=>{const method=one('SELECT * FROM payment_methods WHERE id=? AND active=1',Number(p.methodId));if(!method)throw new Error('Invalid payment method');if(method.requires_reference)required(p.reference,'Payment reference');return {...p,amount:money(number(p.amount,'Payment'))}});if(Math.abs(money(pays.reduce((s,p)=>s+p.amount,0))-total)>0.001)throw new Error(`Payments must equal order total (${total.toFixed(2)})`)}else if(payments.length)throw new Error('Deferred order cannot include collected payments');
 const id=crypto.randomUUID(),seq=Number(one("SELECT value FROM settings WHERE key='next_order_no'")?.value||1001),orderDate=new Intl.DateTimeFormat('en-CA',{timeZone:settings.restaurant_timezone||'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),dailyNo=Number(one('SELECT COALESCE(MAX(daily_no),0)+1 next_no FROM orders WHERE order_date=?',orderDate).next_no);run("UPDATE settings SET value=? WHERE key='next_order_no'",String(seq+1));run(`INSERT INTO orders(id,sequential_no,order_date,daily_no,source,shift_id,user_id,customer_name,customer_phone,order_type,subtotal,discount,total,notes,request_id,request_hash,payment_status,delivery_address) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,seq,orderDate,dailyNo,source,shiftId,userId,customerName,customerPhone,orderType,subtotal,reduction,total,notes,requestId,hash,deferredPayment&&total>0?'due':'paid',deliveryAddress);
 for(const x of normalized){const station=one('SELECT code FROM preparation_stations WHERE id=?',x.p.station_id)?.code||null;run('INSERT INTO order_items(order_id,product_id,product_name_ar,product_name_en,quantity,unit_price,line_total,notes,modifiers,station_code) VALUES(?,?,?,?,?,?,?,?,?,?)',id,x.p.id,x.p.name_ar,x.p.name_en,x.qty,x.price,x.line,x.notes,JSON.stringify(x.mods),station);for(const r of x.requirements)if(r.quantity_base>0)stock.consumeIngredient({ingredientId:r.ingredient_id,specificVariantId:r.specific_variant_id,stationCode:station||'default',quantityBase:r.quantity_base*x.qty,referenceType:'order',referenceId:id,userId,note:`Order #${seq}`})}
 for(const p of pays)run('INSERT INTO payments(order_id,payment_method_id,amount,reference) VALUES(?,?,?,?)',id,Number(p.methodId),p.amount,p.reference||null);
 const customerId=input.customerId?customers.attach(input.customerId,{customerName,customerPhone,memberCode:input.memberCode,fromCloud:source==='web'}):customers.save({customerName,customerPhone,deliveryDetails});run('UPDATE orders SET customer_id=?,delivery_details=?,delivery_fee=?,pricing_snapshot=?,receipt_settings=? WHERE id=?',customerId,JSON.stringify(deliveryDetails),priced.delivery,JSON.stringify({...priced,rules:Object.fromEntries(Object.entries(settings).filter(([k])=>/^(tax|service|packaging|other)_/.test(k)))}),JSON.stringify(Object.fromEntries(Object.entries(settings).filter(([k])=>k.startsWith('receipt_')||k.startsWith('restaurant_')))),id);
 run('UPDATE orders SET loyalty_rules=? WHERE id=?',JSON.stringify(require('./loyalty').settings()),id);
 if(input.reward){run('UPDATE orders SET reward_snapshot=? WHERE id=?',JSON.stringify(input.reward),id);if(source==='pos')run("INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('redemption_commit',?,'upsert',?,?)",id,JSON.stringify({requestId}),crypto.randomUUID())}require('./loyalty').reconcile(getOrder(id));customers.queueOrder(getOrder(id));
 queuePrint(id);permissions.audit({id:userId},'order.create','orders',id,null,{total,source,paymentStatus:deferredPayment&&total>0?'due':'paid'});return getOrder(id);
})}
function queuePrint(id,reprint=false){require('./printing/service').enqueue(getOrder(id),{reprint})}
function getOrder(id){const o=one('SELECT * FROM orders WHERE id=?',id);if(!o)return null;delete o.request_hash;o.delivery_details=JSON.parse(o.delivery_details||'{}');o.pricing=JSON.parse(o.pricing_snapshot||'{}');o.receiptSettings=JSON.parse(o.receipt_settings||'{}');o.cashier=one('SELECT display_name_ar,display_name_en FROM users WHERE id=?',o.user_id)||null;o.orderType=one('SELECT * FROM order_types WHERE code=?',o.order_type)||null;o.items=all('SELECT oi.*,s.name_ar station_name_ar,s.name_en station_name_en FROM order_items oi LEFT JOIN preparation_stations s ON s.code=oi.station_code WHERE order_id=?',id).map(x=>({...x,modifiers:JSON.parse(x.modifiers||'[]')}));o.payments=all('SELECT p.*,m.code,m.name_ar,m.name_en FROM payments p JOIN payment_methods m ON m.id=p.payment_method_id WHERE order_id=?',id);o.refund=one('SELECT * FROM refunds WHERE order_id=?',id)||null;return o}
function listOrders(limit=100,filters={}){const clauses=[],params=[];if(filters.active_kitchen==='1')clauses.push("o.status='completed' AND o.fulfillment_status!='fulfilled'");const fields={status:'o.status',cashier:'o.user_id',shift:'o.shift_id',source:'o.source',fulfillment:'o.fulfillment_status'};for(const [key,col] of Object.entries(fields))if(filters[key]){clauses.push(`${col}=?`);params.push(filters[key])}if(filters.q){clauses.push("(CAST(o.sequential_no AS TEXT) LIKE ? OR o.customer_name LIKE ? OR o.customer_phone LIKE ? OR EXISTS(SELECT 1 FROM order_items i WHERE i.order_id=o.id AND (i.product_name_ar LIKE ? OR i.product_name_en LIKE ?)))");params.push(...Array(5).fill('%'+filters.q+'%'))}for(const [key,op,col] of [['from','>=',"date(o.created_at,'localtime')"],['to','<=',"date(o.created_at,'localtime')"],['min','>=','o.total'],['max','<=','o.total']])if(filters[key]){clauses.push(`${col}${op}?`);params.push(filters[key])}for(const [key,sql] of [['product','SELECT 1 FROM order_items i WHERE i.order_id=o.id AND i.product_id=?'],['category','SELECT 1 FROM order_items i JOIN products p ON p.id=i.product_id WHERE i.order_id=o.id AND p.category_id=?'],['payment','SELECT 1 FROM payments p WHERE p.order_id=o.id AND p.payment_method_id=?']])if(filters[key]){clauses.push(`EXISTS(${sql})`);params.push(Number(filters[key]))}return all(`SELECT o.*,u.username cashier_en,u.display_name_ar cashier_ar,(SELECT GROUP_CONCAT(m.name_en||': '||p.amount) FROM payments p JOIN payment_methods m ON m.id=p.payment_method_id WHERE p.order_id=o.id) payment_summary FROM orders o LEFT JOIN users u ON u.id=o.user_id ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY o.created_at DESC,o.sequential_no DESC ${filters.active_kitchen==='1'?'':'LIMIT ?'}`, ...params,...(filters.active_kitchen==='1'?[]:[Math.min(1000,Math.max(1,Number(limit)||100))])).map(({request_hash,...o})=>o)}
function refund(id,b,user){return transaction(()=>{const approvedBy=permissions.requirePermission(user,'orders.refund',b.approval),o=getOrder(id);if(!o||o.status!=='completed')throw new Error('Only completed orders can be refunded');required(b.reason,'Refund reason');if(b.restock&&all('SELECT payload FROM order_revisions WHERE order_id=?',id).some(r=>JSON.parse(JSON.parse(r.payload).request).removeItems.length))throw new Error('This order had cancelled items; refund without restocking and record any usable returns through a controlled stocktake');const shift=one("SELECT id FROM shifts WHERE user_id=? AND status='open'",user.id);if(o.payments.length&&!shift)throw new Error('Open a shift to process a refund');const rid=crypto.randomUUID();run('INSERT INTO refunds(id,order_id,user_id,approved_by,shift_id,reason,restock,total) VALUES(?,?,?,?,?,?,?,?)',rid,id,user.id,approvedBy,shift?.id||null,b.reason,b.restock?1:0,o.total);for(const p of o.payments)run('INSERT INTO refund_payments(id,refund_id,payment_method_id,amount) VALUES(?,?,?,?)',crypto.randomUUID(),rid,p.payment_method_id,p.amount);if(b.restock)for(const m of all("SELECT * FROM stock_movements WHERE reference_type='order' AND reference_id=? AND movement_type='sale'",id))stock.move({variantId:m.variant_id,locationId:m.location_id,qty:-m.quantity_base,type:'refund',refType:'refund',refId:rid,userId:user.id,note:b.reason,batchId:m.batch_id,unitCost:m.unit_cost_base});run("UPDATE orders SET status='refunded',payment_status=? WHERE id=?",o.payments.length?'refunded':'cancelled',id);require('./printing/service').enqueue(getOrder(id),{kind:'cancel_order',kitchenOnly:true,userId:user.id});require('./printing/service').enqueue(getOrder(id),{kind:'refund',customerOnly:true,userId:user.id});permissions.audit(user,'order.refund','orders',id,{status:o.status,total:o.total},{status:'refunded',restock:!!b.restock},b.reason,approvedBy);require('./loyalty').reconcile(getOrder(id),user);customers.queueOrder(getOrder(id));return getOrder(id)})}
function fulfill(id,status,user){const next={accepted:'preparing',preparing:'ready',ready:'fulfilled'};return transaction(()=>{const o=getOrder(id);if(o?.status==='completed'&&o.fulfillment_status===status)return o;if(!o||o.status!=='completed'||next[o.fulfillment_status]!==status)throw new Error('Invalid order state transition');if(status==='fulfilled'&&o.payment_status!=='paid')throw new Error('Collect payment before fulfilment');run('UPDATE orders SET fulfillment_status=? WHERE id=?',status,id);permissions.audit(user,'order.fulfill','orders',id,o.fulfillment_status,status);require('./loyalty').reconcile(getOrder(id),user);customers.queueOrder(getOrder(id));return getOrder(id)})}
function collect(id,payments,user){return transaction(()=>{const o=getOrder(id),shift=one("SELECT id FROM shifts WHERE user_id=? AND status='open'",user.id);if(!shift)throw new Error('Open a shift first');if(!o||o.payment_status!=='due'||o.status!=='completed')throw new Error('Order is not awaiting payment');let total=0;for(const p of payments){const m=one('SELECT * FROM payment_methods WHERE id=? AND active=1',Number(p.methodId));if(!m)throw new Error('Invalid payment method');if(m.requires_reference)required(p.reference,'Reference');const amount=money(number(p.amount,'Payment'));total+=amount;run('INSERT INTO payments(order_id,payment_method_id,amount,reference) VALUES(?,?,?,?)',id,m.id,amount,p.reference||null)}if(Math.abs(money(total)-o.total)>0.001)throw new Error('Payments must equal order total');run("UPDATE orders SET payment_status='paid',shift_id=? WHERE id=?",shift.id,id);require('./printing/service').enqueue(getOrder(id),{customerOnly:true,userId:user.id});permissions.audit(user,'order.collect','orders',id,'due','paid');require('./loyalty').reconcile(getOrder(id),user);customers.queueOrder(getOrder(id));return getOrder(id)})}
module.exports={createOrder,getOrder,listOrders,refund,fulfill,collect,queuePrint,normalize};
