const {one,all,run,transaction}=require('./db');
const p=require('./permissions'),orders=require('./orders'),stock=require('./inventory');
const {number,money,required}=require('./validation');
const admin=require('./admin');
function shiftReport(id){const shift=one('SELECT * FROM shifts WHERE id=?',id);if(!shift)throw new Error('Shift not found');const payments=all(`SELECT m.id,m.code,m.name_ar,m.name_en,COALESCE((SELECT SUM(p.amount) FROM payments p JOIN orders o ON o.id=p.order_id WHERE COALESCE(p.shift_id,o.shift_id)=? AND p.payment_method_id=m.id),0) amount,COALESCE((SELECT SUM(p.amount) FROM refund_payments p JOIN refunds r ON r.id=p.refund_id WHERE r.shift_id=? AND p.payment_method_id=m.id),0) refunds FROM payment_methods m ORDER BY sort_order`,id,id);const cash=payments.find(m=>m.code==='cash');const expenses=one(`SELECT COALESCE(SUM(e.amount),0) total FROM expenses e JOIN payment_methods m ON m.id=e.payment_method_id WHERE e.shift_id=? AND m.code='cash'`,id).total;const expected=money(shift.opening_cash+(cash?.amount||0)-(cash?.refunds||0)-expenses);return {...shift,payments,cashSales:cash?.amount||0,cashRefunds:cash?.refunds||0,cashExpenses:expenses,expectedCash:expected,counted:shift.closing_cash_counted,difference:shift.closing_cash_counted==null?null:money(shift.closing_cash_counted-expected)}}
function analytics(from,to){from=from||new Date().toISOString().slice(0,10);to=to||from;const period="date(o.created_at,'localtime') BETWEEN ? AND ? AND o.status='completed'";const sales=one(`SELECT COUNT(*) orders_count,COALESCE(SUM(total),0) total_sales,COALESCE(SUM(discount),0) discounts FROM orders o WHERE ${period}`,from,to);const hourly=all(`SELECT strftime('%H',o.created_at,'localtime') hour,COUNT(*) orders_count,SUM(total) sales FROM orders o WHERE ${period} GROUP BY hour`,from,to);const categories=all(`SELECT c.name_ar,c.name_en,SUM(i.quantity) quantity,SUM(i.line_total*(CASE WHEN o.subtotal>0 THEN o.total/o.subtotal ELSE 0 END)) sales FROM order_items i JOIN orders o ON o.id=i.order_id JOIN products p ON p.id=i.product_id JOIN categories c ON c.id=p.category_id WHERE ${period} GROUP BY c.id`,from,to);const products=all(`SELECT i.product_id,i.product_name_ar name_ar,i.product_name_en name_en,SUM(i.quantity) quantity,SUM(i.line_total*(CASE WHEN o.subtotal>0 THEN o.total/o.subtotal ELSE 0 END)) sales FROM order_items i JOIN orders o ON o.id=i.order_id WHERE ${period} GROUP BY i.product_id ORDER BY quantity DESC`,from,to);const movements=all(`SELECT m.*,v.name_ar variant_ar,v.name_en variant_en,l.name_ar location_ar,l.name_en location_en FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id JOIN stock_locations l ON l.id=m.location_id WHERE date(m.created_at,'localtime') BETWEEN ? AND ? ORDER BY m.id DESC LIMIT 1000`,from,to);const valuation=stock.stockRows().map(r=>{const lots=stock.allocations({variantId:r.variant_id,locationId:r.location_id,allowExpired:true});let known=true,value=0;for(const l of lots){const c=stock.cost(l.variant_id,l.batch_id);if(c==null)known=false;value+=l.qty*(c||0)}return {...r,value:known?money(value):null}});return {from,to,sales,hourly,categories,products,movements,valuation,costs:require('./costing').products(),profitability:require('./costing').period(from,to),finance:admin.financeReport(from,to),shifts:all('SELECT id FROM shifts ORDER BY id DESC LIMIT 100').map(s=>shiftReport(s.id)),production:all('SELECT * FROM production_batches ORDER BY created_at DESC LIMIT 100'),waste:all('SELECT * FROM waste_records ORDER BY created_at DESC LIMIT 100')}}
async function handle(req,res,url,user,b,json){const path=url.pathname,method=req.method;const done=data=>{json(res,200,data);return true};
 if(await require('./reliability-api').handle(req,res,url,user,b,json))return true;
 if(await require('./public-order-api').handle(req,res,url,user,b,json))return true;
 if(require('./ux-api').handle(req,res,url,user,b,json))return true;
 if(require('./commercial-api').handle(req,res,url,user,b,json))return true;
 if(await require('./printing/api').handle(req,res,url,user,b,json))return true;
 const amendment=path.match(/^\/api\/orders\/([^/]+)\/amend$/);if(amendment&&method==='POST')return done({order:require('./printing/amendments').amend(amendment[1],b,user)});
 if(path==='/api/permissions'){if(method==='GET')return done({catalog:p.catalog,overrides:all('SELECT * FROM role_permissions')});p.save(b.role,b.permissions,user);return done({ok:true})}
 if(path==='/api/settings'){if(method==='GET')return done({settings:Object.fromEntries(all("SELECT key,value FROM settings WHERE key NOT IN ('installation_id','next_order_no')").map(r=>[r.key,r.value])),printers:all('SELECT * FROM printer_settings'),wasteReasons:all('SELECT * FROM waste_reasons')});transaction(()=>{for(const [key,value] of Object.entries(b)){if(!['online_confirmation_timeout_minutes','online_order_alert_sound','kitchen_warning_minutes','kitchen_late_minutes','restaurant_name_ar','restaurant_name_en','consumption_rule','pickup_enabled','delivery_enabled','backup_interval_hours','costing_method','target_food_cost_percent','low_margin_percent','delivery_fee','restaurant_phone','restaurant_address','restaurant_hours','restaurant_logo','receipt_footer_ar','receipt_footer_en'].includes(key)&&! /^(tax|service|packaging|other)_(enabled|type|value)$/.test(key))throw new Error('Unsupported setting');if(key.endsWith('_minutes')&&(number(value,'Minutes')>1440))throw Error('Minutes must be 1 to 1440');if(key==='online_order_alert_sound'&&!['true','false'].includes(String(value)))throw Error('Invalid sound setting');if(key==='costing_method'&&!['latest','average'].includes(value))throw new Error('Invalid costing method');if(key==='target_food_cost_percent'&&(number(value)>100))throw new Error('Target food cost must be 1–100');if(key.endsWith('_type')&&!['fixed','percentage'].includes(value))throw new Error('Invalid charge type');if(key.endsWith('_value')||key==='delivery_fee')number(value,'Charge',{zero:true});if(key==='consumption_rule'&&!['preferred','fifo','fefo'].includes(value))throw new Error('Invalid consumption rule');if(key.endsWith('_enabled')&&!['true','false'].includes(String(value)))throw new Error('Invalid setting');if(key==='backup_interval_hours')number(value,'Backup interval');const old=one('SELECT value FROM settings WHERE key=?',key)?.value;run('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,String(value));p.audit(user,'settings.change','settings',key,old,value)}});return done({ok:true})}
 if(path==='/api/admin/payment-methods'){if(method==='GET')return done({rows:all('SELECT * FROM payment_methods')});const id=Number(b.id)||null;transaction(()=>{const old=id?one('SELECT * FROM payment_methods WHERE id=?',id):null;required(b.nameAr,'Arabic name');required(b.code,'Code');if(old?.code==='cash'&&(b.code!=='cash'||b.active===false))throw new Error('Cash method must remain available for reconciliation');if(id)run('UPDATE payment_methods SET name_ar=?,name_en=?,requires_reference=?,active=? WHERE id=?',b.nameAr,b.nameEn||null,b.requiresReference?1:0,b.active===false?0:1,id);else run('INSERT INTO payment_methods(code,name_ar,name_en,requires_reference) VALUES(?,?,?,?)',b.code,b.nameAr,b.nameEn||null,b.requiresReference?1:0);p.audit(user,'payment_method.save','payment_methods',id||b.code,old,b)});return done({ok:true})}
 if(path==='/api/admin/modifiers'){if(method==='GET')return done({rows:all('SELECT * FROM modifiers').map(m=>({...m,lines:all('SELECT * FROM modifier_lines WHERE modifier_id=?',m.id)}))});transaction(()=>{const id=Number(run('INSERT INTO modifiers(product_id,name_ar,name_en,price) VALUES(?,?,?,?)',Number(b.productId),required(b.nameAr),b.nameEn||null,number(b.price,'Price',{zero:true})).lastInsertRowid);for(const l of b.lines||[]){const qty=Number(l.quantityBase);if(!Number.isFinite(qty)||qty===0)throw new Error('Modifier quantity must be finite and nonzero');run('INSERT INTO modifier_lines(modifier_id,ingredient_id,quantity_base) VALUES(?,?,?)',id,Number(l.ingredientId),qty)}p.audit(user,'modifier.create','modifiers',id,null,b)});return done({ok:true})}
 const product=path.match(/^\/api\/admin\/products\/(\d+)$/);if(product&&method==='PATCH'){transaction(()=>{const old=one('SELECT * FROM products WHERE id=?',Number(product[1]));if(!old)throw new Error('Product not found');required(b.reason,'Change reason');run('UPDATE products SET price=?,image_url=?,available_online=?,name_ar=?,name_en=? WHERE id=?',number(b.price??old.price,'Price',{zero:true}),b.imageUrl??old.image_url,b.availableOnline===undefined?old.available_online:b.availableOnline?1:0,b.nameAr||old.name_ar,b.nameEn||old.name_en,old.id);if(b.price!==undefined)run('UPDATE products SET price_known=? WHERE id=?',Number(b.price)>0?1:0,old.id);p.audit(user,'product.change','products',old.id,old,b,b.reason)});return done({ok:true})}
 if(path==='/api/admin/locations'&&method==='POST'){run('INSERT INTO stock_locations(code,name_ar,name_en,priority) VALUES(?,?,?,?)',required(b.code),required(b.nameAr),b.nameEn||null,number(b.priority??50,'Priority',{zero:true}));return done({ok:true})}
 if(path==='/api/admin/waste-reasons'&&method==='POST'){run('INSERT INTO waste_reasons(name_ar,name_en) VALUES(?,?)',required(b.nameAr),b.nameEn||null);return done({ok:true})}
 if(path==='/api/inventory/alerts'){const batches=stock.batches(),today=new Date(),soon=new Date(Date.now()+7*86400000).toISOString().slice(0,10);return done({lowStock:stock.stockSummary().filter(r=>r.quantity_base<=r.low_stock_base),expiring:batches.filter(r=>r.expires_on&&r.expires_on<=soon),batches})}
 if(path==='/api/inventory/threshold'&&method==='POST'){run('UPDATE ingredients SET low_stock_base=? WHERE id=?',number(b.quantity,'Threshold',{zero:true}),Number(b.ingredientId));return done({ok:true})}
 if(path==='/api/inventory/movements')return done({rows:analytics(url.searchParams.get('from'),url.searchParams.get('to')).movements.map(({unit_cost_base,...r})=>p.can(user,'reports.costs')?{...r,unit_cost_base}:r)});
 if(path==='/api/reports/platform')return done(analytics(url.searchParams.get('from'),url.searchParams.get('to')));
 if(path==='/api/shifts/history')return done({rows:all('SELECT id FROM shifts WHERE user_id=? ORDER BY id DESC LIMIT 100',user.id).map(s=>shiftReport(s.id))});
 if(path==='/api/shifts/close'&&method==='POST'){const sh=one("SELECT * FROM shifts WHERE user_id=? AND status='open'",user.id);if(!sh)throw new Error('No open shift');const counted=number(b.closingCash,'Closing cash',{zero:true});transaction(()=>{run("UPDATE shifts SET status='closed',closed_at=CURRENT_TIMESTAMP,closing_cash_counted=? WHERE id=?",counted,sh.id);p.audit(user,'shift.close','shifts',sh.id,sh,{closingCash:counted})});return done(shiftReport(sh.id))}
 const action=path.match(/^\/api\/orders\/([^/]+)\/(refund|fulfill|collect|reprint)$/);if(action&&method==='POST'){const id=decodeURIComponent(action[1]);if(action[2]==='refund')return done({order:orders.refund(id,b,user)});if(action[2]==='fulfill')return done({order:require('./response-views').order(user,orders.fulfill(id,b.status,user))});if(action[2]==='collect')return done({order:orders.collect(id,b.payments||[],user)});if(!orders.getOrder(id))throw new Error('Order not found');transaction(()=>{if(!p.can(user,'customers.pii'))require('./printing/service').enqueue(orders.getOrder(id),{reprint:true,kitchenOnly:true});else orders.queuePrint(id,true);p.audit(user,'order.reprint','orders',id,null,{reprint:true})});return done({ok:true})}
 if(path==='/api/printing/settings')return done({rows:all('SELECT * FROM printer_settings')});
 if(path==='/api/printing/complete'&&method==='POST'){if(!p.can(user,'customers.pii')&&one('SELECT job_type FROM print_queue WHERE id=?',Number(b.jobId))?.job_type!=='kitchen'){const e=Error('Kitchen tickets only');e.status=403;throw e}run("UPDATE print_queue SET status='printed',printed_at=CURRENT_TIMESTAMP WHERE id=?",Number(b.jobId));return done({ok:true})}
 if(path==='/api/sync/status')return done({status:require('./sync').getSyncStatus(),pending:one("SELECT COUNT(*) count FROM sync_queue WHERE status IN ('pending','retrying')").count,failed:all("SELECT id,entity_type,entity_id,attempts,last_error FROM sync_queue WHERE status='dead-letter' ORDER BY id LIMIT 100"),logs:all('SELECT * FROM sync_log ORDER BY id DESC LIMIT 100')});
 if(path==='/api/sync/retry'&&method==='POST')return done(await require('./sync').syncOnce());
 return false;
}
module.exports={handle,shiftReport,analytics};
