const {one,all,run,transaction}=require('./db'),p=require('./permissions'),loyalty=require('./loyalty');
async function handle(req,res,url,user,b,json){const path=url.pathname,method=req.method,done=d=>{json(res,200,d);return true};
 if(path==='/api/sync/retry'&&method==='POST'&&b.id){if(!b.reason||!['retry','skip'].includes(b.action))throw Error('Action and review reason required');transaction(()=>{const old=one("SELECT * FROM sync_queue WHERE id=? AND status='dead-letter'",Number(b.id));if(!old)throw Error('Failed event not found');run('UPDATE sync_queue SET status=?,attempts=0,next_retry_at=0,last_error=? WHERE id=?',b.action==='retry'?'pending':'synced',b.action==='skip'?'Operator skipped: '+b.reason:null,old.id);p.audit(user,'sync.review','sync_queue',old.id,{status:old.status},{action:b.action},b.reason)});return done({ok:true})}
 if(path==='/api/updates/check')return done(await require('./updates').check());
 if(path==='/api/menu/publication')return done({rows:require('./catalog').publication().map(({id,name_ar,name_en,published,reasons,active,in_stock})=>({id,name_ar,name_en,published,reasons,posAvailable:!!active&&!!in_stock}))});
 if(path==='/api/settings/consumption-locations'){if(method==='GET')return done({rows:all('SELECT * FROM consumption_locations')});if(!Array.isArray(b.locationIds)||!b.locationIds.length)throw Error('Select at least one consumption location');if(b.stationCode!=='default'&&!one('SELECT id FROM preparation_stations WHERE code=?',b.stationCode))throw Error('Invalid station');transaction(()=>{run('DELETE FROM consumption_locations WHERE station_code=?',b.stationCode);for(const id of new Set(b.locationIds)){if(!one('SELECT id FROM stock_locations WHERE id=? AND active=1',Number(id)))throw Error('Invalid location');run('INSERT INTO consumption_locations VALUES(?,?)',b.stationCode,Number(id))}p.audit(user,'consumption_locations.save','station',b.stationCode,null,b)});return done({ok:true})}
 const variant=path.match(/^\/api\/admin\/variants\/(\d+)$/);if(variant&&method==='PATCH'){if(typeof b.active!=='boolean')throw Error('Active flag required');run('UPDATE ingredient_variants SET active=? WHERE id=?',b.active?1:0,Number(variant[1]));p.audit(user,'variant.active','variant',variant[1],null,b);return done({ok:true})}
 if(path==='/api/loyalty/settings'){if(method==='GET')return done({settings:loyalty.settings(),rewards:loyalty.rewards()});return done({settings:transaction(()=>{const result=loyalty.saveSettings(b);p.audit(user,'loyalty.settings','loyalty','settings',null,result);return result})})}
 if(path==='/api/loyalty/rewards'&&method==='POST')return done({reward:transaction(()=>{const reward=loyalty.saveReward(b);p.audit(user,'loyalty.reward','reward',reward.id,null,reward);return reward})});
 if(path==='/api/loyalty/adjust'&&method==='POST'){if(!b.reason||!b.requestId||!Number.isInteger(b.delta))throw Error('Reason, request ID and integer points required');return done({id:transaction(()=>{const id=loyalty.append({customerId:b.customerId,type:'manual_adjustment',delta:b.delta,key:'adjust:'+b.requestId,reason:b.reason,actor:user.global_id});p.audit(user,'loyalty.adjust','customer',b.customerId,null,{delta:b.delta},b.reason);return id})})}
 if(path==='/api/loyalty/customer'&&method==='GET'){const id=url.searchParams.get('id'),link=one('SELECT account_id FROM customer_links WHERE customer_id=?',id),localEntries=all('SELECT * FROM loyalty_ledger WHERE customer_id=? ORDER BY created_at DESC LIMIT 100',id);if(link){try{const cloud=await require('./sync-service').cloud('/api/sync/loyalty/balance',{method:'POST',body:JSON.stringify({customerId:link.account_id})});return done({...cloud,source:'cloud',redemptionOnlineOnly:true})}catch{return done({points:null,source:'offline',localEntries,redemptionOnlineOnly:true})}}return done({points:null,source:'unlinked',localEntries,redemptionOnlineOnly:true})}
 if(path==='/api/customers/link'&&method==='POST'){if(!b.reason)throw Error('Link reason required');const cloud=await require('./sync-service').cloud('/api/sync/customers'),account=cloud.customers.find(c=>c.id===b.accountId);if(!account)throw Error('Cloud account not found');transaction(()=>{require('./customers').link(b.customerId,account);p.audit(user,'customer.link','customer',b.customerId,null,{accountId:b.accountId},b.reason)});return done({ok:true})}
 if(path==='/api/remote/status')return done({users:all("SELECT global_id,username,role,remote_access_enabled FROM users WHERE role IN ('owner','manager')"),commands:all('SELECT * FROM command_receipts ORDER BY applied_at DESC LIMIT 100')});
 return false;
}
module.exports={handle};
