const crypto=require('crypto');
const {all,one,run,transaction}=require('./db');
const {number,required}=require('./validation');
function variant(id){const v=one('SELECT * FROM ingredient_variants WHERE id=? AND active=1',Number(id));if(!v)throw new Error('Variant not found');number(v.conversion_to_base,'Conversion');return v}
function location(id){if(!one('SELECT id FROM stock_locations WHERE id=? AND active=1',Number(id)))throw new Error('Location not found');return Number(id)}
function cost(variantId,batchId=null){const row=one(`SELECT SUM(quantity_base*unit_cost_base)/SUM(quantity_base) cost FROM stock_movements WHERE variant_id=? AND batch_id IS ? AND quantity_base>0 AND unit_cost_base IS NOT NULL AND movement_type IN ('purchase','production_output','opening')`,variantId,batchId);return row?.cost??null}
function move({variantId,locationId,qty,type,refType,refId,userId=null,note=null,batchId=null,unitCost=null}){location(locationId);run('INSERT INTO stock_movements(variant_id,location_id,quantity_base,movement_type,reference_type,reference_id,user_id,note,batch_id,unit_cost_base) VALUES(?,?,?,?,?,?,?,?,?,?)',Number(variantId),Number(locationId),qty,type,refType,String(refId),userId,note,batchId,unitCost)}
function allocations({ingredientId,variantId,locationId,allowExpired=false,rule,allowedLocations}){
 rule=rule||one("SELECT value FROM settings WHERE key='consumption_rule'")?.value||'preferred';
 let rows=all(`SELECT v.id variant_id,v.preferred,l.id location_id,l.priority,m.batch_id,b.expires_on,MIN(m.created_at) first_received,SUM(m.quantity_base) qty FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id JOIN stock_locations l ON l.id=m.location_id LEFT JOIN stock_batches b ON b.id=m.batch_id WHERE v.active=1 AND l.active=1 ${ingredientId?'AND v.ingredient_id=?':''} ${variantId?'AND v.id=?':''} ${locationId?'AND l.id=?':''} GROUP BY v.id,l.id,m.batch_id HAVING qty>0.000001`,...[ingredientId,variantId,locationId].filter(x=>x!=null).map(Number));
 if(allowedLocations)rows=rows.filter(r=>allowedLocations.includes(r.location_id));
 if(!allowExpired){const today=new Intl.DateTimeFormat('en-CA',{timeZone:one("SELECT value FROM settings WHERE key='restaurant_timezone'")?.value||'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());rows=rows.filter(r=>!r.expires_on||r.expires_on>=today)}
 return rows.sort((a,b)=>rule==='fefo'?(a.expires_on||'9999').localeCompare(b.expires_on||'9999')||a.first_received.localeCompare(b.first_received):rule==='fifo'?a.first_received.localeCompare(b.first_received):b.preferred-a.preferred||a.priority-b.priority||a.first_received.localeCompare(b.first_received));
}
function consume({ingredientId,variantId,locationId,qty,type,refType,refId,userId,note,allowExpired=false,rule,allowedLocations}){
 qty=number(qty);const rows=allocations({ingredientId,variantId,locationId,allowExpired,rule,allowedLocations});const available=rows.reduce((s,r)=>s+r.qty,0);if(available+1e-8<qty){const ingredient=ingredientId?one('SELECT name_ar,name_en,base_unit FROM ingredients WHERE id=?',ingredientId):null;const error=new Error(allowedLocations?'Kitchen stock is insufficient: '+(ingredient?.name_en||ingredient?.name_ar||'ingredient')+'. Transfer/replenish stock.':`Insufficient usable stock: required ${qty}, available ${available}`);if(ingredient)error.details={name_ar:ingredient.name_ar,name_en:ingredient.name_en,unit:ingredient.base_unit,required:qty,available};throw error}
 const taken=[];let remaining=qty;
 for(const r of rows){if(remaining<1e-8)break;const take=Math.min(remaining,r.qty);const unitCost=cost(r.variant_id,r.batch_id);move({variantId:r.variant_id,locationId:r.location_id,qty:-take,type,refType,refId,userId,note,batchId:r.batch_id,unitCost});taken.push({...r,qty:take,unitCost});remaining-=take}return taken;
}
function consumeIngredient({ingredientId,specificVariantId,quantityBase,referenceType,referenceId,userId,note,stationCode='default'}){const allowedLocations=all('SELECT location_id FROM consumption_locations WHERE station_code=?',stationCode).map(r=>r.location_id);return consume({allowedLocations,ingredientId,variantId:specificVariantId||undefined,qty:quantityBase,type:'sale',refType:referenceType,refId:referenceId,userId,note})}
function batch(variantId,batchNumber,expiresOn){if(expiresOn&&(!/^\d{4}-\d{2}-\d{2}$/.test(expiresOn)||!Number.isFinite(Date.parse(expiresOn))||new Date(expiresOn).toISOString().slice(0,10)!==expiresOn))throw new Error('Invalid expiry date');const id=crypto.randomUUID();run('INSERT INTO stock_batches(id,variant_id,batch_number,expires_on) VALUES(?,?,?,?)',id,variantId,batchNumber||id,expiresOn||null);return id}
function receiveStock({variantId,locationId,quantityPurchase,unitPricePurchase=null,userId,referenceId,note=null,batchNumber,expiresOn}){return transaction(()=>{const v=variant(variantId),qty=number(quantityPurchase)*v.conversion_to_base,unitCost=unitPricePurchase==null||unitPricePurchase===''?null:number(unitPricePurchase,'Cost',{zero:true})/v.conversion_to_base;move({variantId:v.id,locationId,qty,type:'purchase',refType:'purchase',refId:referenceId||crypto.randomUUID(),userId,note,batchId:batch(v.id,batchNumber,expiresOn),unitCost});return qty})}
function transferStock({variantId,fromLocationId,toLocationId,quantityPurchase,userId,note}){return transaction(()=>{if(Number(fromLocationId)===Number(toLocationId))throw new Error('Choose different locations');location(toLocationId);const v=variant(variantId),id=crypto.randomUUID();for(const r of consume({variantId:v.id,locationId:fromLocationId,qty:number(quantityPurchase)*v.conversion_to_base,type:'transfer_out',refType:'transfer',refId:id,userId,note,allowExpired:true}))move({variantId:v.id,locationId:toLocationId,qty:r.qty,type:'transfer_in',refType:'transfer',refId:id,userId,note,batchId:r.batch_id,unitCost:r.unitCost});return id})}
function recordWaste({variantId,locationId,quantityPurchase,reason,note,userId}){return transaction(()=>{const v=variant(variantId),qty=number(quantityPurchase)*v.conversion_to_base,id=crypto.randomUUID();required(reason,'Waste reason');consume({variantId:v.id,locationId,qty,type:'waste',refType:'waste',refId:id,userId,note:reason,allowExpired:true});run('INSERT INTO waste_records(id,variant_id,location_id,quantity_base,reason,note,user_id) VALUES(?,?,?,?,?,?,?)',id,v.id,Number(locationId),qty,reason,note||null,userId);return id})}
function production({inputs,outputs,note,userId}){return transaction(()=>{if(!inputs?.length||!outputs?.length)throw new Error('Production requires inputs and actual outputs');const id=crypto.randomUUID();run('INSERT INTO production_batches(id,user_id,note) VALUES(?,?,?)',id,userId,note||null);let totalCost=0,known=true;for(const l of inputs){location(l.locationId);const v=variant(l.variantId),qty=number(l.quantityPurchase)*v.conversion_to_base;const taken=consume({variantId:v.id,locationId:l.locationId,qty,type:'production_input',refType:'production',refId:id,userId,note});for(const r of taken){if(r.unitCost==null)known=false;totalCost+=r.qty*(r.unitCost||0)}run("INSERT INTO production_lines(batch_id,direction,variant_id,location_id,quantity_base) VALUES(?,'input',?,?,?)",id,v.id,Number(l.locationId),qty)}
 // Multiple outputs need explicit cost shares; one output receives all input cost.
 if(outputs.length>1&&Math.abs(outputs.reduce((s,l)=>s+number(l.costShare,'Cost share',{zero:true}),0)-1)>1e-6)throw new Error('Output cost shares must total 1');
 for(const l of outputs){const v=variant(l.variantId),qty=number(l.quantityPurchase)*v.conversion_to_base;run("INSERT INTO production_lines(batch_id,direction,variant_id,location_id,quantity_base) VALUES(?,'output',?,?,?)",id,v.id,Number(l.locationId),qty);move({variantId:v.id,locationId:l.locationId,qty,type:'production_output',refType:'production',refId:id,userId,note,batchId:batch(v.id,l.batchNumber,l.expiresOn),unitCost:known?totalCost*(outputs.length===1?1:l.costShare)/qty:null})}return id})}
function stockRows(){return all(`SELECT i.id ingredient_id,i.name_ar ingredient_name_ar,i.name_en ingredient_name_en,i.base_unit,v.id variant_id,v.name_ar variant_name_ar,v.name_en variant_name_en,v.brand,v.purchase_unit,v.conversion_to_base,l.id location_id,l.name_ar location_name_ar,l.name_en location_name_en,SUM(m.quantity_base) quantity_base FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id JOIN ingredients i ON i.id=v.ingredient_id JOIN stock_locations l ON l.id=m.location_id GROUP BY v.id,l.id HAVING ABS(quantity_base)>0.000001 ORDER BY i.id,v.id,l.priority`)}
function stockSummary(){return all(`SELECT i.id ingredient_id,i.name_ar,i.name_en,i.base_unit,i.low_stock_base,COALESCE(SUM(m.quantity_base),0) quantity_base FROM ingredients i LEFT JOIN ingredient_variants v ON v.ingredient_id=i.id LEFT JOIN stock_movements m ON m.variant_id=v.id WHERE i.active=1 GROUP BY i.id ORDER BY i.id`)}
function batches(){return all(`SELECT b.*,v.name_ar variant_ar,v.name_en variant_en,l.id location_id,l.name_ar location_ar,l.name_en location_en,COALESCE(SUM(m.quantity_base),0) quantity_base FROM stock_batches b JOIN ingredient_variants v ON v.id=b.variant_id JOIN stock_movements m ON m.batch_id=b.id JOIN stock_locations l ON l.id=m.location_id GROUP BY b.id,l.id HAVING quantity_base>0 ORDER BY b.expires_on`)}
module.exports={stockRows,stockSummary,consumeIngredient,receiveStock,transferStock,recordWaste,production,consume,move,variant,cost,batches,allocations};
