const {all,one,run,transaction}=require('./db');
const orders=require('./orders');
let timer=null,inFlight=null,status={enabled:false,online:false,lastSuccess:null,lastError:null};
async function request(base,path,opt={}){const r=await fetch(base+path,{...opt,signal:AbortSignal.timeout(Math.max(5000,Number(process.env.SYNC_TIMEOUT_MS)||15000)),headers:{'content-type':'application/json','x-sync-secret':process.env.SYNC_SECRET||'trackbite-dev-secret',...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function perform(){const base=(process.env.CLOUD_API_URL||'').replace(/\/$/,'');if(!base)return status={...status,enabled:false};status.enabled=true;try{
 const installationId=one("SELECT value FROM settings WHERE key='installation_id'").value;
 await request(base,'/api/sync/heartbeat',{method:'POST',body:JSON.stringify({installationId})});
 const catalog={categories:all('SELECT id,name_ar,name_en,sort_order FROM categories WHERE active=1 ORDER BY sort_order,id'),products:all('SELECT id,category_id,name_ar,name_en,price,image_url,description_ar,description_en FROM products WHERE active=1 AND in_stock=1 AND available_online=1 AND category_id IN (SELECT id FROM categories WHERE active=1) AND EXISTS(SELECT 1 FROM recipes r WHERE r.product_id=products.id) ORDER BY id'),modifiers:all('SELECT id,product_id,name_ar,name_en,price FROM modifiers WHERE active=1'),orderTypes:all('SELECT code id,* FROM order_types WHERE active=1 AND online=1'),settings:Object.fromEntries(all("SELECT key,value FROM settings WHERE key IN ('pickup_enabled','delivery_enabled','restaurant_name_ar','restaurant_name_en','delivery_fee','restaurant_phone','restaurant_address','restaurant_hours') OR key LIKE 'tax_%' OR key LIKE 'service_%' OR key LIKE 'packaging_%' OR key LIKE 'other_%'").map(r=>[r.key,r.value]))};
 await request(base,'/api/sync/catalog',{method:'POST',body:JSON.stringify(catalog)});
 const pending=await request(base,'/api/sync/orders/pending');
 for(const row of pending.orders||[]){try{const local=transaction(()=>{const existing=one('SELECT local_order_id FROM cloud_imports WHERE cloud_order_id=?',row.id);if(existing)return orders.getOrder(existing.local_order_id);const p=row.payload;const created=orders.createOrder({source:'web',requestId:row.id,userId:null,customerName:p.customerName||null,customerPhone:p.customerPhone||null,orderType:p.orderType||'pickup',items:p.items,notes:p.notes||null,deferredPayment:true,deliveryAddress:p.deliveryAddress||null,deliveryDetails:p.deliveryDetails||{},deliveryFee:p.deliveryFee||0});if(Math.abs(created.total-Number(p.total))>0.001)throw new Error('Menu price changed; online order requires review');run('INSERT INTO cloud_imports(cloud_order_id,local_order_id) VALUES(?,?)',row.id,created.id);return created});await request(base,`/api/sync/orders/${encodeURIComponent(row.id)}/ack`,{method:'POST',body:JSON.stringify({localOrderId:local.id,status:local.fulfillment_status,paymentStatus:local.payment_status})})}catch(e){await request(base,`/api/sync/orders/${encodeURIComponent(row.id)}/error`,{method:'POST',body:JSON.stringify({error:e.message})})}}
 const events=all("SELECT * FROM sync_queue WHERE status='pending' ORDER BY id LIMIT 500");
 for(const e of events){try{await request(base,'/api/sync/events',{method:'POST',body:JSON.stringify({installationId,eventKey:e.event_key,eventType:`${e.entity_type}.${e.operation}`,entityType:e.entity_type,entityId:e.entity_id,operation:e.operation,payload:JSON.parse(e.payload||'{}')})});run("UPDATE sync_queue SET status='synced',synced_at=CURRENT_TIMESTAMP,attempts=attempts+1,last_error=NULL WHERE id=?",e.id)}catch(error){run('UPDATE sync_queue SET attempts=attempts+1,last_error=? WHERE id=?',error.message,e.id);throw error}}
 const recovered=!status.online;status={enabled:true,online:true,lastSuccess:new Date().toISOString(),lastError:null};if(recovered)run('INSERT INTO sync_log(ok,message) VALUES(1,?)','Cloud connected; queued records are being delivered');
 }catch(e){if(status.lastError!==e.message)run('INSERT INTO sync_log(ok,message) VALUES(0,?)',e.message);status={...status,online:false,lastError:e.message}}return status}
function syncOnce(){if(inFlight)return inFlight;inFlight=perform().finally(()=>inFlight=null);return inFlight}
function startSyncLoop(){if(timer)return;syncOnce();timer=setInterval(syncOnce,Number(process.env.SYNC_INTERVAL_MS||10000));timer.unref()}
module.exports={syncOnce,startSyncLoop,getSyncStatus:()=>status};
