const {all,one,run,transaction}=require('./db');
const orders=require('./orders');const policy=require('./sync-policy');policy.configuration();
let timer=null,inFlight=null,status={enabled:false,online:false,lastSuccess:null,lastError:null};
async function request(base,path,opt={}){const r=await fetch(base+path,{...opt,signal:AbortSignal.timeout(Math.max(5000,Number(process.env.SYNC_TIMEOUT_MS)||15000)),headers:{'content-type':'application/json','x-sync-secret':policy.configuration().secret,'x-installation-id':one("SELECT value FROM settings WHERE key='installation_id'").value,...(opt.headers||{})}});const d=await r.json();if(!r.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.status=r.status;throw e};return d}
async function perform(){const base=(process.env.CLOUD_API_URL||'').replace(/\/$/,'');if(!base)return status={...status,enabled:false};status.enabled=true;try{
 const installationId=one("SELECT value FROM settings WHERE key='installation_id'").value;
 const heartbeat=await request(base,'/api/sync/heartbeat',{method:'POST',body:JSON.stringify({installationId})});
 status.pairingVerified=heartbeat.installationId===installationId;status.cloudHeartbeat=heartbeat.heartbeat||null;
 let cursor=null;do{const page=await request(base,'/api/sync/orders/pending'+(cursor?'?after='+cursor:''));require('./online-orders').ingest(page.orders||[]);cursor=page.next||null}while(cursor);await require('./online-orders').deliver((path,opt)=>request(base,path,opt));
 if(heartbeat.capabilities?.includes('commands')){
  const staff=all("SELECT global_id id,username,role,password_hash,active,session_version revision FROM users WHERE remote_access_enabled=1 AND role IN ('owner','manager')").map(u=>({...u,permissions:require('./permissions').list(one('SELECT * FROM users WHERE global_id=?',u.id))}));
  const resources={ingredients:all('SELECT id,name_ar,name_en,base_unit FROM ingredients WHERE active=1'),stations:all('SELECT * FROM preparation_stations'),categories:all('SELECT * FROM categories'),products:all('SELECT id,category_id,station_id,name_ar,name_en,price,active,in_stock,available_online,description_ar,description_en,image_url FROM products'),modifiers:all('SELECT * FROM modifiers')};const roster={installationId,staff,resources},revision=require('node:crypto').createHash('sha256').update(JSON.stringify(roster)).digest('hex');if(status.staffRevision!==revision||heartbeat.staffRevision!==revision){await request(base,'/api/sync/staff',{method:'POST',body:JSON.stringify({...roster,revision})});status.staffRevision=revision}
  const pendingCommands=await request(base,'/api/sync/commands');for(const command of pendingCommands.commands){await request(base,'/api/sync/commands/'+command.id+'/ack',{method:'POST',body:JSON.stringify({status:'Delivered'})});const outcome=require('./remote-commands').apply(command);await request(base,'/api/sync/commands/'+command.id+'/ack',{method:'POST',body:JSON.stringify(outcome)})}
 }
 if(heartbeat.capabilities?.includes('accounts')){const data=await request(base,'/api/sync/customers');for(const c of data.customers){try{transaction(()=>require('./customers').attach(c.id,{customerName:c.name,customerPhone:c.phone,memberCode:c.member_code,fromCloud:true}))}catch(e){status.customerLinkError=e.message}}}
 const catalog=require('./catalog').build();status.localCatalogRevision=catalog.revision;
 if(catalog.revision!==status.cloudCatalogRevision||'catalogRevision' in heartbeat&&heartbeat.catalogRevision!==catalog.revision){const ack=await request(base,'/api/sync/catalog',{method:'POST',body:JSON.stringify(catalog)});status.cloudCatalogRevision=ack.revision||catalog.revision;status.lastCatalogSync=new Date().toISOString()}
 status.catalogPending=status.localCatalogRevision!==status.cloudCatalogRevision;
 await require('./online-orders').deliver((path,opt)=>request(base,path,opt));
 const events=all("SELECT q.* FROM sync_queue q WHERE q.status IN ('pending','retrying') AND q.next_retry_at<=? AND NOT EXISTS(SELECT 1 FROM sync_queue prior WHERE prior.entity_type=q.entity_type AND prior.entity_id=q.entity_id AND prior.id<q.id AND prior.status!='synced') ORDER BY q.id LIMIT 100",Date.now());
 for(const e of events){if(e.entity_type==='orders'&&one('SELECT 1 FROM online_order_inbox WHERE local_order_id=? AND decision_pending=1',e.entity_id))continue;try{let eventPayload=JSON.parse(e.payload||'{}');if(e.entity_type==='loyalty'){const link=one('SELECT account_id FROM customer_links WHERE customer_id=?',require('./customer-management').primary(eventPayload.customer_id)?.id);if(!link){run('UPDATE sync_queue SET next_retry_at=? WHERE id=?',Date.now()+60000,e.id);continue}eventPayload.customer_id=link.account_id}await request(base,'/api/sync/events',{method:'POST',body:JSON.stringify({installationId,eventKey:e.event_key,eventType:e.entity_type+'.'+e.operation,entityType:e.entity_type,entityId:e.entity_id,operation:e.operation,payload:eventPayload})});run("UPDATE sync_queue SET status='synced',synced_at=CURRENT_TIMESTAMP,attempts=attempts+1,last_error=NULL WHERE id=?",e.id)}catch(error){const attempt=e.attempts+1,dead=attempt>=5||error instanceof SyntaxError;run('UPDATE sync_queue SET status=?,attempts=?,last_error=?,next_retry_at=? WHERE id=?',dead?'dead-letter':'retrying',attempt,error.message,Date.now()+policy.backoff(attempt),e.id);if(!error.status&&!(error instanceof SyntaxError))throw error}}
 const recovered=!status.online;status={...status,enabled:true,online:true,lastSuccess:new Date().toISOString(),lastError:null};if(recovered)run('INSERT INTO sync_log(ok,message) VALUES(1,?)','Cloud connected; queued records are being delivered');
 }catch(e){if(status.lastError!==e.message)run('INSERT INTO sync_log(ok,message) VALUES(0,?)',e.message);status={...status,online:false,lastError:e.message}}return status}
function syncOnce(){if(inFlight)return inFlight;inFlight=perform().finally(()=>inFlight=null);return inFlight}
function startSyncLoop(){if(timer)return;syncOnce();timer=setInterval(syncOnce,Number(process.env.SYNC_INTERVAL_MS||10000));timer.unref()}
module.exports={cloud:(path,opt)=>request(policy.configuration().url,path,opt),syncOnce,startSyncLoop,getSyncStatus:()=>({...status,environment:process.env.DEMO_MODE==='true'?'DEMO':'PRODUCTION',cloudOrigin:policy.configuration().url,installation:one("SELECT value FROM settings WHERE key='installation_id'")?.value,incoming:require('./online-orders').counts()})};
