const {one,run,transaction}=require('./db'),s=require('./ux-service'),admin=require('./admin'),p=require('./permissions'),{number,required}=require('./validation');
function execute(type,rows,user,requestId){const invoices=new Map(),result=[];
 for(let index=0;index<rows.length;index++){const r=rows[index];try{
 if(type==='materials'){result.push(s.material({nameAr:required(r.Material,'Material'),nameEn:r.English,unit:required(r.Unit,'Unit'),defaultLocationId:r.Location?s.match('stock_locations',r.Location)?.id:null,materialType:r.Type||'purchased'},user));if(r.Location&&!s.match('stock_locations',r.Location))throw Error('Location not found. Choose an existing warehouse.');}
 if(type==='menu'){let category=s.match('categories',required(r.Category,'Category'));if(!category)category={id:admin.addCategory({nameAr:r.Category})};const sku=required(r.SKU,'SKU'),old=one('SELECT * FROM products WHERE sku=?',sku);if(old){result.push({id:old.id,reused:true});continue}const price=r.Price===''||r.Price==null?null:number(r.Price,'Price');const id=admin.addProduct({categoryId:category.id,nameAr:required(r.Item,'Item'),nameEn:r.English,sku,price:price??0});run('UPDATE products SET setup_required=1,price_known=?,available_online=0,in_stock=0 WHERE id=?',price==null?0:1,id);p.audit(user,'menu.import','products',id,null,r);result.push({id});}
 if(type==='prices'){const item=r.SKU?one('SELECT * FROM products WHERE sku=?',r.SKU):s.match('products',r.Item);if(!item)throw Error('Menu item not found. Use its SKU or exact name.');const price=number(required(String(r.Price??''),'Price'));run('UPDATE products SET price=?,price_known=1 WHERE id=?',price,item.id);p.audit(user,'price.import','products',item.id,{price:item.price},{price});result.push({id:item.id});}
 if(type==='purchases'){const ing=r.materialId?one('SELECT * FROM ingredients WHERE id=?',Number(r.materialId)):s.match('ingredients',required(r.Material,'Material'));if(!ing)throw Error('Material not found. Add it inline or import Raw Materials first.');const loc=(r.locationId?one('SELECT * FROM stock_locations WHERE id=?',Number(r.locationId)):s.match('stock_locations',r.Location))||(!r.Location&&ing.default_stock_location_id?{id:ing.default_stock_location_id}:null);if(!loc)throw Error('Choose an existing stock location');required(r.Supplier,'Supplier');const key=JSON.stringify([s.normalize(r.Supplier),r['Invoice Date'],r['Invoice Number']||'']);if(!invoices.has(key))invoices.set(key,{requestId:requestId+'-'+invoices.size,supplierName:r.Supplier,supplierId:r.supplierId,date:r['Invoice Date'],invoiceNo:r['Invoice Number'],notes:r.Notes,items:[]});invoices.get(key).items.push({ingredientId:ing.id,brand:r.Brand,quantity:number(r.Quantity),unit:required(r.Unit),price:required(String(r['Unit Price']??''),'Unit purchase price'),locationId:loc.id,expiresOn:r.Expiry,batchNumber:r.Batch,conversionToBase:r['Pieces Per Carton']});result.push({material:ing.name_ar});}
 }catch(e){e.row=index+1;throw e}}
 for(const invoice of invoices.values())s.purchase(invoice,user);return {rows:result.length,invoices:invoices.size};
}
function handle(type,action,b,user){if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>500)throw Error('Choose a file containing 1 to 500 rows');
 if(action==='commit')return s.once('import:'+type,b,()=>execute(type,b.rows,user,b.requestId));
 const preview=[];for(let i=0;i<b.rows.length;i++){const rollback={};try{transaction(()=>{execute(type,[b.rows[i]],user,'preview-request-'+i);throw rollback})}catch(e){preview.push({row:i+1,valid:e===rollback,error:e===rollback?null:e.message,choices:e.choices,kind:e.kind})}}
 return {rows:preview,valid:preview.filter(r=>r.valid).length,invalid:preview.filter(r=>!r.valid).length,total:preview.length};
}
module.exports={handle};
