const {one,all,run,transaction}=require('./db'),admin=require('./admin'),stock=require('./inventory'),p=require('./permissions'),{number,required}=require('./validation'),crypto=require('node:crypto');
const normalize=value=>String(value||'').normalize('NFKC').trim().toLowerCase().replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/\s+/g,' ');
function match(table,value){const key=normalize(value);if(!key)return null;const rows=all('SELECT * FROM '+table).filter(r=>[r.name,r.name_ar,r.name_en,r.code,r.sku].some(n=>n&&normalize(n)===key));if(rows.length>1){const e=Error('More than one match. Choose the exact item: '+value);e.kind=table;e.choices=rows.map(r=>({id:r.id,name:r.name||r.name_ar,name_en:r.name_en,unit:r.base_unit}));throw e;}return rows[0]||null}
const base=unit=>({kg:'g',L:'ml',g:'g',ml:'ml',pcs:'pcs'})[unit];
function ingredient(id){const row=one('SELECT * FROM ingredients WHERE id=? AND active=1',Number(id));if(!row)throw Error('Material unavailable. Select an active material.');return row}
function location(id){if(id&&!one('SELECT id FROM stock_locations WHERE id=? AND active=1',Number(id)))throw Error('Select an active stock location');return Number(id)||null}
function conversion(ing,unit,carton){if(unit==='carton'&&ing.base_unit==='pcs'){const n=number(carton,'Pieces per carton');if(!Number.isInteger(n))throw Error('Enter a whole number of pieces per carton');return n}if(base(unit)!==ing.base_unit)throw Error('Unit does not match material. Choose '+(ing.display_unit||ing.base_unit));return ['kg','L'].includes(unit)?1000:1}
function material(b,user,id=null){return transaction(()=>{
 const old=id?one('SELECT * FROM ingredients WHERE id=?',Number(id)):null;if(id&&!old)throw Error('Material not found');
 const label=required(b.nameAr??old?.name_ar,'Material name'),duplicate=match('ingredients',label);if(duplicate&&duplicate.id!==Number(id)){if(!id&&duplicate.active)return {id:duplicate.id,reused:true};throw Error('This material already exists. Open the existing material.')}
 const unit=b.unit||old?.display_unit||old?.base_unit;if(!base(unit))throw Error('Choose g, kg, ml, L or pcs');
 if(old&&base(unit)!==old.base_unit&&(one('SELECT 1 FROM ingredient_variants WHERE ingredient_id=?',old.id)||one('SELECT 1 FROM recipe_lines WHERE ingredient_id=?',old.id)))throw Error('This unit is used in stock or recipes. Create a separate material instead.');
 const loc=location(b.defaultLocationId===undefined?old?.default_stock_location_id:b.defaultLocationId),kind=b.materialType||old?.material_type||'purchased';if(!['purchased','prepared'].includes(kind))throw Error('Choose purchased or prepared material');
 const low=b.lowStock===undefined?(old?.low_stock_base||0):number(b.lowStock||0,'Low stock',{zero:true})*(['kg','L'].includes(unit)?1000:1);
 if(!id)id=admin.addIngredient({nameAr:label,nameEn:b.nameEn,baseUnit:base(unit)});
 run('UPDATE ingredients SET name_ar=?,name_en=?,base_unit=?,display_unit=?,default_stock_location_id=?,material_type=?,low_stock_base=?,active=? WHERE id=?',label,b.nameEn??old?.name_en??null,base(unit),unit,loc,kind,low,b.active===undefined?(old?.active??1):b.active?1:0,id);
 p.audit(user,old?'material.update':'material.create','ingredients',id,old,b);return {id};
})}
function materials(user){return all('SELECT i.*,l.name_ar location_ar,l.name_en location_en FROM ingredients i LEFT JOIN stock_locations l ON l.id=i.default_stock_location_id ORDER BY i.name_ar').map(i=>{const cost=one("SELECT m.unit_cost_base FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id WHERE v.ingredient_id=? AND m.movement_type='purchase' AND m.unit_cost_base IS NOT NULL ORDER BY m.created_at DESC,m.id DESC LIMIT 1",i.id);return {...i,quantity_base:one('SELECT COALESCE(SUM(m.quantity_base),0) n FROM stock_movements m JOIN ingredient_variants v ON v.id=m.variant_id WHERE v.ingredient_id=?',i.id).n,...p.can(user,'reports.costs')||p.can(user,'purchases.write')?{last_cost:cost?.unit_cost_base??null}:{}}})}
function variant(ing,unit,brand='',carton){const factor=conversion(ing,unit,carton),key=normalize(brand),rows=all('SELECT * FROM ingredient_variants WHERE ingredient_id=? AND active=1',ing.id);const found=rows.find(v=>normalize(v.brand)===key&&v.purchase_unit===unit&&v.conversion_to_base===factor);if(found)return found;const id=admin.addVariant({ingredientId:ing.id,nameAr:String(brand).trim()||ing.name_ar,nameEn:String(brand).trim()||ing.name_en,brand:String(brand).trim()||null,purchaseUnit:unit,conversionToBase:factor});return one('SELECT * FROM ingredient_variants WHERE id=?',id)}
function supplier(b,user){const label=required(b.name,'Supplier name'),old=match('suppliers',label);if(old){if(!old.active)throw Error('Supplier is archived. Select another supplier.');return {id:old.id,reused:true}}const id=admin.addSupplier({name:label,phone:b.phone,notes:b.notes});p.audit(user,'supplier.create','suppliers',id,null,b);return {id}}
function once(operation,b,fn){return transaction(()=>{const id=required(b.requestId,'Request identifier');if(!/^[\w-]{16,100}$/.test(id))throw Error('Invalid request identifier');const hash=crypto.createHash('sha256').update(JSON.stringify({...b,requestId:undefined})).digest('hex'),old=one('SELECT * FROM ux_requests WHERE request_id=?',id);if(old){if(old.operation!==operation||old.body_hash!==hash)throw Error('This saved request has different values. Start a new entry.');return JSON.parse(old.result)}const result=fn();run('INSERT INTO ux_requests(request_id,operation,body_hash,result) VALUES(?,?,?,?)',id,operation,hash,JSON.stringify(result));return result})}
function purchase(b,user){return once('purchase',b,()=>{
 if(!Array.isArray(b.items)||!b.items.length)throw Error('Add at least one purchase line');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date||'')||!Number.isFinite(Date.parse(b.date)))throw Error('Choose a valid invoice date');
 let supplierId=Number(b.supplierId)||null;if(supplierId&&!one('SELECT id FROM suppliers WHERE id=? AND active=1',supplierId))throw Error('Select an active supplier');if(!supplierId&&b.supplierName)supplierId=supplier({name:b.supplierName},user).id;
 const items=b.items.map(l=>{const ing=ingredient(l.ingredientId),v=variant(ing,l.unit,l.brand,l.conversionToBase),loc=location(l.locationId||ing.default_stock_location_id);if(!loc)throw Error('Choose a stock location for '+ing.name_ar);required(String(l.price??''),'Purchase price');const qty=number(l.quantity,'Quantity'),price=l.priceMode==='total'?number(l.price,'Line total',{zero:true})/qty:number(l.price,'Unit purchase price',{zero:true});return {variantId:v.id,locationId:loc,quantityPurchase:qty,unitPricePurchase:price,batchNumber:l.batchNumber,expiresOn:l.expiresOn}});
 const result=admin.createPurchase({supplierId,invoiceNo:b.invoiceNo,date:b.date,notes:b.notes,items,userId:user.id});p.audit(user,'purchase.create','purchases',result.id,null,{...b,total:result.total});return result;
})}
function inputLines(lines){const used=new Map();return lines.flatMap(l=>{const ing=ingredient(l.ingredientId),loc=location(l.locationId);if(!loc)throw Error('Choose stock location');let qty=number(l.quantity)*conversion(ing,l.unit,l.conversionToBase);const results=[];for(const lot of stock.allocations({ingredientId:ing.id,locationId:loc})){const key=lot.variant_id+':'+lot.location_id+':'+lot.batch_id,available=Math.max(0,lot.qty-(used.get(key)||0)),take=Math.min(qty,available);if(take<=0)continue;const v=stock.variant(lot.variant_id);results.push({variantId:v.id,locationId:loc,quantityPurchase:take/v.conversion_to_base});used.set(key,(used.get(key)||0)+take);qty-=take;if(qty<1e-8)break}if(qty>1e-8){const error=Error('Not enough '+ing.name_ar+' in this location. Transfer stock here first.'),required=number(l.quantity)*conversion(ing,l.unit,l.conversionToBase);error.details={name_ar:ing.name_ar,name_en:ing.name_en,required,available:Math.max(0,required-qty),unit:ing.base_unit};throw error}return results})}
function production(b,user){return once('production',b,()=>{const inputs=inputLines(b.inputs||[]),outputs=(b.outputs||[]).map(l=>{const ing=ingredient(l.ingredientId),v=variant(ing,l.unit,l.brand,l.conversionToBase);return {variantId:v.id,locationId:location(l.locationId),quantityPurchase:number(l.quantity),costShare:l.costShare===''?undefined:Number(l.costShare),batchNumber:l.batchNumber,expiresOn:l.expiresOn}});const id=stock.production({inputs,outputs,note:b.note,userId:user.id});for(const l of b.outputs)run("UPDATE ingredients SET material_type='prepared' WHERE id=?",Number(l.ingredientId));p.audit(user,'production','production',id,null,b);return {id}})}
function transfer(b,user){return once('transfer',b,()=>{const lines=inputLines([{...b,locationId:b.fromLocationId}]),ids=lines.map(l=>stock.transferStock({...l,fromLocationId:l.locationId,toLocationId:Number(b.toLocationId),userId:user.id,note:b.note}));p.audit(user,'stock.transfer','transfer',ids[0],null,b);return {ids}})}
function template(b,user){return transaction(()=>{required(b.name,'Template name');if(!b.inputs?.length||!b.outputs?.length)throw Error('Add materials used and produced');const clean=rows=>rows.map(l=>{const ing=ingredient(l.ingredientId);conversion(ing,l.unit,l.conversionToBase);return {ingredientId:ing.id,unit:l.unit,locationId:location(l.locationId),quantity:l.quantity===''?'':number(l.quantity),costShare:l.costShare,conversionToBase:l.conversionToBase}});const inputs=clean(b.inputs),outputs=clean(b.outputs);const id=Number(run('INSERT INTO production_templates(name,inputs,outputs) VALUES(?,?,?)',b.name,JSON.stringify(inputs),JSON.stringify(outputs)).lastInsertRowid);p.audit(user,'production.template','production_templates',id,null,b);return {id}})}
module.exports={normalize,match,base,conversion,material,materials,supplier,variant,purchase,production,transfer,template,once};
