const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {createStore}=require('./storage');
const validation=require('../public/shared/validation');
if(process.env.DEMO_MODE!=='true')throw Error('The local cloud simulator requires DEMO_MODE=true. Use the hosted Worker for production.');
const pricing=require('../public/shared/pricing');
const {number,money,required}=require('../src/validation');
const PORT=Number(process.env.CLOUD_PORT||5174),HOST=process.env.CLOUD_HOST||'127.0.0.1',SECRET=process.env.SYNC_SECRET||'trackbite-dev-secret';
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
function body(req){return new Promise((resolve,reject)=>{let text='';req.on('data',c=>{text+=c;if(text.length>2e6)reject(new Error('Request too large'))});req.on('end',()=>{try{resolve(JSON.parse(text||'{}'))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function secureEqual(a,b){if(!a||!b)return false;const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
async function start(){const db=await createStore();await db.exec(`CREATE TABLE IF NOT EXISTS state(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS web_orders(id TEXT PRIMARY KEY,sequential_no INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',payload TEXT NOT NULL,total DOUBLE PRECISION NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,imported_at TEXT); CREATE TABLE IF NOT EXISTS sync_events(event_key TEXT PRIMARY KEY,event_type TEXT,payload TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS replica(installation_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(installation_id,entity_type,entity_id)); CREATE TABLE IF NOT EXISTS web_tracking(order_id TEXT PRIMARY KEY,token TEXT NOT NULL UNIQUE,local_order_id TEXT,payment_status TEXT NOT NULL DEFAULT 'due',error TEXT,request_key TEXT UNIQUE);`);
 await db.run("INSERT INTO state(key,value) VALUES('next_web_no','5001') ON CONFLICT(key) DO NOTHING");
 const get=async key=>(await db.one('SELECT value FROM state WHERE key=?',key))?.value;
 const set=(key,value)=>db.run('INSERT INTO state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,value);
 const online=async()=>Date.now()-Date.parse(await get('heartbeat'))<180000;
 const catalog=async()=>JSON.parse(await get('catalog')||'{"categories":[],"products":[],"modifiers":[],"settings":{}}');
 async function api(req,res,u){try{const m=req.method,p=u.pathname;
  if(p.startsWith('/api/sync/')&&!secureEqual(req.headers['x-sync-secret'],SECRET))return json(res,401,{error:'Unauthorized'});
  if(p==='/api/status')return json(res,200,{ok:true,service:'Track Bite Cloud',database:db.kind,heartbeat:await get('heartbeat')||null,restaurantOnline:await online()});
  if(p==='/api/public/menu'){const c=await catalog();return json(res,200,{...c,service:'demo-cloud',online:await online(),restaurant:{name_ar:c.settings?.restaurant_name_ar||'تراك بايت',name_en:c.settings?.restaurant_name_en||'Track Bite'}})}
  if(p==='/api/orders'&&m==='POST'){
   const b=await body(req),c=await catalog();b.items=validation.items(b.items);b.customerPhone=validation.phone(b.customerPhone);required(b.customerName,'Customer name');validation.requestId(b.requestId,true);if(!await online())return json(res,503,{error:'Restaurant is offline; ordering is paused'});
   if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)throw new Error('Order needs 1–100 items');
   const orderType=b.orderType||'pickup';const type=(c.orderTypes||[{code:'pickup',requires_delivery:0},{code:'delivery',requires_delivery:1}]).find(t=>t.code===orderType);if(!type)throw new Error('Invalid order type');if(type.requires_delivery){required(b.customerName,'Customer name');required(b.customerPhone,'Mobile');required(b.deliveryAddress||b.deliveryDetails?.fullAddress||b.deliveryDetails?.street,'Delivery address')}
   const items=b.items.map(it=>{const p=c.products.find(x=>x.id===Number(it.productId));if(!p)throw new Error('Product unavailable');const modifiers=[...new Set((it.modifiers||[]).map(Number))];let price=p.price;for(const id of modifiers){const mod=(c.modifiers||[]).find(x=>x.id===id&&x.product_id===p.id);if(!mod)throw new Error('Modifier unavailable');price+=mod.price}return {productId:p.id,qty:number(it.qty??1),modifiers,notes:String(it.notes||'').slice(0,1000),price}});
   const deliveryFee=type.requires_delivery?Number(c.settings?.delivery_fee||0):0;const priced=pricing.calculate({subtotal:money(items.reduce((s,i)=>s+money(i.price*i.qty),0)),deliveryFee,settings:c.settings});if(b.expectedTotal!==undefined&&(!Number.isFinite(Number(b.expectedTotal))||Math.abs(Number(b.expectedTotal)-priced.total)>0.001))throw new Error('Menu prices changed. Reopen checkout to review the latest total.');const total=priced.total,requestKey=b.requestId?String(b.requestId):crypto.randomUUID();
   const order=await db.transaction(async()=>{const previous=await db.one('SELECT w.*,t.token FROM web_tracking t JOIN web_orders w ON w.id=t.order_id WHERE t.request_key=?',requestKey);if(previous){const old=JSON.parse(previous.payload);if(validation.canonical(old.items)!==validation.canonical(items)||old.customerName!==(b.customerName||null)||old.customerPhone!==(b.customerPhone||null)||old.orderType!==orderType||validation.canonical(old.deliveryDetails||{})!==validation.canonical(b.deliveryDetails||{})||old.notes!==(b.notes||null)||(old.deliveryAddress||null)!==(b.deliveryAddress||null))throw new Error('Request ID already used');return {id:previous.id,sequential_no:previous.sequential_no,total:previous.total,status:previous.status,trackingToken:previous.token}}
    const counter=await db.one("UPDATE state SET value=CAST(CAST(value AS INTEGER)+1 AS TEXT) WHERE key='next_web_no' RETURNING value");const seq=Number(counter.value)-1,id=crypto.randomUUID(),token=crypto.randomBytes(24).toString('hex');const payload={cloudOrderId:id,sequential_no:seq,items,customerName:b.customerName||null,customerPhone:b.customerPhone||null,orderType,deliveryAddress:b.deliveryAddress||null,deliveryDetails:b.deliveryDetails||{},deliveryFee,pricing:priced,notes:b.notes||null,total};await db.run('INSERT INTO web_orders(id,sequential_no,payload,total) VALUES(?,?,?,?)',id,seq,JSON.stringify(payload),total);await db.run('INSERT INTO web_tracking(order_id,token,request_key) VALUES(?,?,?)',id,token,requestKey);return {id,sequential_no:seq,total,status:'pending',trackingToken:token}});return json(res,201,{order});
  }
  const track=p.match(/^\/api\/tracking\/([a-f0-9]+)$/);if(track){const row=await db.one('SELECT w.sequential_no,w.status,w.total,t.payment_status,t.error FROM web_orders w JOIN web_tracking t ON t.order_id=w.id WHERE t.token=?',track[1]);return json(res,row?200:404,row?{order:row}:{error:'Order not found'})}
  if(p==='/api/sync/heartbeat'&&m==='POST'){await set('heartbeat',new Date().toISOString());return json(res,200,{ok:true})}
  if(p==='/api/sync/catalog'&&m==='POST'){await set('catalog',JSON.stringify(await body(req)));return json(res,200,{ok:true})}
  if(p==='/api/sync/orders/pending')return json(res,200,{orders:(await db.all("SELECT id,sequential_no,payload,total FROM web_orders WHERE status='pending' ORDER BY created_at LIMIT 100")).map(r=>({...r,payload:JSON.parse(r.payload)}))});
  const ack=p.match(/^\/api\/sync\/orders\/([^/]+)\/(ack|error)$/);if(ack&&m==='POST'){const b=await body(req);await db.transaction(async()=>{if(ack[2]==='ack'){await db.run("UPDATE web_orders SET status=CASE WHEN status='pending' THEN 'accepted' ELSE status END,imported_at=COALESCE(imported_at,?) WHERE id=?",new Date().toISOString(),ack[1]);await db.run('UPDATE web_tracking SET local_order_id=?,error=NULL,payment_status=? WHERE order_id=?',b.localOrderId,b.paymentStatus||'due',ack[1])}else await db.run('UPDATE web_tracking SET error=? WHERE order_id=?',String(b.error).slice(0,500),ack[1])});return json(res,200,{ok:true})}
  if(p==='/api/sync/events'&&m==='POST'){const b=await body(req);required(b.eventKey,'Event key');await db.transaction(async()=>{if(await db.one('SELECT event_key FROM sync_events WHERE event_key=?',b.eventKey))return;await db.run('INSERT INTO sync_events(event_key,event_type,payload) VALUES(?,?,?)',b.eventKey,b.eventType||null,JSON.stringify(b.payload||{}));if(b.entityType&&b.installationId){if(b.operation==='delete')await db.run('DELETE FROM replica WHERE installation_id=? AND entity_type=? AND entity_id=?',b.installationId,b.entityType,String(b.entityId));else await db.run('INSERT INTO replica(installation_id,entity_type,entity_id,payload) VALUES(?,?,?,?) ON CONFLICT(installation_id,entity_type,entity_id) DO UPDATE SET payload=excluded.payload',b.installationId,b.entityType,String(b.entityId),JSON.stringify(b.payload));if(b.entityType==='orders'){const row=b.payload;await db.run('UPDATE web_orders SET status=? WHERE id IN (SELECT order_id FROM web_tracking WHERE local_order_id=?)',row.status==='refunded'?'cancelled':row.fulfillment_status,row.id);await db.run('UPDATE web_tracking SET payment_status=? WHERE local_order_id=?',row.payment_status,row.id)}}});return json(res,200,{ok:true})}
  if(p==='/api/sync/events')return json(res,200,{rows:await db.all('SELECT * FROM sync_events ORDER BY created_at DESC LIMIT 100')});
  if(p==='/api/owner/report'){if(!secureEqual(req.headers.authorization,'Bearer '+(process.env.CLOUD_ADMIN_TOKEN||''))||!process.env.CLOUD_ADMIN_TOKEN)return json(res,401,{error:'Cloud owner token required'});const rows=await db.all("SELECT payload FROM replica WHERE entity_type='orders'");const orders=rows.map(r=>JSON.parse(r.payload));return json(res,200,{online:await online(),orders,sales:money(orders.filter(o=>o.status==='completed').reduce((s,o)=>s+o.total,0)),events:(await db.one('SELECT COUNT(*) count FROM sync_events')).count})}
  return json(res,404,{error:'Not found'});
 }catch(e){console.error(e);return json(res,400,{error:e.message})}}
 const root=path.join(__dirname,'..','public'),mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
 let requests=Promise.resolve();http.createServer((req,res)=>{let u;try{u=new URL(req.url,'http://localhost')}catch{return json(res,400,{error:'Invalid URL'})}if(u.pathname.startsWith('/api/')){if(db.kind==='sqlite-demo'){requests=requests.then(()=>api(req,res,u)).catch(e=>{console.error(e);if(!res.headersSent)json(res,500,{error:'Request failed'})});return}return api(req,res,u)}let p=u.pathname==='/'?'/customer/':u.pathname;if(p.endsWith('/'))p+='index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()}fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});res.end(d)})}).listen(PORT,HOST,()=>console.log(`Track Bite Cloud http://${HOST}:${PORT}/customer/ (${db.kind})`));
}
start().catch(e=>{console.error(e);process.exit(1)});
