module.exports=async function online({db,req,res,url,body,json}){const match=url.pathname.match(/^\/api\/sync\/orders\/([^/]+)(?:\/(ack|review|reject|error))?$/);
 if(url.pathname==='/api/sync/orders/pending'){const rows=await db.all("SELECT w.*,t.error FROM web_orders w JOIN web_tracking t ON t.order_id=w.id WHERE w.status IN ('pending','awaiting_restaurant_confirmation','needs_review') AND w.sequential_no>? ORDER BY w.sequential_no LIMIT 100",Number(url.searchParams.get('after'))||0);json(res,200,{orders:rows.map(r=>({...r,payload:JSON.parse(r.payload)})),next:rows.length===100?rows.at(-1).sequential_no:null});return true}
 if(!match)return false;const old=await db.one('SELECT w.*,t.local_order_id,t.error FROM web_orders w JOIN web_tracking t ON t.order_id=w.id WHERE w.id=?',match[1]);if(!old){json(res,404,{error:'Order not found'});return true}
 const waiting=['pending','awaiting_restaurant_confirmation','needs_review'];
 if(!match[2]&&req.method==='GET'){json(res,200,{order:{id:old.id,status:old.status,localOrderId:old.local_order_id,rewardValid:!JSON.parse(old.payload).reward}});return true}
 if(req.method!=='POST')return false;const b=await body(req);await db.transaction(async()=>{
  if(match[2]==='ack'){if(!b.localOrderId||old.local_order_id&&old.local_order_id!==b.localOrderId||!old.local_order_id&&!waiting.includes(old.status))throw Error('Order acknowledgement conflict');await db.run("UPDATE web_orders SET status=CASE WHEN status IN ('pending','awaiting_restaurant_confirmation','needs_review') THEN 'confirmed' ELSE status END,imported_at=COALESCE(imported_at,?) WHERE id=?",new Date().toISOString(),old.id);await db.run('UPDATE web_tracking SET local_order_id=?,error=NULL,payment_status=CASE WHEN local_order_id IS NULL THEN ? ELSE payment_status END WHERE order_id=?',b.localOrderId,b.paymentStatus||'due',old.id)}
  else if(match[2]==='reject'){if(old.status==='rejected')return;if(!waiting.includes(old.status)||old.local_order_id)throw Error('Order cannot be rejected');if(!String(b.reason||'').trim())throw Error('Rejection reason required');await db.run("UPDATE web_orders SET status='rejected' WHERE id=?",old.id);await db.run('UPDATE web_tracking SET error=? WHERE order_id=?',String(b.reason).slice(0,500),old.id)}
  else if(waiting.includes(old.status)&&!old.local_order_id){await db.run('UPDATE web_orders SET status=? WHERE id=?',b.status==='awaiting_restaurant_confirmation'?'awaiting_restaurant_confirmation':'needs_review',old.id);await db.run('UPDATE web_tracking SET error=? WHERE order_id=?',b.code||'review',old.id)}
 });json(res,200,{ok:true});return true;
};
