const {one,all,run,transaction}=require('../db');const {number,required}=require('../validation');const permissions=require('../permissions'),service=require('./service'),render=require('./render');
async function handle(req,res,url,user,b,json){const path=url.pathname,method=req.method,done=data=>{json(res,200,data);return true};
 if(path==='/api/printing/devices'){try{const result=await service.powershell(['-Mode','List']);return done({rows:JSON.parse(result.stdout.replace(/^\uFEFF/,''))})}catch(e){return done({rows:[],error:e.message})}}
 if(path==='/api/printing/settings'&&method==='POST'){const before=one('SELECT * FROM printer_settings WHERE id=?',Number(b.id));if(!before)throw new Error('Printer configuration not found');const width=Number(b.paperWidth);if(![58,80].includes(width))throw new Error('Paper width must be 58 or 80');if(!['browser','windows','escpos_tcp'].includes(b.printerType))throw new Error('Invalid printer transport');if(!['ar','en','bilingual'].includes(b.language))throw new Error('Invalid print language');if(!['text','image'].includes(b.renderMode))throw new Error('Invalid rendering mode');const copies=number(b.copies||1);if(!Number.isInteger(copies)||copies>5)throw new Error('Copies must be 1–5');const port=number(b.port||9100);if(!Number.isInteger(port)||port>65535)throw new Error('Invalid printer port');run('UPDATE printer_settings SET device_name=?,printer_type=?,paper_width=?,copies=?,auto_print=?,language=?,render_mode=?,logo=?,drawer=?,host=?,port=?,active=? WHERE id=?',b.deviceName||null,b.printerType,width,copies,b.autoPrint?1:0,b.language,b.renderMode,b.logo?1:0,b.drawer?1:0,b.host||null,port,b.active===false?0:1,before.id);permissions.audit(user,'printer.configure','printer_settings',before.id,before,{...b});return done({ok:true})}
 if(path==='/api/printing/jobs')return done({rows:all(`SELECT q.*,p.name printer_name,p.printer_type FROM print_queue q LEFT JOIN printer_settings p ON p.id=q.printer_id ${url.searchParams.get('order')?'WHERE q.order_id=?':''} ORDER BY q.id DESC LIMIT 200`,...url.searchParams.get('order')?[url.searchParams.get('order')]:[])});
 const job=path.match(/^\/api\/printing\/jobs\/(\d+)\/(preview|retry|confirm)$/);if(job){const row=one('SELECT * FROM print_queue WHERE id=?',Number(job[1]));if(!row)throw new Error('Print job not found');if(job[2]==='preview'){const printer=one('SELECT * FROM printer_settings WHERE id=?',row.printer_id)||{};res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(render.html(row,printer));return true}if(method!=='POST')throw new Error('POST required');if(job[2]==='confirm'){run("UPDATE print_queue SET status='printed',printed_at=CURRENT_TIMESTAMP WHERE id=?",row.id);permissions.audit(user,'print.confirm','print_queue',row.id,row.status,'printed');return done({ok:true})}if(['sent','printed'].includes(row.status))throw new Error('Successful jobs require a marked reprint');if(row.status==='sending')throw new Error('Print is already in progress');run("UPDATE print_queue SET status='pending',reprint=CASE WHEN attempts>0 THEN 1 ELSE reprint END WHERE id=?",row.id);permissions.audit(user,'print.retry','print_queue',row.id,row.status,'pending',b.reason||null);return done(await service.dispatch(row.id))}
 if(path==='/api/printing/reprint'&&method==='POST'){const archived=one("SELECT payload FROM print_queue WHERE order_id=? AND job_type='customer' AND reprint=0 ORDER BY id DESC LIMIT 1",b.orderId);const o=archived?JSON.parse(archived.payload):require('../orders').getOrder(b.orderId);if(!o)throw new Error('Order not found');const jobs=transaction(()=>{const jobs=service.enqueue(o,{reprint:true,customerOnly:b.type==='customer',kitchenOnly:b.type==='kitchen',station:b.station||null,userId:user.id,reason:b.reason||null});permissions.audit(user,'print.reprint','orders',o.id,null,{jobs,type:b.type,station:b.station},b.reason||null);return jobs});return done({jobs})}
 if(path==='/api/printing/test'&&method==='POST'){const printer=one('SELECT * FROM printer_settings WHERE id=?',Number(b.printerId));if(!printer)throw new Error('Printer not found');const payload={sequential_no:'TEST',created_at:new Date().toISOString(),order_type:'pickup',items:[{quantity:1,product_name_ar:'اختبار الطباعة العربية',product_name_en:'Print test',unit_price:0,line_total:0,modifiers:[],notes:'واضح · Arabic shaping test'}],total:0,payment_status:'paid',payments:[],receiptSettings:{}};const job={job_type:'customer',payload:JSON.stringify(payload),document_kind:'original'};if(printer.printer_type==='browser')return done({html:render.html(job,printer)});await service.send(job,printer);permissions.audit(user,'printer.test','printer_settings',printer.id,null,{sent:true});return done({ok:true})}
 return false;
}
module.exports={handle};
