module.exports=function(db){if(db.prepare('SELECT 1 FROM schema_migrations WHERE version=5').get())return;db.exec('BEGIN IMMEDIATE');try{
const add=(t,c,type)=>{if(!db.prepare(`PRAGMA table_info(${t})`).all().some(x=>x.name===c))db.exec(`ALTER TABLE ${t} ADD COLUMN ${c} ${type}`)};
for(const [c,type] of Object.entries({pricing_snapshot:"TEXT NOT NULL DEFAULT '{}'",receipt_settings:"TEXT NOT NULL DEFAULT '{}'",revision:'INTEGER NOT NULL DEFAULT 0'}))add('orders',c,type);
for(const [c,type] of Object.entries({auto_print:'INTEGER NOT NULL DEFAULT 0',copies:'INTEGER NOT NULL DEFAULT 1',language:"TEXT NOT NULL DEFAULT 'ar'",render_mode:"TEXT NOT NULL DEFAULT 'image'",logo:'INTEGER NOT NULL DEFAULT 0',drawer:'INTEGER NOT NULL DEFAULT 0',device_name:'TEXT'}))add('printer_settings',c,type);
for(const [c,type] of Object.entries({printer_id:'INTEGER REFERENCES printer_settings(id)',attempts:'INTEGER NOT NULL DEFAULT 0',last_error:'TEXT',requested_by:'INTEGER REFERENCES users(id)',reason:'TEXT',document_kind:"TEXT NOT NULL DEFAULT 'original'"}))add('print_queue',c,type);
db.exec('CREATE TABLE order_revisions(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),request_id TEXT UNIQUE,payload TEXT NOT NULL,user_id INTEGER REFERENCES users(id),created_at TEXT DEFAULT CURRENT_TIMESTAMP)');
for(const key of ['tax','service','packaging','other'])for(const [suffix,value] of [['enabled','false'],['type','percentage'],['value','0']])db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(key+'_'+suffix,value);
for(const row of [['receipt_footer_ar','شكراً لزيارتكم'],['receipt_footer_en','Thank you for choosing Track Bite'],['restaurant_phone',''],['restaurant_address',''],['restaurant_logo','']])db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(...row);
db.prepare("INSERT OR IGNORE INTO printer_settings(code,name,station_code) VALUES('delivery','Delivery slip','delivery')").run();
for(const table of ['orders','order_revisions']){const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name);for(const op of ['INSERT','UPDATE','DELETE']){const ref=op==='DELETE'?'OLD':'NEW';db.exec(`DROP TRIGGER IF EXISTS outbox_${table}_${op};CREATE TRIGGER outbox_${table}_${op} AFTER ${op} ON ${table} BEGIN INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('${table}',CAST(${ref}.id AS TEXT),'${op==='DELETE'?'delete':'upsert'}',json_object(${cols.map(c=>`'${c}',${ref}.${c}`).join(',')}),lower(hex(randomblob(16))));END`)}}
db.exec('INSERT INTO schema_migrations(version) VALUES(5);COMMIT');}catch(e){db.exec('ROLLBACK');throw e}};
