const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function document(job,printer={}){const o=typeof job.payload==='string'?JSON.parse(job.payload):job.payload,lang=printer.language||'ar',bi=lang==='bilingual',t=(ar,en)=>bi?ar+' / '+en:lang==='en'?en:ar,n=(ar,en)=>t(ar||en||'',en||ar||''),lines=[],push=(text,size=12,bold=false)=>lines.push({text:String(text||''),size,bold});const kitchen=job.job_type==='kitchen',delivery=job.job_type==='delivery',settings=o.receiptSettings||{};
 push(n(settings.restaurant_name_ar||'تراك بايت',settings.restaurant_name_en||'TRACK BITE'),18,true);
 if(job.reprint)push('*** '+t('إعادة طباعة','REPRINT')+' ***',18,true);
 const kind={refund:['استرداد كامل','FULL REFUND'],updated:['فاتورة معدلة','UPDATED RECEIPT'],addition:['إضافة','ADDITION'],cancel_item:['إلغاء صنف','CANCEL ITEM'],cancel_order:['إلغاء الطلب','CANCEL ORDER']}[job.document_kind];if(kind)push('*** '+t(...kind)+' ***',20,true);
 push(t('طلب رقم','ORDER')+' #'+o.sequential_no,kitchen?26:19,true);if(kitchen)push(t('تذكرة المطبخ','KITCHEN TICKET')+' · '+(job.station_code||''),14,true);
 push(o.created_at||new Date().toISOString(),11);push(n(o.orderType?.name_ar||o.order_type,o.orderType?.name_en||o.order_type),15,true);
 if(o.cashier)push(t('الكاشير: ','Cashier: ')+n(o.cashier.display_name_ar,o.cashier.display_name_en),11);
 const separator='--------------------------------';push(separator,10);
 if(!delivery)for(const i of o.items||[]){push(`${i.quantity} × ${n(i.product_name_ar,i.product_name_en)}`,kitchen?19:13,true);if(!kitchen)push(t('سعر الوحدة','Unit price')+`: ${Number(i.unit_price).toFixed(2)}   |   ${Number(i.line_total).toFixed(2)} EGP`,11);for(const m of i.modifiers||[])push((kitchen?'*** ':'+ ')+n(m.name_ar,m.name_en)+(kitchen?' ***':m.price?` (${Number(m.price).toFixed(2)})`:''),kitchen?15:11,kitchen);if(i.notes)push((kitchen?'*** ':'')+i.notes+(kitchen?' ***':''),kitchen?16:11,true);push(separator,10)}
 if(o.notes){push(t('ملاحظات الطلب','ORDER NOTE'),kitchen?17:12,true);push(o.notes,kitchen?17:12,true)}
 if(!kitchen){const details=o.delivery_details||{};if(o.customer_name)push(t('العميل: ','Customer: ')+o.customer_name,13,true);if(o.customer_phone)push(t('الهاتف: ','Mobile: ')+o.customer_phone);const labels={alternativePhone:['هاتف آخر','Alternative phone'],area:['المنطقة','Area'],street:['الشارع','Street'],building:['المبنى','Building'],floor:['الدور','Floor'],apartment:['الشقة','Apartment'],landmark:['علامة مميزة','Landmark'],fullAddress:['العنوان','Address'],deliveryNotes:['ملاحظات التوصيل','Delivery notes']};for(const [key,label] of Object.entries(labels))if(details[key])push(t(...label)+': '+details[key],12,key==='deliveryNotes');if(o.delivery_address&&o.delivery_address!==details.fullAddress)push(o.delivery_address);push(separator,10);const priced=(o.pricing&&Object.keys(o.pricing).length?o.pricing:null)||{subtotal:o.subtotal,discount:o.discount,total:o.total,delivery:o.delivery_fee||0};if(!delivery)for(const [key,ar,en] of [['subtotal','المجموع الفرعي','Subtotal'],['discount','الخصم','Discount'],['service','الخدمة','Service'],['tax','الضريبة','Tax'],['packaging','التغليف','Packaging'],['other','رسوم أخرى','Other charges'],['delivery','التوصيل','Delivery']])push(t(ar,en)+'  '+Number(priced[key]||0).toFixed(2));push(t('الإجمالي','TOTAL')+'  '+Number(o.total||0).toFixed(2)+' EGP',20,true);push(t('المبلغ المستحق','Amount due')+'  '+(o.payment_status==='due'?Number(o.total).toFixed(2):'0.00')+' EGP',14,true);for(const p of o.payments||[])push(n(p.name_ar,p.name_en)+'  '+Number(p.amount).toFixed(2)+(p.reference?' · '+p.reference:''));if(!delivery){if(settings.restaurant_phone)push(settings.restaurant_phone);if(settings.restaurant_address)push(settings.restaurant_address);push(n(settings.receipt_footer_ar||'شكراً لزيارتكم',settings.receipt_footer_en||'Thank you'),12,true)}}
 return {lines,width:Number(printer.paper_width)||80,language:lang,kitchen,logo:printer.logo?settings.restaurant_logo:null};
}
function html(job,printer){const d=document(job,printer);return `<!doctype html><html lang="${d.language==='en'?'en':'ar'}" dir="${d.language==='en'?'ltr':'rtl'}"><head><meta charset="utf-8"><title>Track Bite #${esc(JSON.parse(job.payload).sequential_no)}</title><style>@page{size:${d.width}mm auto;margin:2mm}body{font-family:Tahoma,Arial,sans-serif;color:#000;background:#fff;width:${d.width-8}mm;margin:3mm auto}p{margin:4px 0;overflow-wrap:anywhere;white-space:pre-wrap;line-height:1.35}button{padding:12px;margin:10px}img{max-width:45mm;max-height:25mm;display:block;margin:auto}@media print{button{display:none}body{margin:0}}</style></head><body>${d.logo?`<img src="${esc(d.logo)}" alt="Track Bite">`:''}${d.lines.map(l=>`<p style="font-size:${l.size}pt;font-weight:${l.bold?'bold':'normal'}">${esc(l.text)}</p>`).join('')}<button onclick="window.print()">طباعة / Print</button></body></html>`}
function textBytes(job,printer){const d=document(job,printer);if(d.lines.some(l=>/[^\x00-\x7F]/.test(l.text.replace(/×/g,'x'))))throw new Error('Native text mode supports English ASCII here; select rendered image for Arabic or bilingual');const bytes=[Buffer.from([27,64])];for(const l of d.lines){bytes.push(Buffer.from([27,69,l.bold?1:0,29,33,l.size>=18?17:0]),Buffer.from(l.text.replace(/×/g,'x')+'\n','ascii'))}bytes.push(Buffer.from([29,33,0,10,10,10,29,86,0]));return Buffer.concat(bytes)}
module.exports={document,html,textBytes};
