const {all,one,run,transaction}=require('../db');
const path=require('path'),fs=require('fs'),crypto=require('crypto'),net=require('net');
const {execFile}=require('child_process'),{promisify}=require('util');const execute=promisify(execFile);
const render=require('./render');let busy=false,timer;
function enqueue(order,{reprint=false,kind='original',kitchenOnly=false,customerOnly=false,station=null,userId=null,reason=null}={}){const jobs=[];const add=(type,stationCode,items)=>{const printer=one('SELECT * FROM printer_settings WHERE active=1 AND code=?',type==='customer'?'customer':type==='delivery'?'delivery':stationCode)||one('SELECT * FROM printer_settings WHERE active=1 AND station_code=?',stationCode);const result=run('INSERT INTO print_queue(order_id,job_type,station_code,payload,reprint,printer_id,requested_by,reason,document_kind) VALUES(?,?,?,?,?,?,?,?,?)',order.id,type,stationCode,JSON.stringify({...order,items}),reprint?1:0,printer?.id||null,userId,reason,kind);jobs.push(Number(result.lastInsertRowid))};if(!kitchenOnly&&!station)add('customer',null,order.items);if(!customerOnly)for(const code of new Set(order.items.map(i=>i.station_code||'kitchen')))if(!station||station===code)add('kitchen',code,order.items.filter(i=>(i.station_code||'kitchen')===code));if(!kitchenOnly&&!customerOnly&&!station&&order.order_type==='delivery')add('delivery','delivery',order.items);return jobs}
async function powershell(args){return execute('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(__dirname,'windows.ps1'),...args],{windowsHide:true,timeout:30000,maxBuffer:1024*1024})}
async function send(job,printer){if(printer.printer_type==='browser')throw new Error('Use browser preview and print for this printer');const dir=path.join(path.dirname(require('../db').dbPath),'print-spool');fs.mkdirSync(dir,{recursive:true});const basename=path.join(dir,crypto.randomUUID()),jsonFile=basename+'.json',rawFile=basename+'.bin';const doc=render.document(job,printer);const order=typeof job.payload==='string'?JSON.parse(job.payload):job.payload;doc.device=printer.device_name||printer.name;doc.copies=printer.copies||1;doc.drawer=!!printer.drawer&&job.job_type==='customer'&&!job.reprint&&(order.payments||[]).some(p=>p.code==='cash'&&p.amount>0);try{
 if(printer.render_mode==='text'){let bytes=render.textBytes(job,printer);if(doc.drawer)bytes=Buffer.concat([bytes,Buffer.from([27,112,0,25,250])]);fs.writeFileSync(rawFile,bytes)}else{fs.writeFileSync(jsonFile,JSON.stringify(doc));await powershell(['-InputFile',jsonFile,'-OutputFile',rawFile,'-Mode','Raster'])}
 if(printer.printer_type==='escpos_tcp'){if(!printer.host)throw new Error('Printer IP address is required');const bytes=fs.readFileSync(rawFile);for(let n=0;n<(printer.copies||1);n++)await new Promise((resolve,reject)=>{const socket=net.createConnection({host:printer.host,port:printer.port||9100});socket.setTimeout(5000);socket.once('timeout',()=>socket.destroy(new Error('Printer timeout')));socket.once('error',reject);socket.once('connect',()=>socket.end(bytes));socket.once('close',hadError=>{if(!hadError)resolve()})})}
 else if(printer.printer_type==='windows'){fs.writeFileSync(jsonFile,JSON.stringify(doc));await powershell(['-InputFile',jsonFile,'-OutputFile',rawFile,'-Mode',printer.render_mode==='text'?'Raw':'Windows'])}
 else throw new Error('Unsupported printer transport');
 }finally{for(const f of [jsonFile,rawFile])try{fs.unlinkSync(f)}catch{}}}
async function dispatch(id){const job=one('SELECT * FROM print_queue WHERE id=?',id);if(!job||!['pending','failed'].includes(job.status))throw new Error('Job is not awaiting print');const printer=one('SELECT * FROM printer_settings WHERE id=? AND active=1',job.printer_id);if(!printer)throw new Error('Assign an active printer first');run("UPDATE print_queue SET status='sending',attempts=attempts+1,last_error=NULL WHERE id=?",id);try{await send(job,printer);run("UPDATE print_queue SET status='sent',printed_at=CURRENT_TIMESTAMP WHERE id=?",id);return {ok:true,status:'sent'}}catch(e){run("UPDATE print_queue SET status='failed',last_error=? WHERE id=?",e.message,id);throw e}}
async function tick(){if(busy)return;busy=true;try{const jobs=all("SELECT q.id FROM print_queue q JOIN printer_settings p ON p.id=q.printer_id WHERE q.status='pending' AND p.auto_print=1 AND p.active=1 AND p.printer_type!='browser' ORDER BY q.id LIMIT 20");for(const job of jobs)try{await dispatch(job.id)}catch{}}finally{busy=false}}
function start(){if(timer)return;for(const job of all('SELECT * FROM print_queue')){let payload;try{payload=JSON.parse(job.payload)}catch{}if(!payload?.items){const order=require('../orders').getOrder(job.order_id);if(order){if(job.job_type==='kitchen')order.items=order.items.filter(i=>i.station_code===job.station_code);run('UPDATE print_queue SET payload=? WHERE id=?',JSON.stringify(order),job.id)}}}run("UPDATE print_queue SET status='failed',last_error='Interrupted while sending; verify printer before retry' WHERE status='sending'");timer=setInterval(tick,1500);timer.unref()}
module.exports={enqueue,dispatch,start,send,powershell};
