const fs=require('node:fs'),path=require('node:path'),{DatabaseSync}=require('node:sqlite');
const root=path.resolve(__dirname,'..');
(async()=>{const file=path.join(root,'.runtime/public-cloud.json'),config=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'')):null;
 const local=await fetch('http://127.0.0.1:4173/api/status',{signal:AbortSignal.timeout(5000)}).then(r=>r.json());const origin=config?.cloudUrl?.replace(/\/$/,'')||'http://127.0.0.1:5174';
 const db=new DatabaseSync(path.join(root,'trackbite-system/data/trackbite.db'),{readOnly:true});let installation,counts;try{installation=db.prepare("SELECT value FROM settings WHERE key='installation_id'").get().value;const inbox=!!db.prepare("SELECT name FROM sqlite_master WHERE name='online_order_inbox'").get();counts={incoming:inbox?db.prepare("SELECT COUNT(*) n FROM online_order_inbox WHERE status='awaiting_restaurant_confirmation'").get().n:'upgrade needed',review:inbox?db.prepare("SELECT COUNT(*) n FROM online_order_inbox WHERE status='needs_review'").get().n:'upgrade needed',decisions:inbox?db.prepare('SELECT COUNT(*) n FROM online_order_inbox WHERE decision_pending=1').get().n:'upgrade needed',pending:db.prepare("SELECT COUNT(*) n FROM sync_queue WHERE status IN ('pending','retrying')").get().n,failed:db.prepare("SELECT COUNT(*) n FROM sync_queue WHERE status='dead-letter'").get().n}}finally{db.close()}
 console.log('POS: '+(local.ok?'Running':'NOT READY'));console.log('Mode: '+(local.sync.environment||'Unknown / upgrade needed'));console.log('Actual cloud: '+(local.sync.cloudOrigin||'Unknown'));console.log('Configured cloud: '+origin);console.log('Origin matched: '+(local.sync.cloudOrigin===origin));console.log('Installation: ...'+installation.slice(-4));
 const cloud=await fetch(origin+'/api/status',{signal:AbortSignal.timeout(15000)}).then(r=>r.json());console.log('Cloud heartbeat: '+(cloud.heartbeat||'Missing'));console.log('Restaurant online: '+cloud.restaurantOnline);
 if(config){const r=await fetch(origin+'/api/sync/diagnostics',{headers:{'x-sync-secret':config.syncSecret,'x-installation-id':installation},signal:AbortSignal.timeout(15000)});const remote=await r.json();console.log('Pairing verified: '+(r.ok&&remote.installationId===installation&&(!config.installationId||config.installationId===installation)));console.log('Cloud incoming / review: '+remote.incoming+' / '+remote.review);
  const access=path.join(root,'.runtime/access/production-logins.json');if(fs.existsSync(access)){const owner=JSON.parse(fs.readFileSync(access,'utf8').replace(/^\uFEFF/,'')).credentials.find(c=>c.role==='owner');const login=await fetch('http://127.0.0.1:4173/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:owner.username,password:owner.password})}).then(r=>r.json());if(login.token){try{const s=await fetch('http://127.0.0.1:4173/api/sync/status',{headers:{authorization:'Bearer '+login.token}}).then(r=>r.json());console.log('Catalog matched: '+(s.status.localCatalogRevision===remote.catalogRevision&&s.status.localCatalogRevision===s.status.cloudCatalogRevision));console.log('Last successful sync: '+s.status.lastSuccess);console.log('Last sync error: '+(s.status.lastError||'None'))}finally{await fetch('http://127.0.0.1:4173/api/logout',{method:'POST',headers:{authorization:'Bearer '+login.token}})}}else console.log('Detailed local diagnostics: sign in as Owner in POS Sync Settings')}
 }
 console.log('Incoming Website Orders: '+counts.incoming);console.log('Needs Review: '+counts.review);console.log('Decisions awaiting website: '+counts.decisions);console.log('Sync queue: '+counts.pending+' pending / '+counts.failed+' failed');
})().catch(e=>{console.error('Health check incomplete: '+e.message);console.error('Open POS Settings > Backup & sync for details.');process.exitCode=1});
