const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const f=await require('./fixture.cjs')();let browser;try{
 browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});const errors=[],checks=[];
 const watch=page=>{page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})};
 const context=await browser.newContext(),page=await context.newPage();watch(page);await page.goto(f.cloudUrl+'/customer/');await page.locator('.product').first().waitFor();assert.equal(await page.locator('.product').count(),4);await page.locator('#webLanguage').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');
 await page.locator('[data-action=profile]').first().click();await page.locator('#switchAccount').click();await page.locator('#dialog [name=name]').fill('Browser Account');await page.locator('#dialog [name=phone]').fill('01055555555');await page.locator('#dialog [name=password]').fill('Browser-Password-123!');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('[data-action=profile]').first().click();await page.locator('#accountAddresses').click();await page.locator('#dialog [name=label]').fill('Home');await page.locator('#dialog [name=fullAddress]').fill('Isolated browser address');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('#webSearch').fill('Classic');assert.equal(await page.locator('.product').count(),1);await page.locator('[data-favorite]').first().click();await page.locator('[data-product]').first().click();await page.locator('#dialog [name=notes]').fill('Sauce aside');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});await page.locator('#checkout').click();await page.locator('#checkoutNext').click();await page.locator('#checkoutNext').click();await page.locator('#checkoutNext').click();await page.locator('.success-copy').waitFor();await page.locator('#dialog button[type=submit]').click();checks.push('customer signup, account address, search, favourite, customization, notes, pickup checkout');
 const second=await browser.newContext({viewport:{width:390,height:844}}),mobile=await second.newPage();watch(mobile);await mobile.goto(f.cloudUrl+'/customer/');await mobile.locator('.product').first().waitFor();assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth),390);await mobile.locator('[data-action=profile]').first().click();await mobile.locator('#dialog [name=phone]').fill('01055555555');await mobile.locator('#dialog [name=password]').fill('Browser-Password-123!');await mobile.locator('#dialog button[type=submit]').click();await mobile.locator('#dialog').waitFor({state:'hidden'});await mobile.locator('[data-action=profile]').first().click();await mobile.locator('#accountOrders').click();await mobile.locator('.history-card').first().waitFor();assert.equal(await mobile.locator('.history-card').count(),1);await mobile.locator('[data-reorder]').first().click();await mobile.locator('#webCart .cart-line').first().waitFor();await mobile.locator('[data-change][data-delta="1"]').first().click();assert.equal(await mobile.locator('#webCart .qty span').first().innerText(),'2');await mobile.locator('[data-change][data-delta="-1"]').first().click();checks.push('mobile cross-device login, backend history, reorder, layout');
 for(const role of ['owner','manager','accountant','cashier','store','kitchen']){const staff=await browser.newPage();watch(staff);await staff.goto(f.localUrl+'/pos/');await staff.locator('[name=username]').fill(role);await staff.locator('[name=password]').fill('1234');await staff.locator('#loginSubmit').click();await staff.locator('#workspace').waitFor({state:'visible'});if(role==='kitchen')assert.equal(await staff.locator('[data-view=customers]').count(),0);const nav=await staff.locator('#nav [data-view]').evaluateAll(es=>es.map(e=>e.dataset.view));for(const id of nav){await staff.locator('[data-view='+id+']').click();await staff.waitForTimeout(100)}if(role==='owner'){await staff.locator('[data-settings=users]').click();await staff.locator('#permissions').waitFor();await staff.locator('[data-settings=loyalty]').click();await staff.locator('#loyaltySettings').waitFor();await staff.locator('[data-settings=consumption]').click();await staff.locator('#consumptionForm').waitFor();await require('./staff-browser.cjs')(staff,f)}await staff.close()}checks.push('open shift, attach customer, split payment, print preview, order progression, receive, transfer, waste, production, stocktake, recipe editing, reports, close shift');checks.push('all six staff role logins and navigation, owner user controls, loyalty and stock location settings');
 await require('./remote-browser.cjs')(browser,f,watch);checks.push('remote owner login, price change, recipe creation and publication, reward creation');
 await mobile.locator('#closeCart').click();await mobile.locator('[data-action=profile]').first().click();await mobile.locator('[data-reward]').first().waitFor();assert((await mobile.locator('#dialog').innerText()).includes('15'));await mobile.locator('#accountLogout').click();await mobile.locator('#dialog').waitFor({state:'hidden'});await mobile.locator('[data-action=profile]').first().click();await mobile.locator('#switchAccount').waitFor();await mobile.locator('#dialogClose').click();checks.push('account points and reward display, logout');
 await page.reload();await page.locator('.product').first().waitFor();await page.locator('[data-method=delivery]').click();await page.locator('[data-product="4"]').first().click();await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});await page.locator('#checkout').click();await page.locator('#dialog [name=fullAddress]').fill('Browser delivery test address');await page.locator('#checkoutNext').click();await page.locator('#checkoutNext').click();await page.locator('#checkoutNext').click();await page.locator('.success-copy').waitFor();await page.locator('#dialog button[type=submit]').click();await page.locator('#tracking').waitFor();checks.push('delivery checkout and tracking');
 await mobile.screenshot({path:path.join(f.dir,'mobile.png'),fullPage:true});await page.screenshot({path:path.join(f.dir,'desktop.png'),fullPage:true});
 assert.deepEqual(errors,[]);checks.push('zero unexpected browser errors');console.log(JSON.stringify({ok:true,checks},null,2));
 }finally{await browser?.close();await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
