const assert=require('node:assert/strict'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite');
(async()=>{const f=await require('./fixture.cjs')();try{
 const request=async(route,b,cookie,method)=>{const r=await fetch(f.cloudUrl+route,{method:method||(b===undefined?'GET':'POST'),headers:{origin:f.cloudUrl,'content-type':'application/json',...(cookie?{cookie}:{})},body:b===undefined?undefined:JSON.stringify(b)}),d=await r.json();assert(r.ok,route+': '+JSON.stringify(d));return {...d,cookie:r.headers.get('set-cookie')?.split(';')[0]}};
 const account=await request('/api/account/signup',{name:'Connected Test',phone:'01088888888',password:'Private-Test-Password-789'});
 const placed=(await request('/api/orders',{requestId:crypto.randomUUID(),items:[{productId:1,qty:1}],customerName:'Connected Test',customerPhone:'01088888888',orderType:'pickup',expectedTotal:150},account.cookie)).order;
 const order=await f.until(async()=>{const d=await f.pos('/api/orders');return d.orders.find(o=>o.request_id===placed.id)});assert.equal(order.customer_id,account.customer.id);
 await f.pos('/api/shifts/open',{openingCash:1000});await f.pos('/api/orders/'+order.id+'/collect',{payments:[{methodId:1,amount:150}]});for(const status of ['preparing','ready','fulfilled'])await f.pos('/api/orders/'+order.id+'/fulfill',{status});
 await f.until(async()=>(await request('/api/account/loyalty',undefined,account.cookie)).balance===15);
 await f.pos('/api/orders/'+order.id+'/refund',{reason:'Isolated test reversal',restock:true});await f.until(async()=>(await request('/api/account/loyalty',undefined,account.cookie)).balance===0);
 f.setCloudAvailable(false);await f.until(async()=>(await f.pos('/api/status')).sync.online===false);const offlineIds=[];
 for(let i=0;i<2;i++){const input={requestId:crypto.randomUUID(),customerId:account.customer.id,items:[{productId:4,qty:1}],payments:[{methodId:1,amount:35}]};const local=(await f.pos('/api/orders',input)).order;offlineIds.push(local.id);assert.equal((await f.pos('/api/orders',input)).order.id,local.id);for(const status of ['preparing','ready','fulfilled'])await f.pos('/api/orders/'+local.id+'/fulfill',{status});const jobs=await f.pos('/api/printing/jobs?order='+local.id);assert(jobs.rows.some(j=>j.job_type==='customer'))}
 f.setCloudAvailable(true);await f.until(async()=>(await request('/api/account/loyalty',undefined,account.cookie)).balance===6);assert.equal((await request('/api/account/orders',undefined,account.cookie)).orders.length,3);
 const reward=(await f.pos('/api/loyalty/rewards',{name_ar:'مشروب مجاني',name_en:'Free drink',points_cost:5,type:'product',product_id:4,active:true})).reward;
 await f.until(async()=>(await request('/api/public/menu')).loyaltyRewards.some(r=>r.id===reward.id));
 const inventoryBefore=(await f.pos('/api/inventory/summary')).summary.find(r=>r.ingredient_id===7).quantity_base;
 const free=(await f.pos('/api/orders',{requestId:crypto.randomUUID(),customerId:account.customer.id,rewardId:reward.id,items:[{productId:4,qty:1}],payments:[]})).order;assert.equal(free.total,0);assert.equal((await f.pos('/api/inventory/summary')).summary.find(r=>r.ingredient_id===7).quantity_base,inventoryBefore-1);
 await f.until(async()=>(await request('/api/account/loyalty',undefined,account.cookie)).balance===1);assert.equal((await f.pos('/api/loyalty/customer?id='+account.customer.id)).points,1);await f.pos('/api/orders/'+free.id+'/refund',{reason:'Test free item reversal',restock:true});await f.until(async()=>(await request('/api/account/loyalty',undefined,account.cookie)).balance===6);
 await assert.rejects(()=>f.pos('/api/orders',{requestId:crypto.randomUUID(),customerId:account.customer.id,rewardId:reward.id,items:[{productId:4,qty:1}],payments:[{methodId:1,amount:35}]}),/Payments must equal/);assert.equal((await request('/api/account/loyalty',undefined,account.cookie)).balance,6);
 const localCustomer=(await f.pos('/api/customers?q='+account.customer.member_code)).rows[0];assert.equal(localCustomer.id,account.customer.id);
 await f.pos('/api/admin/users/1',{password:'Owner-Remote-Password-987',remoteAccessEnabled:true},'PATCH');const login=await fetch(f.localUrl+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'owner',password:'Owner-Remote-Password-987'})}).then(r=>r.json());f.setToken(login.token);
 const remote=await f.until(()=>request('/api/remote/login',{username:'owner',password:'Owner-Remote-Password-987'}));
 const current=await request('/api/remote/bootstrap',undefined,remote.cookie);await f.stopLocal();
 const command=await request('/api/remote/commands',{version:1,operation:'menu.price',expectedRevision:current.catalog.revision,payload:{id:1,price:165,availableOnline:true}},remote.cookie);assert.equal(command.status,'Pending');assert.equal((await request('/api/remote/bootstrap',undefined,remote.cookie)).commands.find(c=>c.id===command.id).status,'Pending');
 await f.startLocal();await f.until(async()=>(await request('/api/remote/bootstrap',undefined,remote.cookie)).commands.find(c=>c.id===command.id).status==='Applied');await f.until(async()=>(await request('/api/public/menu')).products.find(p=>p.id===1).price===165);
 const db=new DatabaseSync(f.database);try{assert.equal(db.prepare('SELECT COUNT(*) n FROM command_receipts WHERE id=?').get(command.id).n,1);
 const poison=crypto.randomUUID(),safe=crypto.randomUUID();db.prepare("INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('orders',?,'upsert','not JSON',?)").run('poison',poison);db.prepare("INSERT INTO sync_queue(entity_type,entity_id,operation,payload,event_key) VALUES('orders',?,'upsert',?,?)").run('safe',JSON.stringify({id:'safe',fulfillment_status:'accepted',payment_status:'due'}),safe);await f.until(()=>db.prepare("SELECT 1 FROM sync_queue WHERE event_key=? AND status='dead-letter'").get(poison));await f.until(()=>db.prepare("SELECT 1 FROM sync_queue WHERE event_key=? AND status='synced'").get(safe));
 }finally{db.close()}
 const item=(await f.pos('/api/menu/item',{nameAr:'صنف اختبار',nameEn:'Test publish',categoryId:1,stationId:1,price:55,active:true,inStock:true,availableOnline:true,lines:[{ingredientId:2,quantity:1,unit:'pcs'}]})).id;
 await f.until(async()=>(await request('/api/public/menu')).products.some(p=>p.id===item&&p.price===55));await f.pos('/api/admin/products/'+item,{price:65,reason:'Test update'},'PATCH');await f.until(async()=>(await request('/api/public/menu')).products.some(p=>p.id===item&&p.price===65));await f.pos('/api/menu/item?id='+item+'&reason=Isolated-test',{},'DELETE');await f.until(async()=>!(await request('/api/public/menu')).products.some(p=>p.id===item));
 console.log(JSON.stringify({ok:true,checks:['authenticated website order carries stable UUID into POS','paid fulfilled earns exactly once through cloud outbox','refund points reversal reaches customer account','POS member-code lookup','online POS free reward consumes inventory','reward refund restores points','failed POS sale releases cloud reservation','offline sales, kitchen progression and print jobs continue','offline loyalty synchronizes exactly once','explicit remote owner enrollment','remote command remains pending offline','persistent local session survives restart','remote command applies once and publishes price','poison event does not block unrelated event','new menu recipe publishes','price revision publishes','disabled product removed']},null,2));
 }finally{await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
