const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),{DatabaseSync}=require('node:sqlite'),{Miniflare}=require('miniflare');
const root=path.resolve(__dirname,'../..');fs.mkdirSync(path.join(root,'.runtime'),{recursive:true});const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){let last;for(let i=0;i<160;i++){try{const v=await fn();if(v)return v}catch(e){last=e}await pause(100)}throw last||Error('Fixture timed out')}
module.exports=async function fixture(){const dir=fs.mkdtempSync(path.join(root,'.runtime','e2e-')),localUrl='http://127.0.0.1:4195',cloudUrl='http://localhost:5195',secret='test-only-secret-'+require('node:crypto').randomBytes(32).toString('hex');let local,mf,bridge,logs='',cloudAvailable=true;const database=path.join(dir,'pos.db');
 const start=()=>{local=spawn(process.execPath,['server.js'],{cwd:path.join(root,'trackbite-system'),env:{...process.env,DEMO_MODE:'true',PORT:'4195',TRACKBITE_DB:database,CLOUD_API_URL:cloudUrl,SYNC_SECRET:secret,SYNC_INTERVAL_MS:'200'},stdio:['ignore','pipe','pipe']});local.stderr.on('data',d=>logs+=d)};start();
 try{await until(async()=>{if(local.exitCode!==null)throw Error(logs);return (await fetch(localUrl+'/api/status')).ok});const db=new DatabaseSync(database,{readOnly:true}),installation=db.prepare("SELECT value FROM settings WHERE key='installation_id'").get().value;db.close();
 mf=new Miniflare({modules:true,scriptPath:path.join(root,'dist/server/index.mjs'),compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],bindings:{SYNC_SECRET:secret,INSTALLATION_ID:installation},d1Databases:['DB'],d1Persist:path.join(dir,'d1'),serviceBindings:{ASSETS:async request=>{const url=new URL(request.url);let relative=decodeURIComponent(url.pathname);if(relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,'trackbite-system/public','.'+relative),publicDir=path.join(root,'trackbite-system/public');if(!file.startsWith(publicDir+path.sep)||!fs.existsSync(file))return new Response('Missing asset',{status:404});return new Response(fs.readFileSync(file),{headers:{'content-type':({'.js':'text/javascript','.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream'}})}}});await mf.ready;
 bridge=http.createServer(async(req,res)=>{try{if(!cloudAvailable){res.writeHead(503,{'content-type':'application/json'});res.end(JSON.stringify({error:'Isolated outage'}));return}const chunks=[];for await(const c of req)chunks.push(c);const data=Buffer.concat(chunks),r=await mf.dispatchFetch(cloudUrl+req.url,{method:req.method,headers:req.headers,body:data.length?data:undefined});res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()))}catch(e){res.writeHead(500);res.end(e.message)}});await new Promise(r=>bridge.listen(5195,r));await until(async()=>{const m=await fetch(cloudUrl+'/api/public/menu').then(r=>r.json());return m.products?.length===4&&m.online});
 let token=(await fetch(localUrl+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'owner',password:'1234'})}).then(r=>r.json())).token;
 const pos=async(url,b,method)=>{const r=await fetch(localUrl+url,{method:method||(b===undefined?'GET':'POST'),headers:{'content-type':'application/json',authorization:'Bearer '+token},body:b===undefined?undefined:JSON.stringify(b)}),d=await r.json();if(!r.ok)throw Error(url+': '+d.error);return d};
 return {setCloudAvailable:value=>cloudAvailable=value,dir,database,localUrl,cloudUrl,secret,installation,mf,until,pos,setToken:t=>token=t,stopLocal:async()=>{if(local){await new Promise(r=>{local.once('exit',r);local.kill()});local=null}},startLocal:async()=>{start();await until(async()=>(await fetch(localUrl+'/api/status')).ok)},close:async()=>{if(local)await new Promise(r=>{local.once('exit',r);local.kill()});if(bridge)await new Promise(r=>bridge.close(r));await mf?.dispose();if(path.resolve(dir).startsWith(path.join(root,'.runtime')+path.sep))fs.rmSync(dir,{recursive:true,force:true})}};
 }catch(e){if(local)local.kill();await mf?.dispose();throw Error(e.message+' '+logs)}
};
