const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const f=await require('./fixture.cjs')();let browser;try{
 browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});const errors=[],checks=[];
 const watch=page=>{page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})};
 async function staff(role){const p=await browser.newPage();watch(p);await p.goto(f.localUrl+'/pos/');await p.evaluate(()=>localStorage.setItem('tb_lang','en'));await p.reload();await p.locator('[name=username]').fill(role);await p.locator('[name=password]').fill('1234');await p.locator('#loginSubmit').click();await p.locator('#workspace').waitFor({state:'visible'});await p.locator('[data-view=orders]').click();await p.locator('#incomingMode').waitFor();return p}
 const owner=await staff('owner'),kitchen=await staff('kitchen'),customer=await browser.newPage({viewport:{width:390,height:844}});watch(customer);
 await owner.locator('#incomingMode').click();await f.pos('/api/shifts/open',{openingCash:100});
 await customer.goto(f.cloudUrl+'/customer/');await customer.locator('.product').first().waitFor();await customer.locator('#webLanguage').click();
 await customer.locator('[data-action=profile]').first().click();await customer.locator('#switchAccount').click();await customer.locator('#dialog [name=name]').fill('Kitchen Browser Customer');await customer.locator('#dialog [name=phone]').fill('01077777777');await customer.locator('#dialog [name=password]').fill('Kitchen-Test-Password-123!');await customer.locator('#dialog button[type=submit]').click();await customer.locator('#dialog').waitFor({state:'hidden'});
 for(const type of ['pickup','delivery']){
  if(type==='delivery'){await customer.locator('#webLanguage').click();await customer.locator('[data-method=delivery]').click();await kitchen.locator('#language').click();await owner.locator('#language').click()}
  await customer.locator('[data-product="1"]').first().click();await customer.locator('#dialog [name=mod1]').check();await customer.locator('#dialog [name=notes]').fill('Sauce aside');await customer.locator('#dialog button[type=submit]').click();await customer.locator('#dialog').waitFor({state:'hidden'});await customer.locator('[data-action=cart]').click();await customer.locator('#checkout').click();await customer.locator('#dialog [name=notes]').fill('Call on arrival');if(type==='delivery')await customer.locator('#dialog [name=fullAddress]').fill('Isolated browser delivery address');await customer.locator('#checkoutNext').click();await customer.locator('#checkoutNext').click();const response=customer.waitForResponse(r=>r.url().endsWith('/api/orders')&&r.request().method()==='POST');await customer.locator('#checkoutNext').click();const placed=(await(await response).json()).order;await customer.locator('.success-copy').waitFor();assert.match(await customer.locator('.success-copy').innerText(),/waiting for restaurant confirmation|في انتظار تأكيد المطعم/);await customer.locator('#dialog button[type=submit]').click();
  await owner.locator(`[data-online-accept="${placed.id}"]`).waitFor({timeout:15000});assert.equal((await f.pos('/api/orders')).orders.filter(o=>o.request_id===placed.id).length,0);assert.equal(await kitchen.locator('[data-forward]').count(),0);
  await owner.locator(`[data-online-accept="${placed.id}"]`).click();const local=await f.until(async()=>(await f.pos('/api/orders')).orders.find(o=>o.request_id===placed.id));try{await kitchen.locator(`[data-forward="${local.id}"]`).waitFor({timeout:10000})}catch(e){throw Error(await kitchen.locator("#content").innerText()+" TOAST "+await kitchen.locator("#toast").innerText()+" ERRORS "+JSON.stringify(errors)+" OWNERAPI "+JSON.stringify(await f.pos("/api/orders?active_kitchen=1&status=completed"))+" KITCHENAPI "+await kitchen.evaluate(async()=>JSON.stringify(await fetch("/api/orders?active_kitchen=1&status=completed",{headers:{authorization:"Bearer "+localStorage.getItem("tb_token")}}).then(r=>r.json()))))}
  const card=kitchen.locator('.ticket').filter({has:kitchen.locator(`[data-forward="${local.id}"]`)});assert.match(await card.innerText(),/Sauce aside/);assert.match(await card.innerText(),/Call on arrival/);assert.match(await card.innerText(),/WEB/);assert(!/01077777777|165|EGP/.test(await card.innerText()));
  await f.until(async()=>(await fetch(f.cloudUrl+'/api/tracking/'+placed.trackingToken).then(r=>r.json())).order.status==='confirmed');
  for(const [next,cloud] of [['preparing','preparing'],['ready','ready'],['fulfilled','completed']]){if(next==='fulfilled')await f.pos('/api/orders/'+local.id+'/collect',{payments:[{methodId:1,amount:local.total}]});await kitchen.locator(`[data-forward="${local.id}"][data-next="${next}"]`).click();await f.until(async()=>(await fetch(f.cloudUrl+'/api/tracking/'+placed.trackingToken).then(r=>r.json())).order.status===cloud);if(next!=='fulfilled')await kitchen.locator(`[data-kitchen-state="${next}"] [data-forward="${local.id}"]`).waitFor();}
  await kitchen.locator(`[data-forward="${local.id}"]`).waitFor({state:'detached'});await customer.reload();await customer.locator('#tracking').waitFor();assert.match(await customer.locator('#tracking').innerText(),/Completed|تم التسليم|بالهنا/);await kitchen.reload();await kitchen.locator('#workspace').waitFor();assert.equal(await kitchen.locator(`[data-forward="${local.id}"]`).count(),0);
  checks.push(type+': real customer signup/session checkout → incoming → explicit Accept → three one-tap kitchen states → customer completion; notes, modifier, privacy, refresh');
 }
 await owner.locator('[data-view=settings]').click();await owner.locator('[data-settings=backup]').click();await owner.locator('#onlineSettings').waitFor();assert.match(await owner.locator('#content').innerText(),/DEMO/);checks.push('Owner sync pairing and timeout settings are visible');
 await kitchen.locator('#logout').click();await kitchen.locator('#login').waitFor({state:'visible'});let requests=0;kitchen.on('request',r=>{if(r.url().includes('/api/orders'))requests++});await kitchen.waitForTimeout(3500);assert.equal(requests,0);checks.push('polling stops after logout');
 assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth),390);assert.deepEqual(errors,[]);checks.push('Arabic RTL, English, mobile width and zero unexpected browser console errors');console.log(JSON.stringify({ok:true,scenarios:checks.length,checks},null,2));
 }finally{await browser?.close();await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
