const assert=require('node:assert/strict'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite');
(async()=>{const f=await require('./fixture.cjs')();const checks=[];let db;try{
 db=new DatabaseSync(f.database);const cloudDb=await f.mf.getD1Database('DB');
 const request=async(path,b,status=200)=>{const r=await fetch(f.cloudUrl+path,{method:b?'POST':'GET',headers:{origin:f.cloudUrl,'content-type':'application/json'},body:b?JSON.stringify(b):undefined}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d};
 const wait=id=>f.until(async()=>(await f.pos('/api/orders')).incomingOnlineOrders.find(o=>o.id===id));
 const place=async(extra={})=>{const b={requestId:crypto.randomUUID(),items:[{productId:4,qty:1}],customerName:'Isolated confirmation test',customerPhone:'01066666666',orderType:'pickup',expectedTotal:35,...extra};const order=(await request('/api/orders',b,201)).order;await wait(order.id);return {order,body:b}};
 const totals=()=>({orders:db.prepare('SELECT COUNT(*) n FROM orders').get().n,stock:db.prepare('SELECT COUNT(*) n FROM stock_movements').get().n,prints:db.prepare('SELECT COUNT(*) n FROM print_queue').get().n,payments:db.prepare('SELECT COUNT(*) n FROM payments').get().n,points:db.prepare('SELECT COUNT(*) n FROM loyalty_ledger').get().n});
 const before=totals(),first=await place();assert.equal(first.order.status,'awaiting_restaurant_confirmation');assert.deepEqual(totals(),before);checks.push('durable inbox arrival creates no order, stock movement, payment, points or print');
 await f.stopLocal();await f.startLocal();assert(await wait(first.order.id));checks.push('pending inbox survives POS process restart');
 const accepted=await Promise.all([f.pos('/api/online-orders/'+first.order.id+'/accept',{}),f.pos('/api/online-orders/'+first.order.id+'/accept',{})]);assert.equal(accepted[0].order.id,accepted[1].order.id);assert(accepted.some(x=>x.alreadyAccepted));assert.equal(totals().orders,before.orders+1);assert.equal(totals().stock,before.stock+1);assert.equal(db.prepare("SELECT COUNT(*) n FROM print_queue WHERE order_id=? AND job_type='kitchen' AND document_kind='original'").get(accepted[0].order.id).n,1);checks.push('simultaneous Accept creates one order, one deduction, one original kitchen ticket');
 assert.equal((await request('/api/tracking/'+first.order.trackingToken)).order.status,'confirmed');assert.equal((await request('/api/orders',first.body,201)).order.id,first.order.id);checks.push('duplicate website request and cloud confirmation preserve identity');
 const second=await place();await f.pos('/api/online-orders/'+second.order.id+'/reject',{reason:'Kitchen overloaded'});assert.equal((await request('/api/tracking/'+second.order.trackingToken)).order.rejection_reason,'Kitchen overloaded');await assert.rejects(()=>f.pos('/api/online-orders/'+second.order.id+'/accept',{}));checks.push('rejection is visible to customer and cannot subsequently accept');
 const third=await place();const config=(await f.pos('/api/settings/consumption-locations')).rows.filter(r=>r.station_code==='drinks').map(r=>r.location_id);
 await f.pos('/api/settings/consumption-locations',{stationCode:'drinks',locationIds:[1]});const snapshot=totals();await assert.rejects(()=>f.pos('/api/online-orders/'+third.order.id+'/accept',{}),/needs review/);assert.deepEqual(totals(),snapshot);assert.equal((await wait(third.order.id)).reason,'stock');checks.push('insufficient preparation stock is durable Needs Review with complete rollback');
 await f.pos('/api/settings/consumption-locations',{stationCode:'drinks',locationIds:config});await f.pos('/api/online-orders/'+third.order.id+'/retry',{});assert.equal((await wait(third.order.id)).status,'awaiting_restaurant_confirmation');assert.deepEqual(totals(),snapshot);await f.pos('/api/online-orders/'+third.order.id+'/accept',{});checks.push('Retry validates without accepting or deducting; explicit Accept remains required');
 for(const [label,trigger] of [
  ['after first stock deduction',"AFTER INSERT ON stock_movements WHEN NEW.movement_type='sale'"],
  ['before kitchen print queue',"BEFORE INSERT ON print_queue"],
  ['before cloud mapping',"BEFORE INSERT ON cloud_imports"],
  ['before local decision commit',"BEFORE UPDATE ON online_order_inbox WHEN NEW.status='confirmed'"]
 ]){const x=await place(),base=totals();db.exec(`CREATE TRIGGER injected_failure ${trigger} BEGIN SELECT RAISE(ABORT,'Injected transaction failure'); END`);await assert.rejects(()=>f.pos('/api/online-orders/'+x.order.id+'/accept',{}));db.exec('DROP TRIGGER injected_failure');assert.deepEqual(totals(),base);assert.equal(db.prepare('SELECT COUNT(*) n FROM cloud_imports WHERE cloud_order_id=?').get(x.order.id).n,0);assert.equal((await wait(x.order.id)).status,'needs_review');await f.pos('/api/online-orders/'+x.order.id+'/reject',{reason:'Isolated failure injection'});checks.push('atomic rollback '+label)}
 for(const stage of ['before','after']){const x=await place();f.setCloudFault({path:'/ack',stage});const result=await f.pos('/api/online-orders/'+x.order.id+'/accept',{});assert(result.ackPending);await f.pos('/api/orders/'+result.order.id+'/fulfill',{status:'preparing'});const committed=totals();await f.stopLocal();f.setCloudFault(null);await f.startLocal();await f.until(async()=>(await request('/api/tracking/'+x.order.trackingToken)).order.status==='preparing');assert.equal((await f.pos('/api/online-orders/'+x.order.id+'/accept',{})).order.id,result.order.id);assert.deepEqual(totals(),committed);checks.push('crash after local commit with ACK failure '+stage+' cloud commit recovers exactly once and delivers queued kitchen progress')}
 const priced=await place(),priceBefore=totals();db.prepare('UPDATE products SET price=36 WHERE id=4').run();await assert.rejects(()=>f.pos('/api/online-orders/'+priced.order.id+'/accept',{}));assert.equal((await wait(priced.order.id)).reason,'price');assert.deepEqual(totals(),priceBefore);db.prepare('UPDATE products SET price=35 WHERE id=4').run();await f.pos('/api/online-orders/'+priced.order.id+'/reject',{reason:'Isolated price check'});checks.push('changed menu price enters Needs Review without silent repricing or side effects');
 const offline=await place();f.setCloudAvailable(false);await f.until(async()=>(await f.pos('/api/status')).sync.online===false);assert(await wait(offline.order.id));await f.stopLocal();await f.startLocal();assert(await wait(offline.order.id));f.setCloudAvailable(true);await f.until(async()=>(await f.pos('/api/status')).sync.online);await f.pos('/api/online-orders/'+offline.order.id+'/accept',{});checks.push('internet interruption and restart preserve waiting order for explicit acceptance');
 const local=accepted[0].order;await f.pos('/api/orders/'+local.id+'/fulfill',{status:'preparing'});await f.pos('/api/orders/'+local.id+'/fulfill',{status:'preparing'});await assert.rejects(()=>f.pos('/api/orders/'+local.id+'/fulfill',{status:'fulfilled'}));await f.pos('/api/orders/'+local.id+'/fulfill',{status:'ready'});await assert.rejects(()=>f.pos('/api/orders/'+local.id+'/fulfill',{status:'fulfilled'}),/Collect payment/);checks.push('state machine enforces forward flow, idempotent same-state retry and payment separation');
 await f.pos('/api/shifts/open',{openingCash:100});const paymentBefore=totals();db.exec("CREATE TRIGGER injected_payment BEFORE INSERT ON payments BEGIN SELECT RAISE(ABORT,'Injected payment failure'); END");await assert.rejects(()=>f.pos('/api/orders/'+local.id+'/collect',{payments:[{methodId:1,amount:35}]}));db.exec('DROP TRIGGER injected_payment');assert.deepEqual(totals(),paymentBefore);assert.equal(db.prepare('SELECT payment_status FROM orders WHERE id=?').get(local.id).payment_status,'due');checks.push('payment insert failure preserves unpaid order and rolls back collection');await f.pos('/api/orders/'+local.id+'/collect',{payments:[{methodId:1,amount:35}]});await f.pos('/api/orders/'+local.id+'/fulfill',{status:'fulfilled'});await f.until(async()=>(await request('/api/tracking/'+first.order.trackingToken)).order.status==='completed');checks.push('customer tracking follows restaurant fulfillment');
 await f.pos('/api/orders/'+local.id+'/refund',{reason:'Isolated refund',restock:true});const refundSnapshot=totals();await assert.rejects(()=>f.pos('/api/orders/'+local.id+'/refund',{reason:'Duplicate',restock:true}));assert.deepEqual(totals(),refundSnapshot);checks.push('refund cannot repeat inventory or loyalty reversal');
 const job=db.prepare("SELECT id FROM print_queue WHERE order_id=? AND job_type='kitchen' LIMIT 1").get(accepted[1].order.id);await assert.rejects(()=>f.pos('/api/printing/jobs/'+job.id+'/retry',{}));assert.equal(db.prepare('SELECT COUNT(*) n FROM orders WHERE id=?').get(accepted[1].order.id).n,1);checks.push('printer transport failure preserves committed order');
 await f.stopLocal();await cloudDb.prepare("UPDATE site_state SET value='2000-01-01T00:00:00Z' WHERE key='heartbeat'").run();await request('/api/orders',{...first.body,requestId:crypto.randomUUID()},503);checks.push('stale heartbeat rejects new checkout while existing tracking remains readable');
 console.log(JSON.stringify({ok:true,scenarios:checks.length,checks},null,2));
 }finally{db?.close();await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
