const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),dir=fs.mkdtempSync(path.join(root,'.runtime','menu-seed-'));process.env.DEMO_MODE='true';process.env.TRACKBITE_DB=path.join(dir,'test.db');
const {db,one,all,run}=require('../src/db'),costing=require('../src/costing'),stock=require('../src/stock-ledger'),admin=require('../src/admin'),orders=require('../src/orders'),{seed}=require('../tools/seed-real-menu');
const checks=[];try{
 const history=()=>JSON.stringify(Object.fromEntries(['orders','purchases','stock_movements','customers','recipe_lines','modifiers'].map(t=>[t,all('SELECT * FROM '+t)])));const before=history(),first=seed(),counts=()=>Object.fromEntries(['categories','products','ingredients','modifier_templates'].map(t=>[t,one('SELECT COUNT(*) n FROM '+t).n]));const once=counts();seed();assert.deepEqual(counts(),once);checks.push('second seed creates no duplicate category, product, ingredient or modifier template');assert.equal(history(),before);checks.push('existing orders, purchases, stock, customers, recipes and modifiers unchanged');
 assert.equal(first.totalMenuItems,29);assert.equal(first.products.created,28);assert.equal(first.products.reused,1);checks.push('29 specified SKUs represented; existing Cola reused');
 assert.equal(one('SELECT COUNT(*) n FROM products').n,one('SELECT COUNT(DISTINCT sku) n FROM products').n);assert.equal(one("SELECT COUNT(*) n FROM ingredients WHERE name_en IN ('Farm Frites','McCain')").n,0);checks.push('unique SKUs and generic ingredient identities');
 assert.equal(one('SELECT COUNT(*) n FROM modifier_templates WHERE price IS NULL AND active=0').n,7);checks.push('seven reusable extra templates have unknown prices and remain inactive');
 const draft=one("SELECT * FROM products WHERE sku='SIDE-FRIES'");assert.equal(draft.price_known,0);assert.equal(draft.available_online,0);assert(!require('../src/catalog').build().products.some(p=>p.id===draft.id));assert.throws(()=>orders.normalize([{productId:draft.id,qty:1}]),/unavailable|incomplete/);checks.push('draft product cannot publish or be sold for zero');
 const ingredient=one("SELECT * FROM ingredients WHERE code='FRIES'");assert.equal(all('SELECT * FROM ingredients WHERE name_en IN (\'French Fries\',\'Fries\',\'Potatoes\')').length,1);checks.push('existing equivalent fries ingredient reused');
 admin.setRecipe({productId:draft.id,lines:[{ingredientId:ingredient.id,quantityBase:250}]});let p=costing.products().find(p=>p.id===draft.id);assert.equal(p.cost,null);assert.equal(p.margin,null);assert.equal(p.food_cost_percent,null);assert.equal(p.cost_status,'cost_incomplete');checks.push('missing ingredient cost yields incomplete totals and no profit percentages');
 const variant=one('SELECT * FROM ingredient_variants WHERE ingredient_id=? ORDER BY id LIMIT 1',ingredient.id);stock.receiveStock({variantId:variant.id,locationId:3,quantityPurchase:10,unitPricePurchase:80,userId:1});p=costing.products().find(p=>p.id===draft.id);assert.equal(p.cost,20);assert.equal(p.price,null);assert.equal(p.margin,null);checks.push('recipe can be costed before selling price is entered');
 run("UPDATE products SET price=60,price_known=1,in_stock=1,available_online=1 WHERE id=?",draft.id);p=costing.products().find(p=>p.id===draft.id);assert.equal(p.margin,40);assert.equal(p.cost_status,'complete');assert(require('../src/catalog').build().products.some(x=>x.id===draft.id));checks.push('manual price, complete recipe and known cost allow intentional publication');
 run("UPDATE settings SET value='latest' WHERE key='costing_method'");stock.receiveStock({variantId:variant.id,locationId:3,quantityPurchase:10,unitPricePurchase:100,userId:1});assert.equal(costing.products().find(p=>p.id===draft.id).cost,25);run("UPDATE settings SET value='average' WHERE key='costing_method'");assert.equal(costing.products().find(p=>p.id===draft.id).cost,22.5);checks.push('latest and quantity-weighted average purchase costs recalculate recipes');
 const cola=one("SELECT * FROM ingredients WHERE code='COLA'"),carton=one("SELECT * FROM ingredient_variants WHERE ingredient_id=? AND purchase_unit='carton'",cola.id);stock.receiveStock({variantId:carton.id,locationId:4,quantityPurchase:1,unitPricePurchase:240,userId:1});assert.equal(costing.ingredientCost(cola.id),10);checks.push('24-piece carton purchase cost converts to per-piece cost');
 const box=one("SELECT * FROM ingredients WHERE code='FRIES-BOX'");admin.setRecipe({productId:draft.id,lines:[{ingredientId:ingredient.id,quantityBase:250},{ingredientId:box.id,quantityBase:1}]});p=costing.products().find(p=>p.id===draft.id);assert.equal(p.cost,null);assert.equal(p.known_cost,22.5);assert.equal(p.missing_costs[0].id,box.id);assert(!require('../src/catalog').build().products.some(x=>x.id===draft.id));checks.push('missing packaging cost shows known subtotal and blocks incomplete draft publication');
 const historical=history();seed({experimentalExisting:true});const archived=one('SELECT COUNT(*) n FROM experimental_menu_archive').n;assert(archived>0);assert.equal(history(),historical);assert.equal(one('SELECT COUNT(*) n FROM products WHERE experimental=1 AND (in_stock=1 OR available_online=1 OR price_known=1 OR recipe_verified=1)').n,0);assert(costing.products().filter(p=>p.experimental).every(p=>p.price===null&&p.cost===null&&p.lines.length===0));seed({experimentalExisting:true});assert.equal(one('SELECT COUNT(*) n FROM experimental_menu_archive').n,archived);assert.equal(history(),historical);checks.push('experimental menu archive is idempotent, preserves history and excludes unverified prices/recipes from sales and costing');
 stock.receiveStock({variantId:variant.id,locationId:3,quantityPurchase:1,userId:1});assert.equal(one('SELECT unit_cost_base FROM stock_movements ORDER BY id DESC LIMIT 1').unit_cost_base,null);checks.push('receipt with unknown price remains unknown rather than zero');
 console.log(JSON.stringify({ok:true,scenarios:checks.length,checks},null,2));
}finally{db.close();if(path.resolve(dir).startsWith(path.join(root,'.runtime')+path.sep))fs.rmSync(dir,{recursive:true,force:true})}
