const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {spawn}=require('child_process');const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(__dirname,'resilience-')),secret='test-'+crypto.randomUUID();let local,cloud,token;const sleep=ms=>new Promise(r=>setTimeout(r,ms));let logs='';function start(script,env){const p=spawn(process.execPath,[script],{cwd:root,env:{...process.env,...env,SYNC_SECRET:secret},stdio:['ignore','pipe','pipe']});p.stderr.on('data',d=>logs+=d);return p}
async function j(base,url,b,auth=token){const r=await fetch(base+url,{method:b===undefined?'GET':'POST',headers:{'content-type':'application/json',...(auth?{authorization:'Bearer '+auth}:{})},body:b===undefined?undefined:JSON.stringify(b)});const d=await r.json();if(!r.ok)throw new Error(url+': '+JSON.stringify(d));return d}
const L='http://127.0.0.1:4198',C='http://127.0.0.1:5198';async function until(fn){for(let i=0;i<100;i++){try{const r=await fn();if(r)return r}catch{}await sleep(100)}throw new Error('Timed out\n'+logs)}
(async()=>{try{local=start('server.js',{PORT:'4198',TRACKBITE_DB:path.join(dir,'local.db'),CLOUD_API_URL:C,SYNC_INTERVAL_MS:'200'});await until(()=>j(L,'/api/status'));token=(await j(L,'/api/login',{username:'owner',password:'1234'},null)).token;await j(L,'/api/shifts/open',{openingCash:500});await j(L,'/api/orders',{items:[{productId:4,qty:1}],payments:[{methodId:1,amount:35}],requestId:crypto.randomUUID()});assert((await j(L,'/api/sync/status')).pending>0);assert.equal((await j(L,'/api/status')).sync.online,false);
 await j(L,'/api/settings',{delivery_fee:'20',tax_enabled:'true',tax_type:'percentage',tax_value:'14'});
 cloud=start('cloud/server.js',{CLOUD_PORT:'5198',CLOUD_DB:path.join(dir,'cloud.db')});await until(()=>j(C,'/api/status',undefined,null));await until(async()=>{const m=await j(C,'/api/public/menu',undefined,null);return m.products.length&&m.settings.tax_enabled==='true'&&m});await until(async()=>(await j(L,'/api/sync/status')).pending===0);
 const payload={requestId:crypto.randomUUID(),items:[{productId:1,qty:1,modifiers:[1],notes:'No onions'}],customerName:'Delivery Test',customerPhone:'01012345678',orderType:'delivery',deliveryDetails:{area:'Cairo',fullAddress:'Building 1'},deliveryAddress:'Building 1',notes:'Call outside'};const placed=(await j(C,'/api/orders',payload,null)).order;assert.equal(placed.total,208.1);assert.equal((await j(C,'/api/orders',payload,null)).order.id,placed.id);const imported=await until(async()=>{const {orders}=await j(L,'/api/orders');return orders.find(o=>o.request_id===placed.id)});assert.equal(imported.payment_status,'due');assert.equal(imported.total,placed.total);assert.equal((await j(L,'/api/orders/'+imported.id)).order.payments.length,0);
 const status=await until(async()=>{const {order}=await j(C,'/api/tracking/'+placed.trackingToken,undefined,null);return order.status==='accepted'&&order});assert.equal(status.payment_status,'due');
 await j(L,'/api/orders/'+imported.id+'/collect',{payments:[{methodId:1,amount:208.1}]});await j(L,'/api/orders/'+imported.id+'/fulfill',{status:'preparing'});await until(async()=>(await j(C,'/api/tracking/'+placed.trackingToken,undefined,null)).order.status==='preparing');
 await new Promise(resolve=>{cloud.once('exit',resolve);cloud.kill()});cloud=null;await j(L,'/api/sync/retry',{});assert.equal((await j(L,'/api/status')).sync.online,false);const offline=(await j(L,'/api/orders',{items:[{productId:4,qty:1}],payments:[{methodId:1,amount:39.9}],requestId:crypto.randomUUID()})).order;assert.equal(offline.total,39.9);assert((await j(L,'/api/sync/status')).pending>0);
 cloud=start('cloud/server.js',{CLOUD_PORT:'5198',CLOUD_DB:path.join(dir,'cloud.db')});await until(()=>j(C,'/api/status',undefined,null));await until(async()=>(await j(L,'/api/sync/status')).pending===0);const {orders}=await j(L,'/api/orders');assert.equal(orders.filter(o=>o.request_id===placed.id).length,1);
 const events=await fetch(C+'/api/sync/events',{headers:{'x-sync-secret':secret}}).then(r=>r.json());assert(events.rows.length>0);const event=events.rows[0];const before=events.rows.length;const replay=await fetch(C+'/api/sync/events',{method:'POST',headers:{'content-type':'application/json','x-sync-secret':secret},body:JSON.stringify({eventKey:event.event_key,eventType:event.event_type,payload:JSON.parse(event.payload)})});assert(replay.ok);assert.equal((await fetch(C+'/api/sync/events',{headers:{'x-sync-secret':secret}}).then(r=>r.json())).rows.length,before);
 console.log(JSON.stringify({ok:true,checks:['offline local sales','outbox recovery','shared website pricing','delivery modifiers and notes','web request idempotency','deferred payment collection','customer order tracking','reconnection without duplicate imports','cloud event deduplication']},null,2));
 }finally{local?.kill();cloud?.kill();await sleep(200);const resolved=path.resolve(dir);if(resolved.startsWith(path.resolve(__dirname)+path.sep)&&path.basename(resolved).startsWith('resilience-'))fs.rmSync(resolved,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
