process.env.DEMO_MODE='true';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'../..');fs.mkdirSync(path.join(root,'.runtime'),{recursive:true});const dir=fs.mkdtempSync(path.join(root,'.runtime','security-')),dbFile=path.join(dir,'test.db');process.env.TRACKBITE_DB=dbFile;
const {db,one,all,run,transaction}=require('../src/db'),auth=require('../src/auth'),permissions=require('../src/permissions'),{routes}=require('../src/routes'),v=require('../public/shared/validation'),stock=require('../src/stock-ledger'),loyalty=require('../src/loyalty'),orders=require('../src/orders');let server;
(async()=>{try{
 require('./inventory-edges.cjs')({db,one,run,transaction},stock);
 assert.equal(v.canonical({b:1,a:{z:1,x:2}}),v.canonical({a:{x:2,z:1},b:1}));for(const qty of [0,-1,0.5,100,Infinity])assert.throws(()=>v.items([{productId:1,qty}]));assert.equal(v.phone('010 1234 5678'),'+201012345678');
 const owner=one("SELECT * FROM users WHERE username='owner'"),token=auth.createSession(owner);assert(one('SELECT token_hash FROM staff_sessions').token_hash!==token);assert.equal(auth.getSession({headers:{authorization:'Bearer '+token}}).global_id,owner.global_id);auth.revoke(owner.id);assert.equal(auth.getSession({headers:{authorization:'Bearer '+token}}),null);
 assert.throws(()=>run('UPDATE ingredient_variants SET active=0 WHERE id=2'),/deplete/);
 const initial=one('SELECT COUNT(*) n FROM stock_movements').n;assert.throws(()=>transaction(()=>stock.consumeIngredient({ingredientId:2,quantityBase:999,referenceType:'test',referenceId:'test'})),/Transfer/);assert.equal(one('SELECT COUNT(*) n FROM stock_movements').n,initial);
 transaction(()=>{stock.transferStock({variantId:2,fromLocationId:3,toLocationId:1,quantityPurchase:120,userId:owner.id});assert.throws(()=>stock.consumeIngredient({ingredientId:2,quantityBase:1,referenceType:'test',referenceId:'test'}),/Transfer/);stock.transferStock({variantId:2,fromLocationId:1,toLocationId:3,quantityPurchase:120,userId:owner.id})});
 const customerId=crypto.randomUUID();run('INSERT INTO customers(id,name,phone) VALUES(?,?,?)',customerId,'Isolated','+201099999999');const sh=Number(run('INSERT INTO shifts(user_id,opening_cash) VALUES(?,0)',owner.id).lastInsertRowid);
 const input={customerId,customerName:'Isolated',customerPhone:'01099999999',userId:owner.id,shiftId:sh,items:[{productId:4,qty:1}],payments:[{methodId:1,amount:35}],requestId:crypto.randomUUID()};const order=orders.createOrder(input);assert.equal(order.daily_no,1);assert(order.order_date);for(const state of ['preparing','ready','fulfilled'])orders.fulfill(order.id,state,owner);assert.equal(loyalty.balance(customerId),3);loyalty.reconcile(orders.getOrder(order.id),owner);assert.equal(loyalty.balance(customerId),3);orders.refund(order.id,{reason:'Isolated test',restock:false},owner);assert.equal(loyalty.balance(customerId),0);assert.throws(()=>run('DELETE FROM loyalty_ledger'),/immutable/);
 const policy=require('../src/sync-policy');assert.throws(()=>policy.configuration({CLOUD_API_URL:'https://test.example'}),/SYNC_SECRET/);assert.equal(policy.backoff(1,()=>0.5),1000);assert(policy.backoff(99,()=>1)<=375000);
 assert(fs.readdirSync(path.join(dir,'backups')).some(n=>n.startsWith('before-v9')));const migrations=all('SELECT version FROM schema_migrations').map(r=>r.version);assert.deepEqual(migrations,[3,4,5,6,7,8,9,10,11,12,13]);require('../src/reliability-migration')(db,dbFile);assert.equal(one("SELECT global_id FROM users WHERE username='owner'").global_id,owner.global_id);
 require('./migration-upgrade.cjs')(dir);
 const set=new Set(routes.map(r=>r.method+' '+r.path));assert.equal(set.size,routes.length);const publicRoutes=routes.filter(r=>!r.permission);assert.equal(publicRoutes.length,5);
 server=spawn(process.execPath,['server.js'],{cwd:path.join(root,'trackbite-system'),env:{...process.env,PORT:'4196',CLOUD_API_URL:''},stdio:'ignore'});for(let i=0;i<80;i++){try{if((await fetch('http://127.0.0.1:4196/api/status')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 const call=(route,token,body)=>fetch('http://127.0.0.1:4196'+route.path.replace(/:[a-z]+/g,'999999'),{method:route.method,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:['GET','HEAD'].includes(route.method)?undefined:JSON.stringify(body||{})});
 let checks=0;
 for(const route of routes.filter(r=>r.permission)){assert.equal((await call(route)).status,401,'anonymous '+route.path);checks++}
 for(const user of all('SELECT * FROM users')){const session=auth.createSession(user);for(const route of routes.filter(r=>r.permission&&r.permission!=='authenticated')){const allowed=permissions.can(user,route.permission);if(!allowed)assert.equal((await call(route,session)).status,403,user.role+' '+route.method+' '+route.path);checks++}}
 const cashierUser=one("SELECT * FROM users WHERE role='cashier'");run("INSERT INTO role_permissions(role,permission,allowed) VALUES('cashier','customers.pii',0) ON CONFLICT(role,permission) DO UPDATE SET allowed=0");
 const kitchen=auth.createSession(one("SELECT * FROM users WHERE role='kitchen'")),cashier=auth.createSession(one("SELECT * FROM users WHERE role='cashier'"));const bootstrap=await (await call({method:'GET',path:'/api/bootstrap'},kitchen)).json();assert(!JSON.stringify(bootstrap).includes('installation_id'));assert.deepEqual(bootstrap.paymentMethods,[]);assert(bootstrap.products.every(p=>p.price===undefined));
 const jobs=await(await call({method:'GET',path:'/api/printing/jobs'},kitchen)).json();assert(jobs.rows.every(j=>j.job_type==='kitchen'&&j.payload===undefined));const receipt=one("SELECT id FROM print_queue WHERE job_type='customer'");assert.equal((await call({method:'GET',path:'/api/printing/jobs/'+receipt.id+'/preview'},kitchen)).status,403);
 const cashierOrders=await(await call({method:'GET',path:'/api/orders'},cashier)).json();assert(cashierOrders.orders.every(o=>o.customer_phone===undefined));assert.equal((await call({method:'GET',path:'/api/printing/jobs/'+receipt.id+'/preview'},cashier)).status,403);
 const health=await(await call({method:'GET',path:'/api/status'})).json();assert.equal(health.db,undefined);assert.equal((await fetch('http://127.0.0.1:4196/api/orders',{method:'POST',headers:{'x-public-order':'1','content-type':'application/json'},body:'{}'})).status,401);
 console.log(JSON.stringify({ok:true,authorizationCases:checks,protectedEndpoints:routes.filter(r=>r.permission).length,checks:['every role and endpoint denial matrix','canonical hashes','integer quantity bounds','phone normalization','hashed revocable sessions','verified pre-migration backup','migration idempotency','variant deactivation guard','physical stock locations','FIFO FEFO preferred brand and variant-specific allocation','restaurant-timezone expiry boundary','failed production and transfer rollback','negative stock and invalid expiry rejection','loyalty earns once and refund reversal','immutable points','bounded retry backoff','production secret validation','role-aware bootstrap','kitchen receipt access denied','legacy anonymous orders denied']},null,2));
 }finally{if(server)await new Promise(r=>{server.once('exit',r);server.kill()});db.close();if(path.resolve(dir).startsWith(path.join(root,'.runtime')+path.sep))fs.rmSync(dir,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
