const assert=require('node:assert/strict');
module.exports=async(page,f)=>{
 const dialogSubmit=async()=>{await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'})};
 const postForm=async(id,url,fields)=>{for(const [name,value] of Object.entries(fields)){const el=page.locator('#'+id+' [name='+name+']');if(await el.evaluate(e=>e.tagName==='SELECT'))await el.selectOption(String(value));else await el.fill(String(value))}const response=page.waitForResponse(r=>r.url().includes(url)&&r.request().method()==='POST');await page.locator('#'+id+' button[type=submit], #'+id+' button.primary').last().click();assert((await response).ok(),url);await page.locator('#'+id).waitFor({state:'hidden'})};
 await page.locator('[data-view=pos]').click();await page.locator('#shiftAction').click();await page.locator('#dialog [name=cash]').fill('1000');await dialogSubmit();await page.locator('#findCustomer').click();await page.locator('#dialog [name=query]').fill('Browser Account');await page.locator('[data-attach]').first().waitFor();await page.locator('[data-attach]').first().click();
 await page.locator('[data-product="1"]').click();await page.locator('#dialog [name=notes]').fill('Browser staff order');await dialogSubmit();await page.locator('#splitPayment').click();await page.locator('[data-pay]').nth(0).fill('100');await page.locator('[data-pay]').nth(1).fill('50');await page.locator('#paymentLines select').nth(1).selectOption('4');if(await page.locator('#paymentLines .reference').nth(1).isVisible())await page.locator('#paymentLines .reference').nth(1).fill('TEST-REFERENCE');await page.locator('#complete').click();await page.locator('#lastOrder a').waitFor();
 const popup=page.waitForEvent('popup');await page.locator('#lastOrder a').click();const print=await popup;await print.waitForLoadState('domcontentloaded');assert((await print.locator('body').innerText()).length>20);await print.close();
 const created=(await f.pos('/api/orders')).orders.find(o=>o.source==='pos');assert(created);const detail=(await f.pos('/api/orders/'+created.id)).order;assert.equal(detail.payments.length,2);assert(detail.customer_id);
 await page.locator('[data-view=orders]').click();for(let i=0;i<3;i++){await page.locator('[data-order="'+created.id+'"]').click();try{await page.locator('#nextState').click({timeout:5000})}catch(e){throw Error('Kitchen progression '+i+': '+await page.locator('#dialog').innerText()+' TOAST '+await page.locator('#toast').innerText()+' ORDER '+JSON.stringify((await f.pos('/api/orders/'+created.id)).order))}await page.locator('#dialog').waitFor({state:'hidden'})}
 await page.locator('[data-view=inventory]').click();await page.locator('[data-tab=receive]').click();await postForm('receive','/api/inventory/receive-simple',{ingredientId:1,unit:'g',locationId:1,quantityPurchase:1000,unitPricePurchase:0});
 await page.locator('[data-tab=receive]').click();await postForm('transfer','/api/inventory/transfer',{variantId:2,fromLocationId:3,toLocationId:5,quantityPurchase:1,note:'Browser transfer'});
 await page.locator('[data-tab=receive]').click();await postForm('waste','/api/inventory/waste',{variantId:2,locationId:5,quantityPurchase:1,note:'Browser waste'});
 await page.locator('[data-tab=production]').click();for(const [target,fields] of Object.entries({inputs:{variantId:1,locationId:1,quantityPurchase:1},outputs:{variantId:2,locationId:3,quantityPurchase:10}}))for(const [name,value] of Object.entries(fields)){const el=page.locator('#'+target+' [name='+name+']');if(name==='quantityPurchase')await el.fill(String(value));else await el.selectOption(String(value))}const produced=page.waitForResponse(r=>r.url().endsWith('/api/production')&&r.request().method()==='POST');await page.locator('#production button.primary').click();assert((await produced).ok());await page.locator('#production').waitFor({state:'hidden'});
 await page.locator('[data-tab=stocktake]').click();await postForm('stocktake','/api/stocktake',{variantId:2,locationId:5,quantityPurchase:0,note:'Browser count'});
 await page.locator('[data-view=menu]').click();await page.locator('[data-item="1"]').click();await page.locator('#recipeLines [data-qty]').first().fill('1');await page.locator('#itemForm [name=reason]').fill('Isolated browser recipe edit');await page.locator('#itemForm button.primary').click();await page.locator('#menuRows').waitFor();
 await page.locator('[data-view=reports]').click();await page.locator('#content table').first().waitFor();
 await page.locator('[data-view=pos]').click();await page.locator('#shiftAction').click();await page.locator('#dialog [name=cash]').fill('1100');await dialogSubmit();return created.id;
};
