const assert=require('node:assert/strict'),crypto=require('node:crypto');
(async()=>{const f=await require('./fixture.cjs')(),checks=[];try{
const created=await f.pos('/api/materials',{nameAr:'خامة تجربة',nameEn:'UX material',unit:'kg',defaultLocationId:2});const id=created.id;assert.equal((await f.pos('/api/materials',{nameAr:'  خامة   تجربة ',unit:'kg'})).id,id);checks.push('normalized material quick add reuses an existing identity');
await f.pos('/api/materials/'+id,{nameAr:'خامة تجربة معدلة',lowStock:2,defaultLocationId:3},'PATCH');let m=(await f.pos('/api/materials')).rows.find(r=>r.id===id);assert.equal(m.low_stock_base,2000);assert.equal(m.default_stock_location_id,3);checks.push('material edits use displayed units and persist default stock location');
const supplier=await f.pos('/api/ux/suppliers',{name:'أحمد فودز'});assert.equal((await f.pos('/api/ux/suppliers',{name:'احمد  فودز'})).id,supplier.id);checks.push('Arabic-normalized supplier creation does not duplicate records');
const payload={requestId:crypto.randomUUID(),supplierId:supplier.id,date:'2026-09-28',items:[{ingredientId:id,quantity:2,unit:'kg',brand:'Brand A',price:80}]};const bought=await f.pos('/api/ux/purchases',payload);assert.equal(bought.total,160);assert.equal((await f.pos('/api/ux/purchases',payload)).id,bought.id);m=(await f.pos('/api/materials')).rows.find(r=>r.id===id);assert.equal(m.quantity_base,2000);assert.equal(m.last_cost,.08);checks.push('compact invoice defaults location, normalizes price and cannot duplicate on retry');
await assert.rejects(()=>f.pos('/api/ux/purchases',{...payload,requestId:crypto.randomUUID(),items:[{...payload.items[0],price:''}]}));await assert.rejects(()=>f.pos('/api/materials/'+id,{unit:'pcs'},'PATCH'));checks.push('unknown price and incompatible historical unit changes remain blocked');
const transfer={requestId:crypto.randomUUID(),ingredientId:id,fromLocationId:3,toLocationId:2,quantity:1,unit:'kg'};await f.pos('/api/ux/transfer',transfer);await f.pos('/api/ux/transfer',transfer);assert.equal((await f.pos('/api/inventory/summary')).rows.filter(r=>r.ingredient_id===id&&r.location_id===2).reduce((n,r)=>n+r.quantity_base,0),1000);checks.push('simple transfer preserves inventory and retry idempotency');
const output=(await f.pos('/api/materials',{nameAr:'ناتج تجربة',unit:'pcs',defaultLocationId:3})).id;const production={requestId:crypto.randomUUID(),inputs:[{ingredientId:id,locationId:2,unit:'kg',quantity:1}],outputs:[{ingredientId:output,locationId:3,unit:'pcs',quantity:10}]};await f.pos('/api/production-templates',{name:'وصفة اختبار',inputs:production.inputs,outputs:production.outputs});assert.equal((await f.pos('/api/production-templates')).rows.length,1);const made=await f.pos('/api/ux/production',production);assert.equal((await f.pos('/api/ux/production',production)).id,made.id);assert.equal((await f.pos('/api/materials')).rows.find(r=>r.id===output).quantity_base,10);checks.push('saved production template and actual output use the existing ledger exactly once');
const before=(await f.pos('/api/materials')).rows.length,rows=[{Material:'CSV material',Unit:'pcs',Location:'Kitchen'},{Material:'Bad material',Unit:'invalid'}];const preview=await f.pos('/api/imports/materials/preview',{rows});assert.equal(preview.valid,1);assert.equal(preview.invalid,1);assert.equal((await f.pos('/api/materials')).rows.length,before);await assert.rejects(()=>f.pos('/api/imports/materials/commit',{requestId:crypto.randomUUID(),rows}));assert.equal((await f.pos('/api/materials')).rows.length,before);checks.push('CSV preview writes nothing and invalid commit rolls back every row');
rows.pop();const imported={requestId:crypto.randomUUID(),rows};await f.pos('/api/imports/materials/commit',imported);await f.pos('/api/imports/materials/commit',imported);assert.equal((await f.pos('/api/materials')).rows.length,before+1);checks.push('valid CSV commit creates each row once');
const invoiceRows=[{Supplier:'أحمد فودز','Invoice Date':'2026-09-28',Material:'خامة تجربة معدلة',Quantity:'1',Unit:'kg','Unit Price':'90',Location:'Kitchen'}];assert.equal((await f.pos('/api/imports/purchases/preview',{rows:invoiceRows})).invalid,0);await f.pos('/api/imports/purchases/commit',{rows:invoiceRows,requestId:crypto.randomUUID()});assert.equal((await f.pos('/api/suppliers')).rows.filter(r=>/حمد/.test(r.name)).length,1);checks.push('purchase import matches existing normalized suppliers and materials');
await f.pos('/api/materials/'+output,{active:false},'PATCH');assert.equal((await f.pos('/api/materials')).rows.find(r=>r.id===output).active,0);assert.equal((await f.pos('/api/materials')).rows.find(r=>r.id===output).quantity_base,10);checks.push('archive preserves historical prepared-stock quantities');
const duplicate1=await f.pos('/api/admin/ingredients',{nameAr:'Ambiguous input',baseUnit:'pcs'});await f.pos('/api/admin/ingredients',{nameAr:'Ambiguous input',baseUnit:'pcs'});const ambiguous=[{...invoiceRows[0],Material:'Ambiguous input',Unit:'pcs'}],review=await f.pos('/api/imports/purchases/preview',{rows:ambiguous});assert.equal(review.invalid,1);assert.equal(review.rows[0].choices.length,2);ambiguous[0].materialId=duplicate1.id;assert.equal((await f.pos('/api/imports/purchases/preview',{rows:ambiguous})).invalid,0);checks.push('ambiguous invoice matches require an explicit choice before import');
console.log(JSON.stringify({ok:true,scenarios:checks.length,checks},null,2));
}finally{await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
